// Code generated by Kitex v0.16.1. DO NOT EDIT.

package recommendservice

import (
	"context"
	recommend "gitee.com/HeXiangdong/AdvertRecommend/recommend-service/kitex_gen/recommend"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateAdPlan(ctx context.Context, req *recommend.CreateAdPlanRequest, callOptions ...callopt.Option) (r *recommend.CreateAdPlanResponse, err error)
	UpdateAdPlan(ctx context.Context, req *recommend.UpdateAdPlanRequest, callOptions ...callopt.Option) (r *recommend.UpdateAdPlanResponse, err error)
	GetAdPlan(ctx context.Context, req *recommend.GetAdPlanRequest, callOptions ...callopt.Option) (r *recommend.GetAdPlanResponse, err error)
	ListAdPlans(ctx context.Context, req *recommend.ListAdPlansRequest, callOptions ...callopt.Option) (r *recommend.ListAdPlansResponse, err error)
	DeleteAdPlan(ctx context.Context, req *recommend.DeleteAdPlanRequest, callOptions ...callopt.Option) (r *recommend.DeleteAdPlanResponse, err error)
	CreateAdCreative(ctx context.Context, req *recommend.CreateAdCreativeRequest, callOptions ...callopt.Option) (r *recommend.CreateAdCreativeResponse, err error)
	UpdateAdCreative(ctx context.Context, req *recommend.UpdateAdCreativeRequest, callOptions ...callopt.Option) (r *recommend.UpdateAdCreativeResponse, err error)
	GetAdCreative(ctx context.Context, req *recommend.GetAdCreativeRequest, callOptions ...callopt.Option) (r *recommend.GetAdCreativeResponse, err error)
	ListAdCreatives(ctx context.Context, req *recommend.ListAdCreativesRequest, callOptions ...callopt.Option) (r *recommend.ListAdCreativesResponse, err error)
	DeleteAdCreative(ctx context.Context, req *recommend.DeleteAdCreativeRequest, callOptions ...callopt.Option) (r *recommend.DeleteAdCreativeResponse, err error)
	AddUserInterest(ctx context.Context, req *recommend.AddUserInterestRequest, callOptions ...callopt.Option) (r *recommend.AddUserInterestResponse, err error)
	UpdateUserInterest(ctx context.Context, req *recommend.UpdateUserInterestRequest, callOptions ...callopt.Option) (r *recommend.UpdateUserInterestResponse, err error)
	GetUserInterests(ctx context.Context, req *recommend.GetUserInterestsRequest, callOptions ...callopt.Option) (r *recommend.GetUserInterestsResponse, err error)
	DeleteUserInterest(ctx context.Context, req *recommend.DeleteUserInterestRequest, callOptions ...callopt.Option) (r *recommend.DeleteUserInterestResponse, err error)
	CreateAdEvent(ctx context.Context, req *recommend.CreateAdEventRequest, callOptions ...callopt.Option) (r *recommend.CreateAdEventResponse, err error)
	GetUserAdEvents(ctx context.Context, req *recommend.GetUserAdEventsRequest, callOptions ...callopt.Option) (r *recommend.GetUserAdEventsResponse, err error)
	GetCreativeAdEvents(ctx context.Context, req *recommend.GetCreativeAdEventsRequest, callOptions ...callopt.Option) (r *recommend.GetCreativeAdEventsResponse, err error)
	GetAdvertRecommend(ctx context.Context, req *recommend.GetAdvertRecommendRequest, callOptions ...callopt.Option) (r *recommend.GetAdvertRecommendResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kRecommendServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRecommendServiceClient struct {
	*kClient
}

func (p *kRecommendServiceClient) CreateAdPlan(ctx context.Context, req *recommend.CreateAdPlanRequest, callOptions ...callopt.Option) (r *recommend.CreateAdPlanResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateAdPlan(ctx, req)
}

func (p *kRecommendServiceClient) UpdateAdPlan(ctx context.Context, req *recommend.UpdateAdPlanRequest, callOptions ...callopt.Option) (r *recommend.UpdateAdPlanResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateAdPlan(ctx, req)
}

func (p *kRecommendServiceClient) GetAdPlan(ctx context.Context, req *recommend.GetAdPlanRequest, callOptions ...callopt.Option) (r *recommend.GetAdPlanResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAdPlan(ctx, req)
}

func (p *kRecommendServiceClient) ListAdPlans(ctx context.Context, req *recommend.ListAdPlansRequest, callOptions ...callopt.Option) (r *recommend.ListAdPlansResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListAdPlans(ctx, req)
}

func (p *kRecommendServiceClient) DeleteAdPlan(ctx context.Context, req *recommend.DeleteAdPlanRequest, callOptions ...callopt.Option) (r *recommend.DeleteAdPlanResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteAdPlan(ctx, req)
}

func (p *kRecommendServiceClient) CreateAdCreative(ctx context.Context, req *recommend.CreateAdCreativeRequest, callOptions ...callopt.Option) (r *recommend.CreateAdCreativeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateAdCreative(ctx, req)
}

func (p *kRecommendServiceClient) UpdateAdCreative(ctx context.Context, req *recommend.UpdateAdCreativeRequest, callOptions ...callopt.Option) (r *recommend.UpdateAdCreativeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateAdCreative(ctx, req)
}

func (p *kRecommendServiceClient) GetAdCreative(ctx context.Context, req *recommend.GetAdCreativeRequest, callOptions ...callopt.Option) (r *recommend.GetAdCreativeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAdCreative(ctx, req)
}

func (p *kRecommendServiceClient) ListAdCreatives(ctx context.Context, req *recommend.ListAdCreativesRequest, callOptions ...callopt.Option) (r *recommend.ListAdCreativesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListAdCreatives(ctx, req)
}

func (p *kRecommendServiceClient) DeleteAdCreative(ctx context.Context, req *recommend.DeleteAdCreativeRequest, callOptions ...callopt.Option) (r *recommend.DeleteAdCreativeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteAdCreative(ctx, req)
}

func (p *kRecommendServiceClient) AddUserInterest(ctx context.Context, req *recommend.AddUserInterestRequest, callOptions ...callopt.Option) (r *recommend.AddUserInterestResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddUserInterest(ctx, req)
}

func (p *kRecommendServiceClient) UpdateUserInterest(ctx context.Context, req *recommend.UpdateUserInterestRequest, callOptions ...callopt.Option) (r *recommend.UpdateUserInterestResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUserInterest(ctx, req)
}

func (p *kRecommendServiceClient) GetUserInterests(ctx context.Context, req *recommend.GetUserInterestsRequest, callOptions ...callopt.Option) (r *recommend.GetUserInterestsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserInterests(ctx, req)
}

func (p *kRecommendServiceClient) DeleteUserInterest(ctx context.Context, req *recommend.DeleteUserInterestRequest, callOptions ...callopt.Option) (r *recommend.DeleteUserInterestResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteUserInterest(ctx, req)
}

func (p *kRecommendServiceClient) CreateAdEvent(ctx context.Context, req *recommend.CreateAdEventRequest, callOptions ...callopt.Option) (r *recommend.CreateAdEventResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateAdEvent(ctx, req)
}

func (p *kRecommendServiceClient) GetUserAdEvents(ctx context.Context, req *recommend.GetUserAdEventsRequest, callOptions ...callopt.Option) (r *recommend.GetUserAdEventsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserAdEvents(ctx, req)
}

func (p *kRecommendServiceClient) GetCreativeAdEvents(ctx context.Context, req *recommend.GetCreativeAdEventsRequest, callOptions ...callopt.Option) (r *recommend.GetCreativeAdEventsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCreativeAdEvents(ctx, req)
}

func (p *kRecommendServiceClient) GetAdvertRecommend(ctx context.Context, req *recommend.GetAdvertRecommendRequest, callOptions ...callopt.Option) (r *recommend.GetAdvertRecommendResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAdvertRecommend(ctx, req)
}
