// Code generated by Kitex v0.16.1. DO NOT EDIT.

package recommendservice

import (
	"context"
	"errors"
	recommend "gitee.com/HeXiangdong/AdvertRecommend/recommend-service/kitex_gen/recommend"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateAdPlan": kitex.NewMethodInfo(
		createAdPlanHandler,
		newRecommendServiceCreateAdPlanArgs,
		newRecommendServiceCreateAdPlanResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateAdPlan": kitex.NewMethodInfo(
		updateAdPlanHandler,
		newRecommendServiceUpdateAdPlanArgs,
		newRecommendServiceUpdateAdPlanResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetAdPlan": kitex.NewMethodInfo(
		getAdPlanHandler,
		newRecommendServiceGetAdPlanArgs,
		newRecommendServiceGetAdPlanResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListAdPlans": kitex.NewMethodInfo(
		listAdPlansHandler,
		newRecommendServiceListAdPlansArgs,
		newRecommendServiceListAdPlansResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteAdPlan": kitex.NewMethodInfo(
		deleteAdPlanHandler,
		newRecommendServiceDeleteAdPlanArgs,
		newRecommendServiceDeleteAdPlanResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateAdCreative": kitex.NewMethodInfo(
		createAdCreativeHandler,
		newRecommendServiceCreateAdCreativeArgs,
		newRecommendServiceCreateAdCreativeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateAdCreative": kitex.NewMethodInfo(
		updateAdCreativeHandler,
		newRecommendServiceUpdateAdCreativeArgs,
		newRecommendServiceUpdateAdCreativeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetAdCreative": kitex.NewMethodInfo(
		getAdCreativeHandler,
		newRecommendServiceGetAdCreativeArgs,
		newRecommendServiceGetAdCreativeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListAdCreatives": kitex.NewMethodInfo(
		listAdCreativesHandler,
		newRecommendServiceListAdCreativesArgs,
		newRecommendServiceListAdCreativesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteAdCreative": kitex.NewMethodInfo(
		deleteAdCreativeHandler,
		newRecommendServiceDeleteAdCreativeArgs,
		newRecommendServiceDeleteAdCreativeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AddUserInterest": kitex.NewMethodInfo(
		addUserInterestHandler,
		newRecommendServiceAddUserInterestArgs,
		newRecommendServiceAddUserInterestResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateUserInterest": kitex.NewMethodInfo(
		updateUserInterestHandler,
		newRecommendServiceUpdateUserInterestArgs,
		newRecommendServiceUpdateUserInterestResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserInterests": kitex.NewMethodInfo(
		getUserInterestsHandler,
		newRecommendServiceGetUserInterestsArgs,
		newRecommendServiceGetUserInterestsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteUserInterest": kitex.NewMethodInfo(
		deleteUserInterestHandler,
		newRecommendServiceDeleteUserInterestArgs,
		newRecommendServiceDeleteUserInterestResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateAdEvent": kitex.NewMethodInfo(
		createAdEventHandler,
		newRecommendServiceCreateAdEventArgs,
		newRecommendServiceCreateAdEventResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserAdEvents": kitex.NewMethodInfo(
		getUserAdEventsHandler,
		newRecommendServiceGetUserAdEventsArgs,
		newRecommendServiceGetUserAdEventsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetCreativeAdEvents": kitex.NewMethodInfo(
		getCreativeAdEventsHandler,
		newRecommendServiceGetCreativeAdEventsArgs,
		newRecommendServiceGetCreativeAdEventsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetAdvertRecommend": kitex.NewMethodInfo(
		getAdvertRecommendHandler,
		newRecommendServiceGetAdvertRecommendArgs,
		newRecommendServiceGetAdvertRecommendResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	recommendServiceServiceInfo                = NewServiceInfo()
	recommendServiceServiceInfoForClient       = NewServiceInfoForClient()
	recommendServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return recommendServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return recommendServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return recommendServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "RecommendService"
	handlerType := (*recommend.RecommendService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "recommend",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func createAdPlanHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceCreateAdPlanArgs)
	realResult := result.(*recommend.RecommendServiceCreateAdPlanResult)
	success, err := handler.(recommend.RecommendService).CreateAdPlan(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceCreateAdPlanArgs() interface{} {
	return recommend.NewRecommendServiceCreateAdPlanArgs()
}

func newRecommendServiceCreateAdPlanResult() interface{} {
	return recommend.NewRecommendServiceCreateAdPlanResult()
}

func updateAdPlanHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceUpdateAdPlanArgs)
	realResult := result.(*recommend.RecommendServiceUpdateAdPlanResult)
	success, err := handler.(recommend.RecommendService).UpdateAdPlan(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceUpdateAdPlanArgs() interface{} {
	return recommend.NewRecommendServiceUpdateAdPlanArgs()
}

func newRecommendServiceUpdateAdPlanResult() interface{} {
	return recommend.NewRecommendServiceUpdateAdPlanResult()
}

func getAdPlanHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceGetAdPlanArgs)
	realResult := result.(*recommend.RecommendServiceGetAdPlanResult)
	success, err := handler.(recommend.RecommendService).GetAdPlan(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceGetAdPlanArgs() interface{} {
	return recommend.NewRecommendServiceGetAdPlanArgs()
}

func newRecommendServiceGetAdPlanResult() interface{} {
	return recommend.NewRecommendServiceGetAdPlanResult()
}

func listAdPlansHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceListAdPlansArgs)
	realResult := result.(*recommend.RecommendServiceListAdPlansResult)
	success, err := handler.(recommend.RecommendService).ListAdPlans(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceListAdPlansArgs() interface{} {
	return recommend.NewRecommendServiceListAdPlansArgs()
}

func newRecommendServiceListAdPlansResult() interface{} {
	return recommend.NewRecommendServiceListAdPlansResult()
}

func deleteAdPlanHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceDeleteAdPlanArgs)
	realResult := result.(*recommend.RecommendServiceDeleteAdPlanResult)
	success, err := handler.(recommend.RecommendService).DeleteAdPlan(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceDeleteAdPlanArgs() interface{} {
	return recommend.NewRecommendServiceDeleteAdPlanArgs()
}

func newRecommendServiceDeleteAdPlanResult() interface{} {
	return recommend.NewRecommendServiceDeleteAdPlanResult()
}

func createAdCreativeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceCreateAdCreativeArgs)
	realResult := result.(*recommend.RecommendServiceCreateAdCreativeResult)
	success, err := handler.(recommend.RecommendService).CreateAdCreative(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceCreateAdCreativeArgs() interface{} {
	return recommend.NewRecommendServiceCreateAdCreativeArgs()
}

func newRecommendServiceCreateAdCreativeResult() interface{} {
	return recommend.NewRecommendServiceCreateAdCreativeResult()
}

func updateAdCreativeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceUpdateAdCreativeArgs)
	realResult := result.(*recommend.RecommendServiceUpdateAdCreativeResult)
	success, err := handler.(recommend.RecommendService).UpdateAdCreative(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceUpdateAdCreativeArgs() interface{} {
	return recommend.NewRecommendServiceUpdateAdCreativeArgs()
}

func newRecommendServiceUpdateAdCreativeResult() interface{} {
	return recommend.NewRecommendServiceUpdateAdCreativeResult()
}

func getAdCreativeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceGetAdCreativeArgs)
	realResult := result.(*recommend.RecommendServiceGetAdCreativeResult)
	success, err := handler.(recommend.RecommendService).GetAdCreative(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceGetAdCreativeArgs() interface{} {
	return recommend.NewRecommendServiceGetAdCreativeArgs()
}

func newRecommendServiceGetAdCreativeResult() interface{} {
	return recommend.NewRecommendServiceGetAdCreativeResult()
}

func listAdCreativesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceListAdCreativesArgs)
	realResult := result.(*recommend.RecommendServiceListAdCreativesResult)
	success, err := handler.(recommend.RecommendService).ListAdCreatives(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceListAdCreativesArgs() interface{} {
	return recommend.NewRecommendServiceListAdCreativesArgs()
}

func newRecommendServiceListAdCreativesResult() interface{} {
	return recommend.NewRecommendServiceListAdCreativesResult()
}

func deleteAdCreativeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceDeleteAdCreativeArgs)
	realResult := result.(*recommend.RecommendServiceDeleteAdCreativeResult)
	success, err := handler.(recommend.RecommendService).DeleteAdCreative(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceDeleteAdCreativeArgs() interface{} {
	return recommend.NewRecommendServiceDeleteAdCreativeArgs()
}

func newRecommendServiceDeleteAdCreativeResult() interface{} {
	return recommend.NewRecommendServiceDeleteAdCreativeResult()
}

func addUserInterestHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceAddUserInterestArgs)
	realResult := result.(*recommend.RecommendServiceAddUserInterestResult)
	success, err := handler.(recommend.RecommendService).AddUserInterest(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceAddUserInterestArgs() interface{} {
	return recommend.NewRecommendServiceAddUserInterestArgs()
}

func newRecommendServiceAddUserInterestResult() interface{} {
	return recommend.NewRecommendServiceAddUserInterestResult()
}

func updateUserInterestHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceUpdateUserInterestArgs)
	realResult := result.(*recommend.RecommendServiceUpdateUserInterestResult)
	success, err := handler.(recommend.RecommendService).UpdateUserInterest(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceUpdateUserInterestArgs() interface{} {
	return recommend.NewRecommendServiceUpdateUserInterestArgs()
}

func newRecommendServiceUpdateUserInterestResult() interface{} {
	return recommend.NewRecommendServiceUpdateUserInterestResult()
}

func getUserInterestsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceGetUserInterestsArgs)
	realResult := result.(*recommend.RecommendServiceGetUserInterestsResult)
	success, err := handler.(recommend.RecommendService).GetUserInterests(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceGetUserInterestsArgs() interface{} {
	return recommend.NewRecommendServiceGetUserInterestsArgs()
}

func newRecommendServiceGetUserInterestsResult() interface{} {
	return recommend.NewRecommendServiceGetUserInterestsResult()
}

func deleteUserInterestHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceDeleteUserInterestArgs)
	realResult := result.(*recommend.RecommendServiceDeleteUserInterestResult)
	success, err := handler.(recommend.RecommendService).DeleteUserInterest(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceDeleteUserInterestArgs() interface{} {
	return recommend.NewRecommendServiceDeleteUserInterestArgs()
}

func newRecommendServiceDeleteUserInterestResult() interface{} {
	return recommend.NewRecommendServiceDeleteUserInterestResult()
}

func createAdEventHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceCreateAdEventArgs)
	realResult := result.(*recommend.RecommendServiceCreateAdEventResult)
	success, err := handler.(recommend.RecommendService).CreateAdEvent(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceCreateAdEventArgs() interface{} {
	return recommend.NewRecommendServiceCreateAdEventArgs()
}

func newRecommendServiceCreateAdEventResult() interface{} {
	return recommend.NewRecommendServiceCreateAdEventResult()
}

func getUserAdEventsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceGetUserAdEventsArgs)
	realResult := result.(*recommend.RecommendServiceGetUserAdEventsResult)
	success, err := handler.(recommend.RecommendService).GetUserAdEvents(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceGetUserAdEventsArgs() interface{} {
	return recommend.NewRecommendServiceGetUserAdEventsArgs()
}

func newRecommendServiceGetUserAdEventsResult() interface{} {
	return recommend.NewRecommendServiceGetUserAdEventsResult()
}

func getCreativeAdEventsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceGetCreativeAdEventsArgs)
	realResult := result.(*recommend.RecommendServiceGetCreativeAdEventsResult)
	success, err := handler.(recommend.RecommendService).GetCreativeAdEvents(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceGetCreativeAdEventsArgs() interface{} {
	return recommend.NewRecommendServiceGetCreativeAdEventsArgs()
}

func newRecommendServiceGetCreativeAdEventsResult() interface{} {
	return recommend.NewRecommendServiceGetCreativeAdEventsResult()
}

func getAdvertRecommendHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*recommend.RecommendServiceGetAdvertRecommendArgs)
	realResult := result.(*recommend.RecommendServiceGetAdvertRecommendResult)
	success, err := handler.(recommend.RecommendService).GetAdvertRecommend(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newRecommendServiceGetAdvertRecommendArgs() interface{} {
	return recommend.NewRecommendServiceGetAdvertRecommendArgs()
}

func newRecommendServiceGetAdvertRecommendResult() interface{} {
	return recommend.NewRecommendServiceGetAdvertRecommendResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateAdPlan(ctx context.Context, req *recommend.CreateAdPlanRequest) (r *recommend.CreateAdPlanResponse, err error) {
	var _args recommend.RecommendServiceCreateAdPlanArgs
	_args.Req = req
	var _result recommend.RecommendServiceCreateAdPlanResult
	if err = p.c.Call(ctx, "CreateAdPlan", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateAdPlan(ctx context.Context, req *recommend.UpdateAdPlanRequest) (r *recommend.UpdateAdPlanResponse, err error) {
	var _args recommend.RecommendServiceUpdateAdPlanArgs
	_args.Req = req
	var _result recommend.RecommendServiceUpdateAdPlanResult
	if err = p.c.Call(ctx, "UpdateAdPlan", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAdPlan(ctx context.Context, req *recommend.GetAdPlanRequest) (r *recommend.GetAdPlanResponse, err error) {
	var _args recommend.RecommendServiceGetAdPlanArgs
	_args.Req = req
	var _result recommend.RecommendServiceGetAdPlanResult
	if err = p.c.Call(ctx, "GetAdPlan", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListAdPlans(ctx context.Context, req *recommend.ListAdPlansRequest) (r *recommend.ListAdPlansResponse, err error) {
	var _args recommend.RecommendServiceListAdPlansArgs
	_args.Req = req
	var _result recommend.RecommendServiceListAdPlansResult
	if err = p.c.Call(ctx, "ListAdPlans", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteAdPlan(ctx context.Context, req *recommend.DeleteAdPlanRequest) (r *recommend.DeleteAdPlanResponse, err error) {
	var _args recommend.RecommendServiceDeleteAdPlanArgs
	_args.Req = req
	var _result recommend.RecommendServiceDeleteAdPlanResult
	if err = p.c.Call(ctx, "DeleteAdPlan", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateAdCreative(ctx context.Context, req *recommend.CreateAdCreativeRequest) (r *recommend.CreateAdCreativeResponse, err error) {
	var _args recommend.RecommendServiceCreateAdCreativeArgs
	_args.Req = req
	var _result recommend.RecommendServiceCreateAdCreativeResult
	if err = p.c.Call(ctx, "CreateAdCreative", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateAdCreative(ctx context.Context, req *recommend.UpdateAdCreativeRequest) (r *recommend.UpdateAdCreativeResponse, err error) {
	var _args recommend.RecommendServiceUpdateAdCreativeArgs
	_args.Req = req
	var _result recommend.RecommendServiceUpdateAdCreativeResult
	if err = p.c.Call(ctx, "UpdateAdCreative", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAdCreative(ctx context.Context, req *recommend.GetAdCreativeRequest) (r *recommend.GetAdCreativeResponse, err error) {
	var _args recommend.RecommendServiceGetAdCreativeArgs
	_args.Req = req
	var _result recommend.RecommendServiceGetAdCreativeResult
	if err = p.c.Call(ctx, "GetAdCreative", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListAdCreatives(ctx context.Context, req *recommend.ListAdCreativesRequest) (r *recommend.ListAdCreativesResponse, err error) {
	var _args recommend.RecommendServiceListAdCreativesArgs
	_args.Req = req
	var _result recommend.RecommendServiceListAdCreativesResult
	if err = p.c.Call(ctx, "ListAdCreatives", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteAdCreative(ctx context.Context, req *recommend.DeleteAdCreativeRequest) (r *recommend.DeleteAdCreativeResponse, err error) {
	var _args recommend.RecommendServiceDeleteAdCreativeArgs
	_args.Req = req
	var _result recommend.RecommendServiceDeleteAdCreativeResult
	if err = p.c.Call(ctx, "DeleteAdCreative", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddUserInterest(ctx context.Context, req *recommend.AddUserInterestRequest) (r *recommend.AddUserInterestResponse, err error) {
	var _args recommend.RecommendServiceAddUserInterestArgs
	_args.Req = req
	var _result recommend.RecommendServiceAddUserInterestResult
	if err = p.c.Call(ctx, "AddUserInterest", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateUserInterest(ctx context.Context, req *recommend.UpdateUserInterestRequest) (r *recommend.UpdateUserInterestResponse, err error) {
	var _args recommend.RecommendServiceUpdateUserInterestArgs
	_args.Req = req
	var _result recommend.RecommendServiceUpdateUserInterestResult
	if err = p.c.Call(ctx, "UpdateUserInterest", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserInterests(ctx context.Context, req *recommend.GetUserInterestsRequest) (r *recommend.GetUserInterestsResponse, err error) {
	var _args recommend.RecommendServiceGetUserInterestsArgs
	_args.Req = req
	var _result recommend.RecommendServiceGetUserInterestsResult
	if err = p.c.Call(ctx, "GetUserInterests", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteUserInterest(ctx context.Context, req *recommend.DeleteUserInterestRequest) (r *recommend.DeleteUserInterestResponse, err error) {
	var _args recommend.RecommendServiceDeleteUserInterestArgs
	_args.Req = req
	var _result recommend.RecommendServiceDeleteUserInterestResult
	if err = p.c.Call(ctx, "DeleteUserInterest", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateAdEvent(ctx context.Context, req *recommend.CreateAdEventRequest) (r *recommend.CreateAdEventResponse, err error) {
	var _args recommend.RecommendServiceCreateAdEventArgs
	_args.Req = req
	var _result recommend.RecommendServiceCreateAdEventResult
	if err = p.c.Call(ctx, "CreateAdEvent", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserAdEvents(ctx context.Context, req *recommend.GetUserAdEventsRequest) (r *recommend.GetUserAdEventsResponse, err error) {
	var _args recommend.RecommendServiceGetUserAdEventsArgs
	_args.Req = req
	var _result recommend.RecommendServiceGetUserAdEventsResult
	if err = p.c.Call(ctx, "GetUserAdEvents", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCreativeAdEvents(ctx context.Context, req *recommend.GetCreativeAdEventsRequest) (r *recommend.GetCreativeAdEventsResponse, err error) {
	var _args recommend.RecommendServiceGetCreativeAdEventsArgs
	_args.Req = req
	var _result recommend.RecommendServiceGetCreativeAdEventsResult
	if err = p.c.Call(ctx, "GetCreativeAdEvents", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAdvertRecommend(ctx context.Context, req *recommend.GetAdvertRecommendRequest) (r *recommend.GetAdvertRecommendResponse, err error) {
	var _args recommend.RecommendServiceGetAdvertRecommendArgs
	_args.Req = req
	var _result recommend.RecommendServiceGetAdvertRecommendResult
	if err = p.c.Call(ctx, "GetAdvertRecommend", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
