// Code generated by Kitex. DO NOT EDIT.

package advert

type AdCreative struct {
	CreativeId   int64  `thrift:"creativeId,1" json:"creativeId"`
	PlanId       int64  `thrift:"planId,2" json:"planId"`
	CreativeType int32  `thrift:"creativeType,3" json:"creativeType"`
	MediaUrl     string `thrift:"mediaUrl,4" json:"mediaUrl"`
	Title        string `thrift:"title,5" json:"title"`
	Description  string `thrift:"description,6" json:"description"`
	Status       int32  `thrift:"status,7" json:"status"`
	CreateTime   string `thrift:"createTime,8" json:"createTime"`
	UpdateTime   string `thrift:"updateTime,9" json:"updateTime"`
}

type CreateAdCreativeRequest struct {
	PlanId       int64  `thrift:"planId,1" json:"planId"`
	CreativeType int32  `thrift:"creativeType,2" json:"creativeType"`
	MediaUrl     string `thrift:"mediaUrl,3" json:"mediaUrl"`
	Title        string `thrift:"title,4" json:"title"`
	Description  string `thrift:"description,5" json:"description"`
}

type CreateAdCreativeResponse struct {
	BaseResp   *BaseResponse `thrift:"baseResp,1" json:"baseResp"`
	CreativeId int64         `thrift:"creativeId,2" json:"creativeId"`
}

type UpdateAdCreativeRequest struct {
	CreativeId   int64   `thrift:"creativeId,1" json:"creativeId"`
	PlanId       *int64  `thrift:"planId,2,optional" json:"planId,omitempty"`
	CreativeType *int32  `thrift:"creativeType,3,optional" json:"creativeType,omitempty"`
	MediaUrl     *string `thrift:"mediaUrl,4,optional" json:"mediaUrl,omitempty"`
	Title        *string `thrift:"title,5,optional" json:"title,omitempty"`
	Description  *string `thrift:"description,6,optional" json:"description,omitempty"`
	Status       *int32  `thrift:"status,7,optional" json:"status,omitempty"`
}

type UpdateAdCreativeResponse struct {
	BaseResp *BaseResponse `thrift:"baseResp,1" json:"baseResp"`
}

type GetAdCreativeRequest struct {
	CreativeId int64 `thrift:"creativeId,1" json:"creativeId"`
}

type GetAdCreativeResponse struct {
	BaseResp   *BaseResponse `thrift:"baseResp,1" json:"baseResp"`
	AdCreative *AdCreative   `thrift:"adCreative,2" json:"adCreative"`
}

type ListAdCreativesRequest struct {
	Page     int32  `thrift:"page,1" json:"page"`
	PageSize int32  `thrift:"pageSize,2" json:"pageSize"`
	PlanId   *int64 `thrift:"planId,3,optional" json:"planId,omitempty"`
}

type ListAdCreativesResponse struct {
	BaseResp    *BaseResponse `thrift:"baseResp,1" json:"baseResp"`
	AdCreatives []*AdCreative `thrift:"adCreatives,2" json:"adCreatives"`
	Total       int64         `thrift:"total,3" json:"total"`
}

type DeleteAdCreativeRequest struct {
	CreativeId int64 `thrift:"creativeId,1" json:"creativeId"`
}

type DeleteAdCreativeResponse struct {
	BaseResp *BaseResponse `thrift:"baseResp,1" json:"baseResp"`
}
