// Code generated by Kitex. DO NOT EDIT.

package advert

// BaseResponse 基础响应
type BaseResponse struct {
	Code    int32  `thrift:"code,1" json:"code"`
	Message string `thrift:"message,2" json:"message"`
}

// AdPlan 广告计划
type AdPlan struct {
	PlanId        int64   `thrift:"planId,1" json:"planId"`
	Name          string  `thrift:"name,2" json:"name"`
	Objective     string  `thrift:"objective,3" json:"objective"`
	Budget        float64 `thrift:"budget,4" json:"budget"`
	BidPrice      string  `thrift:"bidPrice,5" json:"bidPrice"`
	TargetingRule string  `thrift:"targetingRule,6" json:"targetingRule"`
	StartTime     string  `thrift:"startTime,7" json:"startTime"`
	EndTime       string  `thrift:"endTime,8" json:"endTime"`
	Status        int32   `thrift:"status,9" json:"status"`
	CreateTime    string  `thrift:"createTime,10" json:"createTime"`
	UpdateTime    string  `thrift:"updateTime,11" json:"updateTime"`
}

type CreateAdPlanRequest struct {
	Name          string  `thrift:"name,1" json:"name"`
	Objective     string  `thrift:"objective,2" json:"objective"`
	Budget        float64 `thrift:"budget,3" json:"budget"`
	BidPrice      string  `thrift:"bidPrice,4" json:"bidPrice"`
	TargetingRule string  `thrift:"targetingRule,5" json:"targetingRule"`
	StartTime     string  `thrift:"startTime,6" json:"startTime"`
	EndTime       string  `thrift:"endTime,7" json:"endTime"`
}

type CreateAdPlanResponse struct {
	BaseResp *BaseResponse `thrift:"baseResp,1" json:"baseResp"`
	PlanId   int64         `thrift:"planId,2" json:"planId"`
}

type UpdateAdPlanRequest struct {
	PlanId        int64    `thrift:"planId,1" json:"planId"`
	Name          *string  `thrift:"name,2,optional" json:"name,omitempty"`
	Objective     *string  `thrift:"objective,3,optional" json:"objective,omitempty"`
	Budget        *float64 `thrift:"budget,4,optional" json:"budget,omitempty"`
	BidPrice      *string  `thrift:"bidPrice,5,optional" json:"bidPrice,omitempty"`
	TargetingRule *string  `thrift:"targetingRule,6,optional" json:"targetingRule,omitempty"`
	StartTime     *string  `thrift:"startTime,7,optional" json:"startTime,omitempty"`
	EndTime       *string  `thrift:"endTime,8,optional" json:"endTime,omitempty"`
	Status        *int32   `thrift:"status,9,optional" json:"status,omitempty"`
}

type UpdateAdPlanResponse struct {
	BaseResp *BaseResponse `thrift:"baseResp,1" json:"baseResp"`
}

type GetAdPlanRequest struct {
	PlanId int64 `thrift:"planId,1" json:"planId"`
}

type GetAdPlanResponse struct {
	BaseResp *BaseResponse `thrift:"baseResp,1" json:"baseResp"`
	AdPlan   *AdPlan       `thrift:"adPlan,2" json:"adPlan"`
}

type ListAdPlansRequest struct {
	Page     int32  `thrift:"page,1" json:"page"`
	PageSize int32  `thrift:"pageSize,2" json:"pageSize"`
	Status   *int32 `thrift:"status,3,optional" json:"status,omitempty"`
}

type ListAdPlansResponse struct {
	BaseResp *BaseResponse `thrift:"baseResp,1" json:"baseResp"`
	AdPlans  []*AdPlan     `thrift:"adPlans,2" json:"adPlans"`
	Total    int64         `thrift:"total,3" json:"total"`
}

type DeleteAdPlanRequest struct {
	PlanId int64 `thrift:"planId,1" json:"planId"`
}

type DeleteAdPlanResponse struct {
	BaseResp *BaseResponse `thrift:"baseResp,1" json:"baseResp"`
}
