// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package advert

import (
	"fmt"
)

type GetAdvertRecommendRequest struct {
	UserId int64 `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
}

func NewGetAdvertRecommendRequest() *GetAdvertRecommendRequest {
	return &GetAdvertRecommendRequest{}
}

func (p *GetAdvertRecommendRequest) InitDefault() {
}

func (p *GetAdvertRecommendRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetAdvertRecommendRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetAdvertRecommendRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertRecommendRequest(%+v)", *p)
}

var fieldIDToName_AdvertRecommendRequest = map[int16]string{
	1: "userId",
}

type GetAdvertRecommendResponse struct {
	BaseResp *BaseResponse `thrift:"baseResp,1" frugal:"1,default,BaseResponse" json:"baseResp"`
	Adverts  []*AdCreative `thrift:"adverts,2" frugal:"2,default,list<AdCreative>" json:"adverts"`
	Total    int64         `thrift:"total,3" frugal:"3,default,i64" json:"total"`
}

func NewGetAdvertRecommendResponse() *GetAdvertRecommendResponse {
	return &GetAdvertRecommendResponse{}
}

func (p *GetAdvertRecommendResponse) InitDefault() {
}

var AdvertRecommendResponse_BaseResp_DEFAULT *BaseResponse

func (p *GetAdvertRecommendResponse) GetBaseResp() (v *BaseResponse) {
	if !p.IsSetBaseResp() {
		return AdvertRecommendResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *GetAdvertRecommendResponse) GetAdverts() (v []*AdCreative) {
	return p.Adverts
}

func (p *GetAdvertRecommendResponse) GetTotal() (v int64) {
	return p.Total
}
func (p *GetAdvertRecommendResponse) SetBaseResp(val *BaseResponse) {
	p.BaseResp = val
}
func (p *GetAdvertRecommendResponse) SetAdverts(val []*AdCreative) {
	p.Adverts = val
}
func (p *GetAdvertRecommendResponse) SetTotal(val int64) {
	p.Total = val
}

func (p *GetAdvertRecommendResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetAdvertRecommendResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertRecommendResponse(%+v)", *p)
}

var fieldIDToName_AdvertRecommendResponse = map[int16]string{
	1: "baseResp",
	2: "adverts",
	3: "total",
}
