// Code generated by Kitex. DO NOT EDIT.

package advert

import (
	"context"
	"fmt"
)

// AdvertService 服务接口
type AdvertService interface {
	CreateAdPlan(ctx context.Context, req *CreateAdPlanRequest) (*CreateAdPlanResponse, error)
	UpdateAdPlan(ctx context.Context, req *UpdateAdPlanRequest) (*UpdateAdPlanResponse, error)
	GetAdPlan(ctx context.Context, req *GetAdPlanRequest) (*GetAdPlanResponse, error)
	ListAdPlans(ctx context.Context, req *ListAdPlansRequest) (*ListAdPlansResponse, error)
	DeleteAdPlan(ctx context.Context, req *DeleteAdPlanRequest) (*DeleteAdPlanResponse, error)

	CreateAdCreative(ctx context.Context, req *CreateAdCreativeRequest) (*CreateAdCreativeResponse, error)
	UpdateAdCreative(ctx context.Context, req *UpdateAdCreativeRequest) (*UpdateAdCreativeResponse, error)
	GetAdCreative(ctx context.Context, req *GetAdCreativeRequest) (*GetAdCreativeResponse, error)
	ListAdCreatives(ctx context.Context, req *ListAdCreativesRequest) (*ListAdCreativesResponse, error)
	DeleteAdCreative(ctx context.Context, req *DeleteAdCreativeRequest) (*DeleteAdCreativeResponse, error)

	CreateUserProfile(ctx context.Context, req *CreateUserProfileRequest) (*CreateUserProfileResponse, error)
	UpdateUserProfile(ctx context.Context, req *UpdateUserProfileRequest) (*UpdateUserProfileResponse, error)
	GetUserProfile(ctx context.Context, req *GetUserProfileRequest) (*GetUserProfileResponse, error)
	DeleteUserProfile(ctx context.Context, req *DeleteUserProfileRequest) (*DeleteUserProfileResponse, error)

	AddUserInterest(ctx context.Context, req *AddUserInterestRequest) (*AddUserInterestResponse, error)
	UpdateUserInterest(ctx context.Context, req *UpdateUserInterestRequest) (*UpdateUserInterestResponse, error)
	GetUserInterests(ctx context.Context, req *GetUserInterestsRequest) (*GetUserInterestsResponse, error)
	DeleteUserInterest(ctx context.Context, req *DeleteUserInterestRequest) (*DeleteUserInterestResponse, error)

	CreateAdEvent(ctx context.Context, req *CreateAdEventRequest) (*CreateAdEventResponse, error)
	GetUserAdEvents(ctx context.Context, req *GetUserAdEventsRequest) (*GetUserAdEventsResponse, error)
	GetCreativeAdEvents(ctx context.Context, req *GetCreativeAdEventsRequest) (*GetCreativeAdEventsResponse, error)
}

type AdvertServiceCreateAdPlanArgs struct {
	Req *CreateAdPlanRequest `thrift:"req,1" frugal:"1,default,CreateAdPlanRequest" json:"req"`
}

func NewAdvertServiceCreateAdPlanArgs() *AdvertServiceCreateAdPlanArgs {
	return &AdvertServiceCreateAdPlanArgs{}
}

func (p *AdvertServiceCreateAdPlanArgs) InitDefault() {
}

var AdvertServiceCreateAdPlanArgs_Req_DEFAULT *CreateAdPlanRequest

func (p *AdvertServiceCreateAdPlanArgs) GetReq() (v *CreateAdPlanRequest) {
	if !p.IsSetReq() {
		return AdvertServiceCreateAdPlanArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdvertServiceCreateAdPlanArgs) SetReq(val *CreateAdPlanRequest) {
	p.Req = val
}

func (p *AdvertServiceCreateAdPlanArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdvertServiceCreateAdPlanArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceCreateAdPlanArgs(%+v)", *p)
}

var fieldIDToName_AdvertServiceCreateAdPlanArgs = map[int16]string{
	1: "req",
}

type AdvertServiceCreateAdPlanResult struct {
	Success *CreateAdPlanResponse `thrift:"success,0,optional" frugal:"0,optional,CreateAdPlanResponse" json:"success,omitempty"`
}

func NewAdvertServiceCreateAdPlanResult() *AdvertServiceCreateAdPlanResult {
	return &AdvertServiceCreateAdPlanResult{}
}

func (p *AdvertServiceCreateAdPlanResult) InitDefault() {
}

var AdvertServiceCreateAdPlanResult_Success_DEFAULT *CreateAdPlanResponse

func (p *AdvertServiceCreateAdPlanResult) GetSuccess() (v *CreateAdPlanResponse) {
	if !p.IsSetSuccess() {
		return AdvertServiceCreateAdPlanResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdvertServiceCreateAdPlanResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateAdPlanResponse)
}

func (p *AdvertServiceCreateAdPlanResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdvertServiceCreateAdPlanResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceCreateAdPlanResult(%+v)", *p)
}

var fieldIDToName_AdvertServiceCreateAdPlanResult = map[int16]string{
	0: "success",
}

type AdvertServiceUpdateAdPlanArgs struct {
	Req *UpdateAdPlanRequest `thrift:"req,1" frugal:"1,default,UpdateAdPlanRequest" json:"req"`
}

func NewAdvertServiceUpdateAdPlanArgs() *AdvertServiceUpdateAdPlanArgs {
	return &AdvertServiceUpdateAdPlanArgs{}
}

func (p *AdvertServiceUpdateAdPlanArgs) InitDefault() {
}

var AdvertServiceUpdateAdPlanArgs_Req_DEFAULT *UpdateAdPlanRequest

func (p *AdvertServiceUpdateAdPlanArgs) GetReq() (v *UpdateAdPlanRequest) {
	if !p.IsSetReq() {
		return AdvertServiceUpdateAdPlanArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdvertServiceUpdateAdPlanArgs) SetReq(val *UpdateAdPlanRequest) {
	p.Req = val
}

func (p *AdvertServiceUpdateAdPlanArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdvertServiceUpdateAdPlanArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceUpdateAdPlanArgs(%+v)", *p)
}

var fieldIDToName_AdvertServiceUpdateAdPlanArgs = map[int16]string{
	1: "req",
}

type AdvertServiceUpdateAdPlanResult struct {
	Success *UpdateAdPlanResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateAdPlanResponse" json:"success,omitempty"`
}

func NewAdvertServiceUpdateAdPlanResult() *AdvertServiceUpdateAdPlanResult {
	return &AdvertServiceUpdateAdPlanResult{}
}

func (p *AdvertServiceUpdateAdPlanResult) InitDefault() {
}

var AdvertServiceUpdateAdPlanResult_Success_DEFAULT *UpdateAdPlanResponse

func (p *AdvertServiceUpdateAdPlanResult) GetSuccess() (v *UpdateAdPlanResponse) {
	if !p.IsSetSuccess() {
		return AdvertServiceUpdateAdPlanResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdvertServiceUpdateAdPlanResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateAdPlanResponse)
}

func (p *AdvertServiceUpdateAdPlanResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdvertServiceUpdateAdPlanResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceUpdateAdPlanResult(%+v)", *p)
}

var fieldIDToName_AdvertServiceUpdateAdPlanResult = map[int16]string{
	0: "success",
}

type AdvertServiceGetAdPlanArgs struct {
	Req *GetAdPlanRequest `thrift:"req,1" frugal:"1,default,GetAdPlanRequest" json:"req"`
}

func NewAdvertServiceGetAdPlanArgs() *AdvertServiceGetAdPlanArgs {
	return &AdvertServiceGetAdPlanArgs{}
}

func (p *AdvertServiceGetAdPlanArgs) InitDefault() {
}

var AdvertServiceGetAdPlanArgs_Req_DEFAULT *GetAdPlanRequest

func (p *AdvertServiceGetAdPlanArgs) GetReq() (v *GetAdPlanRequest) {
	if !p.IsSetReq() {
		return AdvertServiceGetAdPlanArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdvertServiceGetAdPlanArgs) SetReq(val *GetAdPlanRequest) {
	p.Req = val
}

func (p *AdvertServiceGetAdPlanArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdvertServiceGetAdPlanArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceGetAdPlanArgs(%+v)", *p)
}

var fieldIDToName_AdvertServiceGetAdPlanArgs = map[int16]string{
	1: "req",
}

type AdvertServiceGetAdPlanResult struct {
	Success *GetAdPlanResponse `thrift:"success,0,optional" frugal:"0,optional,GetAdPlanResponse" json:"success,omitempty"`
}

func NewAdvertServiceGetAdPlanResult() *AdvertServiceGetAdPlanResult {
	return &AdvertServiceGetAdPlanResult{}
}

func (p *AdvertServiceGetAdPlanResult) InitDefault() {
}

var AdvertServiceGetAdPlanResult_Success_DEFAULT *GetAdPlanResponse

func (p *AdvertServiceGetAdPlanResult) GetSuccess() (v *GetAdPlanResponse) {
	if !p.IsSetSuccess() {
		return AdvertServiceGetAdPlanResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdvertServiceGetAdPlanResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetAdPlanResponse)
}

func (p *AdvertServiceGetAdPlanResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdvertServiceGetAdPlanResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceGetAdPlanResult(%+v)", *p)
}

var fieldIDToName_AdvertServiceGetAdPlanResult = map[int16]string{
	0: "success",
}

type AdvertServiceListAdPlansArgs struct {
	Req *ListAdPlansRequest `thrift:"req,1" frugal:"1,default,ListAdPlansRequest" json:"req"`
}

func NewAdvertServiceListAdPlansArgs() *AdvertServiceListAdPlansArgs {
	return &AdvertServiceListAdPlansArgs{}
}

func (p *AdvertServiceListAdPlansArgs) InitDefault() {
}

var AdvertServiceListAdPlansArgs_Req_DEFAULT *ListAdPlansRequest

func (p *AdvertServiceListAdPlansArgs) GetReq() (v *ListAdPlansRequest) {
	if !p.IsSetReq() {
		return AdvertServiceListAdPlansArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdvertServiceListAdPlansArgs) SetReq(val *ListAdPlansRequest) {
	p.Req = val
}

func (p *AdvertServiceListAdPlansArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdvertServiceListAdPlansArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceListAdPlansArgs(%+v)", *p)
}

var fieldIDToName_AdvertServiceListAdPlansArgs = map[int16]string{
	1: "req",
}

type AdvertServiceListAdPlansResult struct {
	Success *ListAdPlansResponse `thrift:"success,0,optional" frugal:"0,optional,ListAdPlansResponse" json:"success,omitempty"`
}

func NewAdvertServiceListAdPlansResult() *AdvertServiceListAdPlansResult {
	return &AdvertServiceListAdPlansResult{}
}

func (p *AdvertServiceListAdPlansResult) InitDefault() {
}

var AdvertServiceListAdPlansResult_Success_DEFAULT *ListAdPlansResponse

func (p *AdvertServiceListAdPlansResult) GetSuccess() (v *ListAdPlansResponse) {
	if !p.IsSetSuccess() {
		return AdvertServiceListAdPlansResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdvertServiceListAdPlansResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListAdPlansResponse)
}

func (p *AdvertServiceListAdPlansResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdvertServiceListAdPlansResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceListAdPlansResult(%+v)", *p)
}

var fieldIDToName_AdvertServiceListAdPlansResult = map[int16]string{
	0: "success",
}

type AdvertServiceDeleteAdPlanArgs struct {
	Req *DeleteAdPlanRequest `thrift:"req,1" frugal:"1,default,DeleteAdPlanRequest" json:"req"`
}

func NewAdvertServiceDeleteAdPlanArgs() *AdvertServiceDeleteAdPlanArgs {
	return &AdvertServiceDeleteAdPlanArgs{}
}

func (p *AdvertServiceDeleteAdPlanArgs) InitDefault() {
}

var AdvertServiceDeleteAdPlanArgs_Req_DEFAULT *DeleteAdPlanRequest

func (p *AdvertServiceDeleteAdPlanArgs) GetReq() (v *DeleteAdPlanRequest) {
	if !p.IsSetReq() {
		return AdvertServiceDeleteAdPlanArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdvertServiceDeleteAdPlanArgs) SetReq(val *DeleteAdPlanRequest) {
	p.Req = val
}

func (p *AdvertServiceDeleteAdPlanArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdvertServiceDeleteAdPlanArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceDeleteAdPlanArgs(%+v)", *p)
}

var fieldIDToName_AdvertServiceDeleteAdPlanArgs = map[int16]string{
	1: "req",
}

type AdvertServiceDeleteAdPlanResult struct {
	Success *DeleteAdPlanResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteAdPlanResponse" json:"success,omitempty"`
}

func NewAdvertServiceDeleteAdPlanResult() *AdvertServiceDeleteAdPlanResult {
	return &AdvertServiceDeleteAdPlanResult{}
}

func (p *AdvertServiceDeleteAdPlanResult) InitDefault() {
}

var AdvertServiceDeleteAdPlanResult_Success_DEFAULT *DeleteAdPlanResponse

func (p *AdvertServiceDeleteAdPlanResult) GetSuccess() (v *DeleteAdPlanResponse) {
	if !p.IsSetSuccess() {
		return AdvertServiceDeleteAdPlanResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdvertServiceDeleteAdPlanResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteAdPlanResponse)
}

func (p *AdvertServiceDeleteAdPlanResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdvertServiceDeleteAdPlanResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceDeleteAdPlanResult(%+v)", *p)
}

var fieldIDToName_AdvertServiceDeleteAdPlanResult = map[int16]string{
	0: "success",
}

type AdvertServiceCreateAdCreativeArgs struct {
	Req *CreateAdCreativeRequest `thrift:"req,1" frugal:"1,default,CreateAdCreativeRequest" json:"req"`
}

func NewAdvertServiceCreateAdCreativeArgs() *AdvertServiceCreateAdCreativeArgs {
	return &AdvertServiceCreateAdCreativeArgs{}
}

func (p *AdvertServiceCreateAdCreativeArgs) InitDefault() {
}

var AdvertServiceCreateAdCreativeArgs_Req_DEFAULT *CreateAdCreativeRequest

func (p *AdvertServiceCreateAdCreativeArgs) GetReq() (v *CreateAdCreativeRequest) {
	if !p.IsSetReq() {
		return AdvertServiceCreateAdCreativeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdvertServiceCreateAdCreativeArgs) SetReq(val *CreateAdCreativeRequest) {
	p.Req = val
}

func (p *AdvertServiceCreateAdCreativeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdvertServiceCreateAdCreativeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceCreateAdCreativeArgs(%+v)", *p)
}

var fieldIDToName_AdvertServiceCreateAdCreativeArgs = map[int16]string{
	1: "req",
}

type AdvertServiceCreateAdCreativeResult struct {
	Success *CreateAdCreativeResponse `thrift:"success,0,optional" frugal:"0,optional,CreateAdCreativeResponse" json:"success,omitempty"`
}

func NewAdvertServiceCreateAdCreativeResult() *AdvertServiceCreateAdCreativeResult {
	return &AdvertServiceCreateAdCreativeResult{}
}

func (p *AdvertServiceCreateAdCreativeResult) InitDefault() {
}

var AdvertServiceCreateAdCreativeResult_Success_DEFAULT *CreateAdCreativeResponse

func (p *AdvertServiceCreateAdCreativeResult) GetSuccess() (v *CreateAdCreativeResponse) {
	if !p.IsSetSuccess() {
		return AdvertServiceCreateAdCreativeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdvertServiceCreateAdCreativeResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateAdCreativeResponse)
}

func (p *AdvertServiceCreateAdCreativeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdvertServiceCreateAdCreativeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceCreateAdCreativeResult(%+v)", *p)
}

var fieldIDToName_AdvertServiceCreateAdCreativeResult = map[int16]string{
	0: "success",
}

type AdvertServiceUpdateAdCreativeArgs struct {
	Req *UpdateAdCreativeRequest `thrift:"req,1" frugal:"1,default,UpdateAdCreativeRequest" json:"req"`
}

func NewAdvertServiceUpdateAdCreativeArgs() *AdvertServiceUpdateAdCreativeArgs {
	return &AdvertServiceUpdateAdCreativeArgs{}
}

func (p *AdvertServiceUpdateAdCreativeArgs) InitDefault() {
}

var AdvertServiceUpdateAdCreativeArgs_Req_DEFAULT *UpdateAdCreativeRequest

func (p *AdvertServiceUpdateAdCreativeArgs) GetReq() (v *UpdateAdCreativeRequest) {
	if !p.IsSetReq() {
		return AdvertServiceUpdateAdCreativeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdvertServiceUpdateAdCreativeArgs) SetReq(val *UpdateAdCreativeRequest) {
	p.Req = val
}

func (p *AdvertServiceUpdateAdCreativeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdvertServiceUpdateAdCreativeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceUpdateAdCreativeArgs(%+v)", *p)
}

var fieldIDToName_AdvertServiceUpdateAdCreativeArgs = map[int16]string{
	1: "req",
}

type AdvertServiceUpdateAdCreativeResult struct {
	Success *UpdateAdCreativeResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateAdCreativeResponse" json:"success,omitempty"`
}

func NewAdvertServiceUpdateAdCreativeResult() *AdvertServiceUpdateAdCreativeResult {
	return &AdvertServiceUpdateAdCreativeResult{}
}

func (p *AdvertServiceUpdateAdCreativeResult) InitDefault() {
}

var AdvertServiceUpdateAdCreativeResult_Success_DEFAULT *UpdateAdCreativeResponse

func (p *AdvertServiceUpdateAdCreativeResult) GetSuccess() (v *UpdateAdCreativeResponse) {
	if !p.IsSetSuccess() {
		return AdvertServiceUpdateAdCreativeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdvertServiceUpdateAdCreativeResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateAdCreativeResponse)
}

func (p *AdvertServiceUpdateAdCreativeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdvertServiceUpdateAdCreativeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceUpdateAdCreativeResult(%+v)", *p)
}

var fieldIDToName_AdvertServiceUpdateAdCreativeResult = map[int16]string{
	0: "success",
}

type AdvertServiceGetAdCreativeArgs struct {
	Req *GetAdCreativeRequest `thrift:"req,1" frugal:"1,default,GetAdCreativeRequest" json:"req"`
}

func NewAdvertServiceGetAdCreativeArgs() *AdvertServiceGetAdCreativeArgs {
	return &AdvertServiceGetAdCreativeArgs{}
}

func (p *AdvertServiceGetAdCreativeArgs) InitDefault() {
}

var AdvertServiceGetAdCreativeArgs_Req_DEFAULT *GetAdCreativeRequest

func (p *AdvertServiceGetAdCreativeArgs) GetReq() (v *GetAdCreativeRequest) {
	if !p.IsSetReq() {
		return AdvertServiceGetAdCreativeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdvertServiceGetAdCreativeArgs) SetReq(val *GetAdCreativeRequest) {
	p.Req = val
}

func (p *AdvertServiceGetAdCreativeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdvertServiceGetAdCreativeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceGetAdCreativeArgs(%+v)", *p)
}

var fieldIDToName_AdvertServiceGetAdCreativeArgs = map[int16]string{
	1: "req",
}

type AdvertServiceGetAdCreativeResult struct {
	Success *GetAdCreativeResponse `thrift:"success,0,optional" frugal:"0,optional,GetAdCreativeResponse" json:"success,omitempty"`
}

func NewAdvertServiceGetAdCreativeResult() *AdvertServiceGetAdCreativeResult {
	return &AdvertServiceGetAdCreativeResult{}
}

func (p *AdvertServiceGetAdCreativeResult) InitDefault() {
}

var AdvertServiceGetAdCreativeResult_Success_DEFAULT *GetAdCreativeResponse

func (p *AdvertServiceGetAdCreativeResult) GetSuccess() (v *GetAdCreativeResponse) {
	if !p.IsSetSuccess() {
		return AdvertServiceGetAdCreativeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdvertServiceGetAdCreativeResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetAdCreativeResponse)
}

func (p *AdvertServiceGetAdCreativeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdvertServiceGetAdCreativeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceGetAdCreativeResult(%+v)", *p)
}

var fieldIDToName_AdvertServiceGetAdCreativeResult = map[int16]string{
	0: "success",
}

type AdvertServiceListAdCreativesArgs struct {
	Req *ListAdCreativesRequest `thrift:"req,1" frugal:"1,default,ListAdCreativesRequest" json:"req"`
}

func NewAdvertServiceListAdCreativesArgs() *AdvertServiceListAdCreativesArgs {
	return &AdvertServiceListAdCreativesArgs{}
}

func (p *AdvertServiceListAdCreativesArgs) InitDefault() {
}

var AdvertServiceListAdCreativesArgs_Req_DEFAULT *ListAdCreativesRequest

func (p *AdvertServiceListAdCreativesArgs) GetReq() (v *ListAdCreativesRequest) {
	if !p.IsSetReq() {
		return AdvertServiceListAdCreativesArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdvertServiceListAdCreativesArgs) SetReq(val *ListAdCreativesRequest) {
	p.Req = val
}

func (p *AdvertServiceListAdCreativesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdvertServiceListAdCreativesArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceListAdCreativesArgs(%+v)", *p)
}

var fieldIDToName_AdvertServiceListAdCreativesArgs = map[int16]string{
	1: "req",
}

type AdvertServiceListAdCreativesResult struct {
	Success *ListAdCreativesResponse `thrift:"success,0,optional" frugal:"0,optional,ListAdCreativesResponse" json:"success,omitempty"`
}

func NewAdvertServiceListAdCreativesResult() *AdvertServiceListAdCreativesResult {
	return &AdvertServiceListAdCreativesResult{}
}

func (p *AdvertServiceListAdCreativesResult) InitDefault() {
}

var AdvertServiceListAdCreativesResult_Success_DEFAULT *ListAdCreativesResponse

func (p *AdvertServiceListAdCreativesResult) GetSuccess() (v *ListAdCreativesResponse) {
	if !p.IsSetSuccess() {
		return AdvertServiceListAdCreativesResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdvertServiceListAdCreativesResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListAdCreativesResponse)
}

func (p *AdvertServiceListAdCreativesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdvertServiceListAdCreativesResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceListAdCreativesResult(%+v)", *p)
}

var fieldIDToName_AdvertServiceListAdCreativesResult = map[int16]string{
	0: "success",
}

type AdvertServiceDeleteAdCreativeArgs struct {
	Req *DeleteAdCreativeRequest `thrift:"req,1" frugal:"1,default,DeleteAdCreativeRequest" json:"req"`
}

func NewAdvertServiceDeleteAdCreativeArgs() *AdvertServiceDeleteAdCreativeArgs {
	return &AdvertServiceDeleteAdCreativeArgs{}
}

func (p *AdvertServiceDeleteAdCreativeArgs) InitDefault() {
}

var AdvertServiceDeleteAdCreativeArgs_Req_DEFAULT *DeleteAdCreativeRequest

func (p *AdvertServiceDeleteAdCreativeArgs) GetReq() (v *DeleteAdCreativeRequest) {
	if !p.IsSetReq() {
		return AdvertServiceDeleteAdCreativeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdvertServiceDeleteAdCreativeArgs) SetReq(val *DeleteAdCreativeRequest) {
	p.Req = val
}

func (p *AdvertServiceDeleteAdCreativeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdvertServiceDeleteAdCreativeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceDeleteAdCreativeArgs(%+v)", *p)
}

var fieldIDToName_AdvertServiceDeleteAdCreativeArgs = map[int16]string{
	1: "req",
}

type AdvertServiceDeleteAdCreativeResult struct {
	Success *DeleteAdCreativeResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteAdCreativeResponse" json:"success,omitempty"`
}

func NewAdvertServiceDeleteAdCreativeResult() *AdvertServiceDeleteAdCreativeResult {
	return &AdvertServiceDeleteAdCreativeResult{}
}

func (p *AdvertServiceDeleteAdCreativeResult) InitDefault() {
}

var AdvertServiceDeleteAdCreativeResult_Success_DEFAULT *DeleteAdCreativeResponse

func (p *AdvertServiceDeleteAdCreativeResult) GetSuccess() (v *DeleteAdCreativeResponse) {
	if !p.IsSetSuccess() {
		return AdvertServiceDeleteAdCreativeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdvertServiceDeleteAdCreativeResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteAdCreativeResponse)
}

func (p *AdvertServiceDeleteAdCreativeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdvertServiceDeleteAdCreativeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceDeleteAdCreativeResult(%+v)", *p)
}

var fieldIDToName_AdvertServiceDeleteAdCreativeResult = map[int16]string{
	0: "success",
}

type AdvertServiceCreateUserProfileArgs struct {
	Req *CreateUserProfileRequest `thrift:"req,1" frugal:"1,default,CreateUserProfileRequest" json:"req"`
}

func NewAdvertServiceCreateUserProfileArgs() *AdvertServiceCreateUserProfileArgs {
	return &AdvertServiceCreateUserProfileArgs{}
}

func (p *AdvertServiceCreateUserProfileArgs) InitDefault() {
}

var AdvertServiceCreateUserProfileArgs_Req_DEFAULT *CreateUserProfileRequest

func (p *AdvertServiceCreateUserProfileArgs) GetReq() (v *CreateUserProfileRequest) {
	if !p.IsSetReq() {
		return AdvertServiceCreateUserProfileArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdvertServiceCreateUserProfileArgs) SetReq(val *CreateUserProfileRequest) {
	p.Req = val
}

func (p *AdvertServiceCreateUserProfileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdvertServiceCreateUserProfileArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceCreateUserProfileArgs(%+v)", *p)
}

var fieldIDToName_AdvertServiceCreateUserProfileArgs = map[int16]string{
	1: "req",
}

type AdvertServiceCreateUserProfileResult struct {
	Success *CreateUserProfileResponse `thrift:"success,0,optional" frugal:"0,optional,CreateUserProfileResponse" json:"success,omitempty"`
}

func NewAdvertServiceCreateUserProfileResult() *AdvertServiceCreateUserProfileResult {
	return &AdvertServiceCreateUserProfileResult{}
}

func (p *AdvertServiceCreateUserProfileResult) InitDefault() {
}

var AdvertServiceCreateUserProfileResult_Success_DEFAULT *CreateUserProfileResponse

func (p *AdvertServiceCreateUserProfileResult) GetSuccess() (v *CreateUserProfileResponse) {
	if !p.IsSetSuccess() {
		return AdvertServiceCreateUserProfileResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdvertServiceCreateUserProfileResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateUserProfileResponse)
}

func (p *AdvertServiceCreateUserProfileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdvertServiceCreateUserProfileResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceCreateUserProfileResult(%+v)", *p)
}

var fieldIDToName_AdvertServiceCreateUserProfileResult = map[int16]string{
	0: "success",
}

type AdvertServiceUpdateUserProfileArgs struct {
	Req *UpdateUserProfileRequest `thrift:"req,1" frugal:"1,default,UpdateUserProfileRequest" json:"req"`
}

func NewAdvertServiceUpdateUserProfileArgs() *AdvertServiceUpdateUserProfileArgs {
	return &AdvertServiceUpdateUserProfileArgs{}
}

func (p *AdvertServiceUpdateUserProfileArgs) InitDefault() {
}

var AdvertServiceUpdateUserProfileArgs_Req_DEFAULT *UpdateUserProfileRequest

func (p *AdvertServiceUpdateUserProfileArgs) GetReq() (v *UpdateUserProfileRequest) {
	if !p.IsSetReq() {
		return AdvertServiceUpdateUserProfileArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdvertServiceUpdateUserProfileArgs) SetReq(val *UpdateUserProfileRequest) {
	p.Req = val
}

func (p *AdvertServiceUpdateUserProfileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdvertServiceUpdateUserProfileArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceUpdateUserProfileArgs(%+v)", *p)
}

var fieldIDToName_AdvertServiceUpdateUserProfileArgs = map[int16]string{
	1: "req",
}

type AdvertServiceUpdateUserProfileResult struct {
	Success *UpdateUserProfileResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateUserProfileResponse" json:"success,omitempty"`
}

func NewAdvertServiceUpdateUserProfileResult() *AdvertServiceUpdateUserProfileResult {
	return &AdvertServiceUpdateUserProfileResult{}
}

func (p *AdvertServiceUpdateUserProfileResult) InitDefault() {
}

var AdvertServiceUpdateUserProfileResult_Success_DEFAULT *UpdateUserProfileResponse

func (p *AdvertServiceUpdateUserProfileResult) GetSuccess() (v *UpdateUserProfileResponse) {
	if !p.IsSetSuccess() {
		return AdvertServiceUpdateUserProfileResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdvertServiceUpdateUserProfileResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateUserProfileResponse)
}

func (p *AdvertServiceUpdateUserProfileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdvertServiceUpdateUserProfileResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceUpdateUserProfileResult(%+v)", *p)
}

var fieldIDToName_AdvertServiceUpdateUserProfileResult = map[int16]string{
	0: "success",
}

type AdvertServiceGetUserProfileArgs struct {
	Req *GetUserProfileRequest `thrift:"req,1" frugal:"1,default,GetUserProfileRequest" json:"req"`
}

func NewAdvertServiceGetUserProfileArgs() *AdvertServiceGetUserProfileArgs {
	return &AdvertServiceGetUserProfileArgs{}
}

func (p *AdvertServiceGetUserProfileArgs) InitDefault() {
}

var AdvertServiceGetUserProfileArgs_Req_DEFAULT *GetUserProfileRequest

func (p *AdvertServiceGetUserProfileArgs) GetReq() (v *GetUserProfileRequest) {
	if !p.IsSetReq() {
		return AdvertServiceGetUserProfileArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdvertServiceGetUserProfileArgs) SetReq(val *GetUserProfileRequest) {
	p.Req = val
}

func (p *AdvertServiceGetUserProfileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdvertServiceGetUserProfileArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceGetUserProfileArgs(%+v)", *p)
}

var fieldIDToName_AdvertServiceGetUserProfileArgs = map[int16]string{
	1: "req",
}

type AdvertServiceGetUserProfileResult struct {
	Success *GetUserProfileResponse `thrift:"success,0,optional" frugal:"0,optional,GetUserProfileResponse" json:"success,omitempty"`
}

func NewAdvertServiceGetUserProfileResult() *AdvertServiceGetUserProfileResult {
	return &AdvertServiceGetUserProfileResult{}
}

func (p *AdvertServiceGetUserProfileResult) InitDefault() {
}

var AdvertServiceGetUserProfileResult_Success_DEFAULT *GetUserProfileResponse

func (p *AdvertServiceGetUserProfileResult) GetSuccess() (v *GetUserProfileResponse) {
	if !p.IsSetSuccess() {
		return AdvertServiceGetUserProfileResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdvertServiceGetUserProfileResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserProfileResponse)
}

func (p *AdvertServiceGetUserProfileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdvertServiceGetUserProfileResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceGetUserProfileResult(%+v)", *p)
}

var fieldIDToName_AdvertServiceGetUserProfileResult = map[int16]string{
	0: "success",
}

type AdvertServiceDeleteUserProfileArgs struct {
	Req *DeleteUserProfileRequest `thrift:"req,1" frugal:"1,default,DeleteUserProfileRequest" json:"req"`
}

func NewAdvertServiceDeleteUserProfileArgs() *AdvertServiceDeleteUserProfileArgs {
	return &AdvertServiceDeleteUserProfileArgs{}
}

func (p *AdvertServiceDeleteUserProfileArgs) InitDefault() {
}

var AdvertServiceDeleteUserProfileArgs_Req_DEFAULT *DeleteUserProfileRequest

func (p *AdvertServiceDeleteUserProfileArgs) GetReq() (v *DeleteUserProfileRequest) {
	if !p.IsSetReq() {
		return AdvertServiceDeleteUserProfileArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdvertServiceDeleteUserProfileArgs) SetReq(val *DeleteUserProfileRequest) {
	p.Req = val
}

func (p *AdvertServiceDeleteUserProfileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdvertServiceDeleteUserProfileArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceDeleteUserProfileArgs(%+v)", *p)
}

var fieldIDToName_AdvertServiceDeleteUserProfileArgs = map[int16]string{
	1: "req",
}

type AdvertServiceDeleteUserProfileResult struct {
	Success *DeleteUserProfileResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteUserProfileResponse" json:"success,omitempty"`
}

func NewAdvertServiceDeleteUserProfileResult() *AdvertServiceDeleteUserProfileResult {
	return &AdvertServiceDeleteUserProfileResult{}
}

func (p *AdvertServiceDeleteUserProfileResult) InitDefault() {
}

var AdvertServiceDeleteUserProfileResult_Success_DEFAULT *DeleteUserProfileResponse

func (p *AdvertServiceDeleteUserProfileResult) GetSuccess() (v *DeleteUserProfileResponse) {
	if !p.IsSetSuccess() {
		return AdvertServiceDeleteUserProfileResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdvertServiceDeleteUserProfileResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteUserProfileResponse)
}

func (p *AdvertServiceDeleteUserProfileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdvertServiceDeleteUserProfileResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceDeleteUserProfileResult(%+v)", *p)
}

var fieldIDToName_AdvertServiceDeleteUserProfileResult = map[int16]string{
	0: "success",
}

type AdvertServiceAddUserInterestArgs struct {
	Req *AddUserInterestRequest `thrift:"req,1" frugal:"1,default,AddUserInterestRequest" json:"req"`
}

func NewAdvertServiceAddUserInterestArgs() *AdvertServiceAddUserInterestArgs {
	return &AdvertServiceAddUserInterestArgs{}
}

func (p *AdvertServiceAddUserInterestArgs) InitDefault() {
}

var AdvertServiceAddUserInterestArgs_Req_DEFAULT *AddUserInterestRequest

func (p *AdvertServiceAddUserInterestArgs) GetReq() (v *AddUserInterestRequest) {
	if !p.IsSetReq() {
		return AdvertServiceAddUserInterestArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdvertServiceAddUserInterestArgs) SetReq(val *AddUserInterestRequest) {
	p.Req = val
}

func (p *AdvertServiceAddUserInterestArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdvertServiceAddUserInterestArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceAddUserInterestArgs(%+v)", *p)
}

var fieldIDToName_AdvertServiceAddUserInterestArgs = map[int16]string{
	1: "req",
}

type AdvertServiceAddUserInterestResult struct {
	Success *AddUserInterestResponse `thrift:"success,0,optional" frugal:"0,optional,AddUserInterestResponse" json:"success,omitempty"`
}

func NewAdvertServiceAddUserInterestResult() *AdvertServiceAddUserInterestResult {
	return &AdvertServiceAddUserInterestResult{}
}

func (p *AdvertServiceAddUserInterestResult) InitDefault() {
}

var AdvertServiceAddUserInterestResult_Success_DEFAULT *AddUserInterestResponse

func (p *AdvertServiceAddUserInterestResult) GetSuccess() (v *AddUserInterestResponse) {
	if !p.IsSetSuccess() {
		return AdvertServiceAddUserInterestResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdvertServiceAddUserInterestResult) SetSuccess(x interface{}) {
	p.Success = x.(*AddUserInterestResponse)
}

func (p *AdvertServiceAddUserInterestResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdvertServiceAddUserInterestResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceAddUserInterestResult(%+v)", *p)
}

var fieldIDToName_AdvertServiceAddUserInterestResult = map[int16]string{
	0: "success",
}

type AdvertServiceUpdateUserInterestArgs struct {
	Req *UpdateUserInterestRequest `thrift:"req,1" frugal:"1,default,UpdateUserInterestRequest" json:"req"`
}

func NewAdvertServiceUpdateUserInterestArgs() *AdvertServiceUpdateUserInterestArgs {
	return &AdvertServiceUpdateUserInterestArgs{}
}

func (p *AdvertServiceUpdateUserInterestArgs) InitDefault() {
}

var AdvertServiceUpdateUserInterestArgs_Req_DEFAULT *UpdateUserInterestRequest

func (p *AdvertServiceUpdateUserInterestArgs) GetReq() (v *UpdateUserInterestRequest) {
	if !p.IsSetReq() {
		return AdvertServiceUpdateUserInterestArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdvertServiceUpdateUserInterestArgs) SetReq(val *UpdateUserInterestRequest) {
	p.Req = val
}

func (p *AdvertServiceUpdateUserInterestArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdvertServiceUpdateUserInterestArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceUpdateUserInterestArgs(%+v)", *p)
}

var fieldIDToName_AdvertServiceUpdateUserInterestArgs = map[int16]string{
	1: "req",
}

type AdvertServiceUpdateUserInterestResult struct {
	Success *UpdateUserInterestResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateUserInterestResponse" json:"success,omitempty"`
}

func NewAdvertServiceUpdateUserInterestResult() *AdvertServiceUpdateUserInterestResult {
	return &AdvertServiceUpdateUserInterestResult{}
}

func (p *AdvertServiceUpdateUserInterestResult) InitDefault() {
}

var AdvertServiceUpdateUserInterestResult_Success_DEFAULT *UpdateUserInterestResponse

func (p *AdvertServiceUpdateUserInterestResult) GetSuccess() (v *UpdateUserInterestResponse) {
	if !p.IsSetSuccess() {
		return AdvertServiceUpdateUserInterestResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdvertServiceUpdateUserInterestResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateUserInterestResponse)
}

func (p *AdvertServiceUpdateUserInterestResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdvertServiceUpdateUserInterestResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceUpdateUserInterestResult(%+v)", *p)
}

var fieldIDToName_AdvertServiceUpdateUserInterestResult = map[int16]string{
	0: "success",
}

type AdvertServiceGetUserInterestsArgs struct {
	Req *GetUserInterestsRequest `thrift:"req,1" frugal:"1,default,GetUserInterestsRequest" json:"req"`
}

func NewAdvertServiceGetUserInterestsArgs() *AdvertServiceGetUserInterestsArgs {
	return &AdvertServiceGetUserInterestsArgs{}
}

func (p *AdvertServiceGetUserInterestsArgs) InitDefault() {
}

var AdvertServiceGetUserInterestsArgs_Req_DEFAULT *GetUserInterestsRequest

func (p *AdvertServiceGetUserInterestsArgs) GetReq() (v *GetUserInterestsRequest) {
	if !p.IsSetReq() {
		return AdvertServiceGetUserInterestsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdvertServiceGetUserInterestsArgs) SetReq(val *GetUserInterestsRequest) {
	p.Req = val
}

func (p *AdvertServiceGetUserInterestsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdvertServiceGetUserInterestsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceGetUserInterestsArgs(%+v)", *p)
}

var fieldIDToName_AdvertServiceGetUserInterestsArgs = map[int16]string{
	1: "req",
}

type AdvertServiceGetUserInterestsResult struct {
	Success *GetUserInterestsResponse `thrift:"success,0,optional" frugal:"0,optional,GetUserInterestsResponse" json:"success,omitempty"`
}

func NewAdvertServiceGetUserInterestsResult() *AdvertServiceGetUserInterestsResult {
	return &AdvertServiceGetUserInterestsResult{}
}

func (p *AdvertServiceGetUserInterestsResult) InitDefault() {
}

var AdvertServiceGetUserInterestsResult_Success_DEFAULT *GetUserInterestsResponse

func (p *AdvertServiceGetUserInterestsResult) GetSuccess() (v *GetUserInterestsResponse) {
	if !p.IsSetSuccess() {
		return AdvertServiceGetUserInterestsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdvertServiceGetUserInterestsResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserInterestsResponse)
}

func (p *AdvertServiceGetUserInterestsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdvertServiceGetUserInterestsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceGetUserInterestsResult(%+v)", *p)
}

var fieldIDToName_AdvertServiceGetUserInterestsResult = map[int16]string{
	0: "success",
}

type AdvertServiceDeleteUserInterestArgs struct {
	Req *DeleteUserInterestRequest `thrift:"req,1" frugal:"1,default,DeleteUserInterestRequest" json:"req"`
}

func NewAdvertServiceDeleteUserInterestArgs() *AdvertServiceDeleteUserInterestArgs {
	return &AdvertServiceDeleteUserInterestArgs{}
}

func (p *AdvertServiceDeleteUserInterestArgs) InitDefault() {
}

var AdvertServiceDeleteUserInterestArgs_Req_DEFAULT *DeleteUserInterestRequest

func (p *AdvertServiceDeleteUserInterestArgs) GetReq() (v *DeleteUserInterestRequest) {
	if !p.IsSetReq() {
		return AdvertServiceDeleteUserInterestArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdvertServiceDeleteUserInterestArgs) SetReq(val *DeleteUserInterestRequest) {
	p.Req = val
}

func (p *AdvertServiceDeleteUserInterestArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdvertServiceDeleteUserInterestArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceDeleteUserInterestArgs(%+v)", *p)
}

var fieldIDToName_AdvertServiceDeleteUserInterestArgs = map[int16]string{
	1: "req",
}

type AdvertServiceDeleteUserInterestResult struct {
	Success *DeleteUserInterestResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteUserInterestResponse" json:"success,omitempty"`
}

func NewAdvertServiceDeleteUserInterestResult() *AdvertServiceDeleteUserInterestResult {
	return &AdvertServiceDeleteUserInterestResult{}
}

func (p *AdvertServiceDeleteUserInterestResult) InitDefault() {
}

var AdvertServiceDeleteUserInterestResult_Success_DEFAULT *DeleteUserInterestResponse

func (p *AdvertServiceDeleteUserInterestResult) GetSuccess() (v *DeleteUserInterestResponse) {
	if !p.IsSetSuccess() {
		return AdvertServiceDeleteUserInterestResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdvertServiceDeleteUserInterestResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteUserInterestResponse)
}

func (p *AdvertServiceDeleteUserInterestResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdvertServiceDeleteUserInterestResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceDeleteUserInterestResult(%+v)", *p)
}

var fieldIDToName_AdvertServiceDeleteUserInterestResult = map[int16]string{
	0: "success",
}

type AdvertServiceCreateAdEventArgs struct {
	Req *CreateAdEventRequest `thrift:"req,1" frugal:"1,default,CreateAdEventRequest" json:"req"`
}

func NewAdvertServiceCreateAdEventArgs() *AdvertServiceCreateAdEventArgs {
	return &AdvertServiceCreateAdEventArgs{}
}

func (p *AdvertServiceCreateAdEventArgs) InitDefault() {
}

var AdvertServiceCreateAdEventArgs_Req_DEFAULT *CreateAdEventRequest

func (p *AdvertServiceCreateAdEventArgs) GetReq() (v *CreateAdEventRequest) {
	if !p.IsSetReq() {
		return AdvertServiceCreateAdEventArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdvertServiceCreateAdEventArgs) SetReq(val *CreateAdEventRequest) {
	p.Req = val
}

func (p *AdvertServiceCreateAdEventArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdvertServiceCreateAdEventArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceCreateAdEventArgs(%+v)", *p)
}

var fieldIDToName_AdvertServiceCreateAdEventArgs = map[int16]string{
	1: "req",
}

type AdvertServiceCreateAdEventResult struct {
	Success *CreateAdEventResponse `thrift:"success,0,optional" frugal:"0,optional,CreateAdEventResponse" json:"success,omitempty"`
}

func NewAdvertServiceCreateAdEventResult() *AdvertServiceCreateAdEventResult {
	return &AdvertServiceCreateAdEventResult{}
}

func (p *AdvertServiceCreateAdEventResult) InitDefault() {
}

var AdvertServiceCreateAdEventResult_Success_DEFAULT *CreateAdEventResponse

func (p *AdvertServiceCreateAdEventResult) GetSuccess() (v *CreateAdEventResponse) {
	if !p.IsSetSuccess() {
		return AdvertServiceCreateAdEventResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdvertServiceCreateAdEventResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateAdEventResponse)
}

func (p *AdvertServiceCreateAdEventResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdvertServiceCreateAdEventResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceCreateAdEventResult(%+v)", *p)
}

var fieldIDToName_AdvertServiceCreateAdEventResult = map[int16]string{
	0: "success",
}

type AdvertServiceGetUserAdEventsArgs struct {
	Req *GetUserAdEventsRequest `thrift:"req,1" frugal:"1,default,GetUserAdEventsRequest" json:"req"`
}

func NewAdvertServiceGetUserAdEventsArgs() *AdvertServiceGetUserAdEventsArgs {
	return &AdvertServiceGetUserAdEventsArgs{}
}

func (p *AdvertServiceGetUserAdEventsArgs) InitDefault() {
}

var AdvertServiceGetUserAdEventsArgs_Req_DEFAULT *GetUserAdEventsRequest

func (p *AdvertServiceGetUserAdEventsArgs) GetReq() (v *GetUserAdEventsRequest) {
	if !p.IsSetReq() {
		return AdvertServiceGetUserAdEventsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdvertServiceGetUserAdEventsArgs) SetReq(val *GetUserAdEventsRequest) {
	p.Req = val
}

func (p *AdvertServiceGetUserAdEventsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdvertServiceGetUserAdEventsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceGetUserAdEventsArgs(%+v)", *p)
}

var fieldIDToName_AdvertServiceGetUserAdEventsArgs = map[int16]string{
	1: "req",
}

type AdvertServiceGetUserAdEventsResult struct {
	Success *GetUserAdEventsResponse `thrift:"success,0,optional" frugal:"0,optional,GetUserAdEventsResponse" json:"success,omitempty"`
}

func NewAdvertServiceGetUserAdEventsResult() *AdvertServiceGetUserAdEventsResult {
	return &AdvertServiceGetUserAdEventsResult{}
}

func (p *AdvertServiceGetUserAdEventsResult) InitDefault() {
}

var AdvertServiceGetUserAdEventsResult_Success_DEFAULT *GetUserAdEventsResponse

func (p *AdvertServiceGetUserAdEventsResult) GetSuccess() (v *GetUserAdEventsResponse) {
	if !p.IsSetSuccess() {
		return AdvertServiceGetUserAdEventsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdvertServiceGetUserAdEventsResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserAdEventsResponse)
}

func (p *AdvertServiceGetUserAdEventsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdvertServiceGetUserAdEventsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceGetUserAdEventsResult(%+v)", *p)
}

var fieldIDToName_AdvertServiceGetUserAdEventsResult = map[int16]string{
	0: "success",
}

type AdvertServiceGetCreativeAdEventsArgs struct {
	Req *GetCreativeAdEventsRequest `thrift:"req,1" frugal:"1,default,GetCreativeAdEventsRequest" json:"req"`
}

func NewAdvertServiceGetCreativeAdEventsArgs() *AdvertServiceGetCreativeAdEventsArgs {
	return &AdvertServiceGetCreativeAdEventsArgs{}
}

func (p *AdvertServiceGetCreativeAdEventsArgs) InitDefault() {
}

var AdvertServiceGetCreativeAdEventsArgs_Req_DEFAULT *GetCreativeAdEventsRequest

func (p *AdvertServiceGetCreativeAdEventsArgs) GetReq() (v *GetCreativeAdEventsRequest) {
	if !p.IsSetReq() {
		return AdvertServiceGetCreativeAdEventsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AdvertServiceGetCreativeAdEventsArgs) SetReq(val *GetCreativeAdEventsRequest) {
	p.Req = val
}

func (p *AdvertServiceGetCreativeAdEventsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AdvertServiceGetCreativeAdEventsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceGetCreativeAdEventsArgs(%+v)", *p)
}

var fieldIDToName_AdvertServiceGetCreativeAdEventsArgs = map[int16]string{
	1: "req",
}

type AdvertServiceGetCreativeAdEventsResult struct {
	Success *GetCreativeAdEventsResponse `thrift:"success,0,optional" frugal:"0,optional,GetCreativeAdEventsResponse" json:"success,omitempty"`
}

func NewAdvertServiceGetCreativeAdEventsResult() *AdvertServiceGetCreativeAdEventsResult {
	return &AdvertServiceGetCreativeAdEventsResult{}
}

func (p *AdvertServiceGetCreativeAdEventsResult) InitDefault() {
}

var AdvertServiceGetCreativeAdEventsResult_Success_DEFAULT *GetCreativeAdEventsResponse

func (p *AdvertServiceGetCreativeAdEventsResult) GetSuccess() (v *GetCreativeAdEventsResponse) {
	if !p.IsSetSuccess() {
		return AdvertServiceGetCreativeAdEventsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AdvertServiceGetCreativeAdEventsResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetCreativeAdEventsResponse)
}

func (p *AdvertServiceGetCreativeAdEventsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AdvertServiceGetCreativeAdEventsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdvertServiceGetCreativeAdEventsResult(%+v)", *p)
}

var fieldIDToName_AdvertServiceGetCreativeAdEventsResult = map[int16]string{
	0: "success",
}
