// Code generated by Kitex. DO NOT EDIT.

package advert

import (
	"context"
)

// AdvertService 服务接口
type AdvertService interface {
	CreateAdPlan(ctx context.Context, req *CreateAdPlanRequest) (*CreateAdPlanResponse, error)
	UpdateAdPlan(ctx context.Context, req *UpdateAdPlanRequest) (*UpdateAdPlanResponse, error)
	GetAdPlan(ctx context.Context, req *GetAdPlanRequest) (*GetAdPlanResponse, error)
	ListAdPlans(ctx context.Context, req *ListAdPlansRequest) (*ListAdPlansResponse, error)
	DeleteAdPlan(ctx context.Context, req *DeleteAdPlanRequest) (*DeleteAdPlanResponse, error)

	CreateAdCreative(ctx context.Context, req *CreateAdCreativeRequest) (*CreateAdCreativeResponse, error)
	UpdateAdCreative(ctx context.Context, req *UpdateAdCreativeRequest) (*UpdateAdCreativeResponse, error)
	GetAdCreative(ctx context.Context, req *GetAdCreativeRequest) (*GetAdCreativeResponse, error)
	ListAdCreatives(ctx context.Context, req *ListAdCreativesRequest) (*ListAdCreativesResponse, error)
	DeleteAdCreative(ctx context.Context, req *DeleteAdCreativeRequest) (*DeleteAdCreativeResponse, error)

	CreateUserProfile(ctx context.Context, req *CreateUserProfileRequest) (*CreateUserProfileResponse, error)
	UpdateUserProfile(ctx context.Context, req *UpdateUserProfileRequest) (*UpdateUserProfileResponse, error)
	GetUserProfile(ctx context.Context, req *GetUserProfileRequest) (*GetUserProfileResponse, error)
	DeleteUserProfile(ctx context.Context, req *DeleteUserProfileRequest) (*DeleteUserProfileResponse, error)

	AddUserInterest(ctx context.Context, req *AddUserInterestRequest) (*AddUserInterestResponse, error)
	UpdateUserInterest(ctx context.Context, req *UpdateUserInterestRequest) (*UpdateUserInterestResponse, error)
	GetUserInterests(ctx context.Context, req *GetUserInterestsRequest) (*GetUserInterestsResponse, error)
	DeleteUserInterest(ctx context.Context, req *DeleteUserInterestRequest) (*DeleteUserInterestResponse, error)

	CreateAdEvent(ctx context.Context, req *CreateAdEventRequest) (*CreateAdEventResponse, error)
	GetUserAdEvents(ctx context.Context, req *GetUserAdEventsRequest) (*GetUserAdEventsResponse, error)
	GetCreativeAdEvents(ctx context.Context, req *GetCreativeAdEventsRequest) (*GetCreativeAdEventsResponse, error)
}
