// Code generated by Kitex. DO NOT EDIT.

package advert

type UserAdEvent struct {
	EventId    int64  `thrift:"eventId,1" json:"eventId"`
	UserId     int64  `thrift:"userId,2" json:"userId"`
	CreativeId int64  `thrift:"creativeId,3" json:"creativeId"`
	EventType  int32  `thrift:"eventType,4" json:"eventType"`
	Ts         string `thrift:"ts,5" json:"ts"`
	Extra      string `thrift:"extra,6" json:"extra"`
}

type CreateAdEventRequest struct {
	UserId     int64  `thrift:"userId,1" json:"userId"`
	CreativeId int64  `thrift:"creativeId,2" json:"creativeId"`
	EventType  int32  `thrift:"eventType,3" json:"eventType"`
	Ts         string `thrift:"ts,4" json:"ts"`
	Extra      string `thrift:"extra,5" json:"extra"`
}

type CreateAdEventResponse struct {
	BaseResp *BaseResponse `thrift:"baseResp,1" json:"baseResp"`
	EventId  int64         `thrift:"eventId,2" json:"eventId"`
}

type GetUserAdEventsRequest struct {
	UserId    int64  `thrift:"userId,1" json:"userId"`
	Page      int32  `thrift:"page,2" json:"page"`
	PageSize  int32  `thrift:"pageSize,3" json:"pageSize"`
	EventType *int32 `thrift:"eventType,4,optional" json:"eventType,omitempty"`
}

type GetUserAdEventsResponse struct {
	BaseResp *BaseResponse  `thrift:"baseResp,1" json:"baseResp"`
	Events   []*UserAdEvent `thrift:"events,2" json:"events"`
	Total    int64          `thrift:"total,3" json:"total"`
}

type GetCreativeAdEventsRequest struct {
	CreativeId int64  `thrift:"creativeId,1" json:"creativeId"`
	Page       int32  `thrift:"page,2" json:"page"`
	PageSize   int32  `thrift:"pageSize,3" json:"pageSize"`
	EventType  *int32 `thrift:"eventType,4,optional" json:"eventType,omitempty"`
}

type GetCreativeAdEventsResponse struct {
	BaseResp *BaseResponse  `thrift:"baseResp,1" json:"baseResp"`
	Events   []*UserAdEvent `thrift:"events,2" json:"events"`
	Total    int64          `thrift:"total,3" json:"total"`
}
