// Code generated by Kitex. DO NOT EDIT.

package advert

type UserProfileBase struct {
	UserId     int64  `thrift:"userId,1" json:"userId"`
	Gender     int32  `thrift:"gender,2" json:"gender"`
	Age        int32  `thrift:"age,3" json:"age"`
	Region     string `thrift:"region,4" json:"region"`
	DeviceType string `thrift:"deviceType,5" json:"deviceType"`
	CreateTime string `thrift:"createTime,6" json:"createTime"`
	UpdateTime string `thrift:"updateTime,7" json:"updateTime"`
}

type CreateUserProfileRequest struct {
	UserId     int64  `thrift:"userId,1" json:"userId"`
	Gender     int32  `thrift:"gender,2" json:"gender"`
	Age        int32  `thrift:"age,3" json:"age"`
	Region     string `thrift:"region,4" json:"region"`
	DeviceType string `thrift:"deviceType,5" json:"deviceType"`
}

type CreateUserProfileResponse struct {
	BaseResp *BaseResponse `thrift:"baseResp,1" json:"baseResp"`
}

type UpdateUserProfileRequest struct {
	UserId     int64   `thrift:"userId,1" json:"userId"`
	Gender     *int32  `thrift:"gender,2,optional" json:"gender,omitempty"`
	Age        *int32  `thrift:"age,3,optional" json:"age,omitempty"`
	Region     *string `thrift:"region,4,optional" json:"region,omitempty"`
	DeviceType *string `thrift:"deviceType,5,optional" json:"deviceType,omitempty"`
}

type UpdateUserProfileResponse struct {
	BaseResp *BaseResponse `thrift:"baseResp,1" json:"baseResp"`
}

type GetUserProfileRequest struct {
	UserId int64 `thrift:"userId,1" json:"userId"`
}

type GetUserProfileResponse struct {
	BaseResp    *BaseResponse    `thrift:"baseResp,1" json:"baseResp"`
	UserProfile *UserProfileBase `thrift:"userProfile,2" json:"userProfile"`
}

type DeleteUserProfileRequest struct {
	UserId int64 `thrift:"userId,1" json:"userId"`
}

type DeleteUserProfileResponse struct {
	BaseResp *BaseResponse `thrift:"baseResp,1" json:"baseResp"`
}

type UserInterest struct {
	Id         int64   `thrift:"id,1" json:"id"`
	UserId     int64   `thrift:"userId,2" json:"userId"`
	Tag        string  `thrift:"tag,3" json:"tag"`
	Weight     float64 `thrift:"weight,4" json:"weight"`
	UpdateTime string  `thrift:"updateTime,5" json:"updateTime"`
}

type AddUserInterestRequest struct {
	UserId int64   `thrift:"userId,1" json:"userId"`
	Tag    string  `thrift:"tag,2" json:"tag"`
	Weight float64 `thrift:"weight,3" json:"weight"`
}

type AddUserInterestResponse struct {
	BaseResp *BaseResponse `thrift:"baseResp,1" json:"baseResp"`
	Id       int64         `thrift:"id,2" json:"id"`
}

type UpdateUserInterestRequest struct {
	Id     int64   `thrift:"id,1" json:"id"`
	Weight float64 `thrift:"weight,2" json:"weight"`
}

type UpdateUserInterestResponse struct {
	BaseResp *BaseResponse `thrift:"baseResp,1" json:"baseResp"`
}

type GetUserInterestsRequest struct {
	UserId int64 `thrift:"userId,1" json:"userId"`
}

type GetUserInterestsResponse struct {
	BaseResp  *BaseResponse   `thrift:"baseResp,1" json:"baseResp"`
	Interests []*UserInterest `thrift:"interests,2" json:"interests"`
}

type DeleteUserInterestRequest struct {
	Id int64 `thrift:"id,1" json:"id"`
}

type DeleteUserInterestResponse struct {
	BaseResp *BaseResponse `thrift:"baseResp,1" json:"baseResp"`
}
