// Code generated by Kitex v0.16.1. DO NOT EDIT.

package userservice

import (
	"context"
	"errors"
	user "gitee.com/HeXiangdong/AdvertRecommend/user-service/kitex_gen/user"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateUserProfile": kitex.NewMethodInfo(
		createUserProfileHandler,
		newUserServiceCreateUserProfileArgs,
		newUserServiceCreateUserProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateUserProfile": kitex.NewMethodInfo(
		updateUserProfileHandler,
		newUserServiceUpdateUserProfileArgs,
		newUserServiceUpdateUserProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserProfile": kitex.NewMethodInfo(
		getUserProfileHandler,
		newUserServiceGetUserProfileArgs,
		newUserServiceGetUserProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteUserProfile": kitex.NewMethodInfo(
		deleteUserProfileHandler,
		newUserServiceDeleteUserProfileArgs,
		newUserServiceDeleteUserProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.1",
		Extra:           extra,
	}
	return svcInfo
}

func createUserProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceCreateUserProfileArgs)
	realResult := result.(*user.UserServiceCreateUserProfileResult)
	success, err := handler.(user.UserService).CreateUserProfile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceCreateUserProfileArgs() interface{} {
	return user.NewUserServiceCreateUserProfileArgs()
}

func newUserServiceCreateUserProfileResult() interface{} {
	return user.NewUserServiceCreateUserProfileResult()
}

func updateUserProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUpdateUserProfileArgs)
	realResult := result.(*user.UserServiceUpdateUserProfileResult)
	success, err := handler.(user.UserService).UpdateUserProfile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUpdateUserProfileArgs() interface{} {
	return user.NewUserServiceUpdateUserProfileArgs()
}

func newUserServiceUpdateUserProfileResult() interface{} {
	return user.NewUserServiceUpdateUserProfileResult()
}

func getUserProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetUserProfileArgs)
	realResult := result.(*user.UserServiceGetUserProfileResult)
	success, err := handler.(user.UserService).GetUserProfile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetUserProfileArgs() interface{} {
	return user.NewUserServiceGetUserProfileArgs()
}

func newUserServiceGetUserProfileResult() interface{} {
	return user.NewUserServiceGetUserProfileResult()
}

func deleteUserProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceDeleteUserProfileArgs)
	realResult := result.(*user.UserServiceDeleteUserProfileResult)
	success, err := handler.(user.UserService).DeleteUserProfile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceDeleteUserProfileArgs() interface{} {
	return user.NewUserServiceDeleteUserProfileArgs()
}

func newUserServiceDeleteUserProfileResult() interface{} {
	return user.NewUserServiceDeleteUserProfileResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateUserProfile(ctx context.Context, req *user.CreateUserProfileRequest) (r *user.CreateUserProfileResponse, err error) {
	var _args user.UserServiceCreateUserProfileArgs
	_args.Req = req
	var _result user.UserServiceCreateUserProfileResult
	if err = p.c.Call(ctx, "CreateUserProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateUserProfile(ctx context.Context, req *user.UpdateUserProfileRequest) (r *user.UpdateUserProfileResponse, err error) {
	var _args user.UserServiceUpdateUserProfileArgs
	_args.Req = req
	var _result user.UserServiceUpdateUserProfileResult
	if err = p.c.Call(ctx, "UpdateUserProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserProfile(ctx context.Context, req *user.GetUserProfileRequest) (r *user.GetUserProfileResponse, err error) {
	var _args user.UserServiceGetUserProfileArgs
	_args.Req = req
	var _result user.UserServiceGetUserProfileResult
	if err = p.c.Call(ctx, "GetUserProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteUserProfile(ctx context.Context, req *user.DeleteUserProfileRequest) (r *user.DeleteUserProfileResponse, err error) {
	var _args user.UserServiceDeleteUserProfileArgs
	_args.Req = req
	var _result user.UserServiceDeleteUserProfileResult
	if err = p.c.Call(ctx, "DeleteUserProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
