// Code generated by Kitex v0.15.2. DO NOT EDIT.

package advertservice

import (
	advert "AdvertRecommend/kitex_gen/advert"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateAdPlan": kitex.NewMethodInfo(
		createAdPlanHandler,
		newAdvertServiceCreateAdPlanArgs,
		newAdvertServiceCreateAdPlanResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateAdPlan": kitex.NewMethodInfo(
		updateAdPlanHandler,
		newAdvertServiceUpdateAdPlanArgs,
		newAdvertServiceUpdateAdPlanResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetAdPlan": kitex.NewMethodInfo(
		getAdPlanHandler,
		newAdvertServiceGetAdPlanArgs,
		newAdvertServiceGetAdPlanResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListAdPlans": kitex.NewMethodInfo(
		listAdPlansHandler,
		newAdvertServiceListAdPlansArgs,
		newAdvertServiceListAdPlansResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteAdPlan": kitex.NewMethodInfo(
		deleteAdPlanHandler,
		newAdvertServiceDeleteAdPlanArgs,
		newAdvertServiceDeleteAdPlanResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateAdCreative": kitex.NewMethodInfo(
		createAdCreativeHandler,
		newAdvertServiceCreateAdCreativeArgs,
		newAdvertServiceCreateAdCreativeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateAdCreative": kitex.NewMethodInfo(
		updateAdCreativeHandler,
		newAdvertServiceUpdateAdCreativeArgs,
		newAdvertServiceUpdateAdCreativeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetAdCreative": kitex.NewMethodInfo(
		getAdCreativeHandler,
		newAdvertServiceGetAdCreativeArgs,
		newAdvertServiceGetAdCreativeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListAdCreatives": kitex.NewMethodInfo(
		listAdCreativesHandler,
		newAdvertServiceListAdCreativesArgs,
		newAdvertServiceListAdCreativesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteAdCreative": kitex.NewMethodInfo(
		deleteAdCreativeHandler,
		newAdvertServiceDeleteAdCreativeArgs,
		newAdvertServiceDeleteAdCreativeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateUserProfile": kitex.NewMethodInfo(
		createUserProfileHandler,
		newAdvertServiceCreateUserProfileArgs,
		newAdvertServiceCreateUserProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateUserProfile": kitex.NewMethodInfo(
		updateUserProfileHandler,
		newAdvertServiceUpdateUserProfileArgs,
		newAdvertServiceUpdateUserProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserProfile": kitex.NewMethodInfo(
		getUserProfileHandler,
		newAdvertServiceGetUserProfileArgs,
		newAdvertServiceGetUserProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteUserProfile": kitex.NewMethodInfo(
		deleteUserProfileHandler,
		newAdvertServiceDeleteUserProfileArgs,
		newAdvertServiceDeleteUserProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AddUserInterest": kitex.NewMethodInfo(
		addUserInterestHandler,
		newAdvertServiceAddUserInterestArgs,
		newAdvertServiceAddUserInterestResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateUserInterest": kitex.NewMethodInfo(
		updateUserInterestHandler,
		newAdvertServiceUpdateUserInterestArgs,
		newAdvertServiceUpdateUserInterestResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserInterests": kitex.NewMethodInfo(
		getUserInterestsHandler,
		newAdvertServiceGetUserInterestsArgs,
		newAdvertServiceGetUserInterestsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteUserInterest": kitex.NewMethodInfo(
		deleteUserInterestHandler,
		newAdvertServiceDeleteUserInterestArgs,
		newAdvertServiceDeleteUserInterestResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateAdEvent": kitex.NewMethodInfo(
		createAdEventHandler,
		newAdvertServiceCreateAdEventArgs,
		newAdvertServiceCreateAdEventResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserAdEvents": kitex.NewMethodInfo(
		getUserAdEventsHandler,
		newAdvertServiceGetUserAdEventsArgs,
		newAdvertServiceGetUserAdEventsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetCreativeAdEvents": kitex.NewMethodInfo(
		getCreativeAdEventsHandler,
		newAdvertServiceGetCreativeAdEventsArgs,
		newAdvertServiceGetCreativeAdEventsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetAdvertRecommend": kitex.NewMethodInfo(
		getAdvertRecommendHandler,
		newAdvertServiceGetAdvertRecommendArgs,
		newAdvertServiceGetAdvertRecommendResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	advertServiceServiceInfo                = NewServiceInfo()
	advertServiceServiceInfoForClient       = NewServiceInfoForClient()
	advertServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return advertServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return advertServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return advertServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AdvertService"
	handlerType := (*advert.AdvertService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "advert",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func createAdPlanHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advert.AdvertServiceCreateAdPlanArgs)
	realResult := result.(*advert.AdvertServiceCreateAdPlanResult)
	success, err := handler.(advert.AdvertService).CreateAdPlan(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvertServiceCreateAdPlanArgs() interface{} {
	return advert.NewAdvertServiceCreateAdPlanArgs()
}

func newAdvertServiceCreateAdPlanResult() interface{} {
	return advert.NewAdvertServiceCreateAdPlanResult()
}

func updateAdPlanHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advert.AdvertServiceUpdateAdPlanArgs)
	realResult := result.(*advert.AdvertServiceUpdateAdPlanResult)
	success, err := handler.(advert.AdvertService).UpdateAdPlan(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvertServiceUpdateAdPlanArgs() interface{} {
	return advert.NewAdvertServiceUpdateAdPlanArgs()
}

func newAdvertServiceUpdateAdPlanResult() interface{} {
	return advert.NewAdvertServiceUpdateAdPlanResult()
}

func getAdPlanHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advert.AdvertServiceGetAdPlanArgs)
	realResult := result.(*advert.AdvertServiceGetAdPlanResult)
	success, err := handler.(advert.AdvertService).GetAdPlan(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvertServiceGetAdPlanArgs() interface{} {
	return advert.NewAdvertServiceGetAdPlanArgs()
}

func newAdvertServiceGetAdPlanResult() interface{} {
	return advert.NewAdvertServiceGetAdPlanResult()
}

func listAdPlansHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advert.AdvertServiceListAdPlansArgs)
	realResult := result.(*advert.AdvertServiceListAdPlansResult)
	success, err := handler.(advert.AdvertService).ListAdPlans(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvertServiceListAdPlansArgs() interface{} {
	return advert.NewAdvertServiceListAdPlansArgs()
}

func newAdvertServiceListAdPlansResult() interface{} {
	return advert.NewAdvertServiceListAdPlansResult()
}

func deleteAdPlanHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advert.AdvertServiceDeleteAdPlanArgs)
	realResult := result.(*advert.AdvertServiceDeleteAdPlanResult)
	success, err := handler.(advert.AdvertService).DeleteAdPlan(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvertServiceDeleteAdPlanArgs() interface{} {
	return advert.NewAdvertServiceDeleteAdPlanArgs()
}

func newAdvertServiceDeleteAdPlanResult() interface{} {
	return advert.NewAdvertServiceDeleteAdPlanResult()
}

func createAdCreativeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advert.AdvertServiceCreateAdCreativeArgs)
	realResult := result.(*advert.AdvertServiceCreateAdCreativeResult)
	success, err := handler.(advert.AdvertService).CreateAdCreative(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvertServiceCreateAdCreativeArgs() interface{} {
	return advert.NewAdvertServiceCreateAdCreativeArgs()
}

func newAdvertServiceCreateAdCreativeResult() interface{} {
	return advert.NewAdvertServiceCreateAdCreativeResult()
}

func updateAdCreativeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advert.AdvertServiceUpdateAdCreativeArgs)
	realResult := result.(*advert.AdvertServiceUpdateAdCreativeResult)
	success, err := handler.(advert.AdvertService).UpdateAdCreative(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvertServiceUpdateAdCreativeArgs() interface{} {
	return advert.NewAdvertServiceUpdateAdCreativeArgs()
}

func newAdvertServiceUpdateAdCreativeResult() interface{} {
	return advert.NewAdvertServiceUpdateAdCreativeResult()
}

func getAdCreativeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advert.AdvertServiceGetAdCreativeArgs)
	realResult := result.(*advert.AdvertServiceGetAdCreativeResult)
	success, err := handler.(advert.AdvertService).GetAdCreative(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvertServiceGetAdCreativeArgs() interface{} {
	return advert.NewAdvertServiceGetAdCreativeArgs()
}

func newAdvertServiceGetAdCreativeResult() interface{} {
	return advert.NewAdvertServiceGetAdCreativeResult()
}

func listAdCreativesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advert.AdvertServiceListAdCreativesArgs)
	realResult := result.(*advert.AdvertServiceListAdCreativesResult)
	success, err := handler.(advert.AdvertService).ListAdCreatives(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvertServiceListAdCreativesArgs() interface{} {
	return advert.NewAdvertServiceListAdCreativesArgs()
}

func newAdvertServiceListAdCreativesResult() interface{} {
	return advert.NewAdvertServiceListAdCreativesResult()
}

func deleteAdCreativeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advert.AdvertServiceDeleteAdCreativeArgs)
	realResult := result.(*advert.AdvertServiceDeleteAdCreativeResult)
	success, err := handler.(advert.AdvertService).DeleteAdCreative(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvertServiceDeleteAdCreativeArgs() interface{} {
	return advert.NewAdvertServiceDeleteAdCreativeArgs()
}

func newAdvertServiceDeleteAdCreativeResult() interface{} {
	return advert.NewAdvertServiceDeleteAdCreativeResult()
}

func createUserProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advert.AdvertServiceCreateUserProfileArgs)
	realResult := result.(*advert.AdvertServiceCreateUserProfileResult)
	success, err := handler.(advert.AdvertService).CreateUserProfile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvertServiceCreateUserProfileArgs() interface{} {
	return advert.NewAdvertServiceCreateUserProfileArgs()
}

func newAdvertServiceCreateUserProfileResult() interface{} {
	return advert.NewAdvertServiceCreateUserProfileResult()
}

func updateUserProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advert.AdvertServiceUpdateUserProfileArgs)
	realResult := result.(*advert.AdvertServiceUpdateUserProfileResult)
	success, err := handler.(advert.AdvertService).UpdateUserProfile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvertServiceUpdateUserProfileArgs() interface{} {
	return advert.NewAdvertServiceUpdateUserProfileArgs()
}

func newAdvertServiceUpdateUserProfileResult() interface{} {
	return advert.NewAdvertServiceUpdateUserProfileResult()
}

func getUserProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advert.AdvertServiceGetUserProfileArgs)
	realResult := result.(*advert.AdvertServiceGetUserProfileResult)
	success, err := handler.(advert.AdvertService).GetUserProfile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvertServiceGetUserProfileArgs() interface{} {
	return advert.NewAdvertServiceGetUserProfileArgs()
}

func newAdvertServiceGetUserProfileResult() interface{} {
	return advert.NewAdvertServiceGetUserProfileResult()
}

func deleteUserProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advert.AdvertServiceDeleteUserProfileArgs)
	realResult := result.(*advert.AdvertServiceDeleteUserProfileResult)
	success, err := handler.(advert.AdvertService).DeleteUserProfile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvertServiceDeleteUserProfileArgs() interface{} {
	return advert.NewAdvertServiceDeleteUserProfileArgs()
}

func newAdvertServiceDeleteUserProfileResult() interface{} {
	return advert.NewAdvertServiceDeleteUserProfileResult()
}

func addUserInterestHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advert.AdvertServiceAddUserInterestArgs)
	realResult := result.(*advert.AdvertServiceAddUserInterestResult)
	success, err := handler.(advert.AdvertService).AddUserInterest(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvertServiceAddUserInterestArgs() interface{} {
	return advert.NewAdvertServiceAddUserInterestArgs()
}

func newAdvertServiceAddUserInterestResult() interface{} {
	return advert.NewAdvertServiceAddUserInterestResult()
}

func updateUserInterestHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advert.AdvertServiceUpdateUserInterestArgs)
	realResult := result.(*advert.AdvertServiceUpdateUserInterestResult)
	success, err := handler.(advert.AdvertService).UpdateUserInterest(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvertServiceUpdateUserInterestArgs() interface{} {
	return advert.NewAdvertServiceUpdateUserInterestArgs()
}

func newAdvertServiceUpdateUserInterestResult() interface{} {
	return advert.NewAdvertServiceUpdateUserInterestResult()
}

func getUserInterestsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advert.AdvertServiceGetUserInterestsArgs)
	realResult := result.(*advert.AdvertServiceGetUserInterestsResult)
	success, err := handler.(advert.AdvertService).GetUserInterests(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvertServiceGetUserInterestsArgs() interface{} {
	return advert.NewAdvertServiceGetUserInterestsArgs()
}

func newAdvertServiceGetUserInterestsResult() interface{} {
	return advert.NewAdvertServiceGetUserInterestsResult()
}

func deleteUserInterestHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advert.AdvertServiceDeleteUserInterestArgs)
	realResult := result.(*advert.AdvertServiceDeleteUserInterestResult)
	success, err := handler.(advert.AdvertService).DeleteUserInterest(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvertServiceDeleteUserInterestArgs() interface{} {
	return advert.NewAdvertServiceDeleteUserInterestArgs()
}

func newAdvertServiceDeleteUserInterestResult() interface{} {
	return advert.NewAdvertServiceDeleteUserInterestResult()
}

func createAdEventHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advert.AdvertServiceCreateAdEventArgs)
	realResult := result.(*advert.AdvertServiceCreateAdEventResult)
	success, err := handler.(advert.AdvertService).CreateAdEvent(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvertServiceCreateAdEventArgs() interface{} {
	return advert.NewAdvertServiceCreateAdEventArgs()
}

func newAdvertServiceCreateAdEventResult() interface{} {
	return advert.NewAdvertServiceCreateAdEventResult()
}

func getUserAdEventsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advert.AdvertServiceGetUserAdEventsArgs)
	realResult := result.(*advert.AdvertServiceGetUserAdEventsResult)
	success, err := handler.(advert.AdvertService).GetUserAdEvents(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvertServiceGetUserAdEventsArgs() interface{} {
	return advert.NewAdvertServiceGetUserAdEventsArgs()
}

func newAdvertServiceGetUserAdEventsResult() interface{} {
	return advert.NewAdvertServiceGetUserAdEventsResult()
}

func getCreativeAdEventsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advert.AdvertServiceGetCreativeAdEventsArgs)
	realResult := result.(*advert.AdvertServiceGetCreativeAdEventsResult)
	success, err := handler.(advert.AdvertService).GetCreativeAdEvents(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvertServiceGetCreativeAdEventsArgs() interface{} {
	return advert.NewAdvertServiceGetCreativeAdEventsArgs()
}

func newAdvertServiceGetCreativeAdEventsResult() interface{} {
	return advert.NewAdvertServiceGetCreativeAdEventsResult()
}

func getAdvertRecommendHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*advert.AdvertServiceGetAdvertRecommendArgs)
	realResult := result.(*advert.AdvertServiceGetAdvertRecommendResult)
	success, err := handler.(advert.AdvertService).GetAdvertRecommend(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAdvertServiceGetAdvertRecommendArgs() interface{} {
	return advert.NewAdvertServiceGetAdvertRecommendArgs()
}

func newAdvertServiceGetAdvertRecommendResult() interface{} {
	return advert.NewAdvertServiceGetAdvertRecommendResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateAdPlan(ctx context.Context, req *advert.CreateAdPlanRequest) (r *advert.CreateAdPlanResponse, err error) {
	var _args advert.AdvertServiceCreateAdPlanArgs
	_args.Req = req
	var _result advert.AdvertServiceCreateAdPlanResult
	if err = p.c.Call(ctx, "CreateAdPlan", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateAdPlan(ctx context.Context, req *advert.UpdateAdPlanRequest) (r *advert.UpdateAdPlanResponse, err error) {
	var _args advert.AdvertServiceUpdateAdPlanArgs
	_args.Req = req
	var _result advert.AdvertServiceUpdateAdPlanResult
	if err = p.c.Call(ctx, "UpdateAdPlan", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAdPlan(ctx context.Context, req *advert.GetAdPlanRequest) (r *advert.GetAdPlanResponse, err error) {
	var _args advert.AdvertServiceGetAdPlanArgs
	_args.Req = req
	var _result advert.AdvertServiceGetAdPlanResult
	if err = p.c.Call(ctx, "GetAdPlan", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListAdPlans(ctx context.Context, req *advert.ListAdPlansRequest) (r *advert.ListAdPlansResponse, err error) {
	var _args advert.AdvertServiceListAdPlansArgs
	_args.Req = req
	var _result advert.AdvertServiceListAdPlansResult
	if err = p.c.Call(ctx, "ListAdPlans", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteAdPlan(ctx context.Context, req *advert.DeleteAdPlanRequest) (r *advert.DeleteAdPlanResponse, err error) {
	var _args advert.AdvertServiceDeleteAdPlanArgs
	_args.Req = req
	var _result advert.AdvertServiceDeleteAdPlanResult
	if err = p.c.Call(ctx, "DeleteAdPlan", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateAdCreative(ctx context.Context, req *advert.CreateAdCreativeRequest) (r *advert.CreateAdCreativeResponse, err error) {
	var _args advert.AdvertServiceCreateAdCreativeArgs
	_args.Req = req
	var _result advert.AdvertServiceCreateAdCreativeResult
	if err = p.c.Call(ctx, "CreateAdCreative", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateAdCreative(ctx context.Context, req *advert.UpdateAdCreativeRequest) (r *advert.UpdateAdCreativeResponse, err error) {
	var _args advert.AdvertServiceUpdateAdCreativeArgs
	_args.Req = req
	var _result advert.AdvertServiceUpdateAdCreativeResult
	if err = p.c.Call(ctx, "UpdateAdCreative", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAdCreative(ctx context.Context, req *advert.GetAdCreativeRequest) (r *advert.GetAdCreativeResponse, err error) {
	var _args advert.AdvertServiceGetAdCreativeArgs
	_args.Req = req
	var _result advert.AdvertServiceGetAdCreativeResult
	if err = p.c.Call(ctx, "GetAdCreative", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListAdCreatives(ctx context.Context, req *advert.ListAdCreativesRequest) (r *advert.ListAdCreativesResponse, err error) {
	var _args advert.AdvertServiceListAdCreativesArgs
	_args.Req = req
	var _result advert.AdvertServiceListAdCreativesResult
	if err = p.c.Call(ctx, "ListAdCreatives", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteAdCreative(ctx context.Context, req *advert.DeleteAdCreativeRequest) (r *advert.DeleteAdCreativeResponse, err error) {
	var _args advert.AdvertServiceDeleteAdCreativeArgs
	_args.Req = req
	var _result advert.AdvertServiceDeleteAdCreativeResult
	if err = p.c.Call(ctx, "DeleteAdCreative", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateUserProfile(ctx context.Context, req *advert.CreateUserProfileRequest) (r *advert.CreateUserProfileResponse, err error) {
	var _args advert.AdvertServiceCreateUserProfileArgs
	_args.Req = req
	var _result advert.AdvertServiceCreateUserProfileResult
	if err = p.c.Call(ctx, "CreateUserProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateUserProfile(ctx context.Context, req *advert.UpdateUserProfileRequest) (r *advert.UpdateUserProfileResponse, err error) {
	var _args advert.AdvertServiceUpdateUserProfileArgs
	_args.Req = req
	var _result advert.AdvertServiceUpdateUserProfileResult
	if err = p.c.Call(ctx, "UpdateUserProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserProfile(ctx context.Context, req *advert.GetUserProfileRequest) (r *advert.GetUserProfileResponse, err error) {
	var _args advert.AdvertServiceGetUserProfileArgs
	_args.Req = req
	var _result advert.AdvertServiceGetUserProfileResult
	if err = p.c.Call(ctx, "GetUserProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteUserProfile(ctx context.Context, req *advert.DeleteUserProfileRequest) (r *advert.DeleteUserProfileResponse, err error) {
	var _args advert.AdvertServiceDeleteUserProfileArgs
	_args.Req = req
	var _result advert.AdvertServiceDeleteUserProfileResult
	if err = p.c.Call(ctx, "DeleteUserProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AddUserInterest(ctx context.Context, req *advert.AddUserInterestRequest) (r *advert.AddUserInterestResponse, err error) {
	var _args advert.AdvertServiceAddUserInterestArgs
	_args.Req = req
	var _result advert.AdvertServiceAddUserInterestResult
	if err = p.c.Call(ctx, "AddUserInterest", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateUserInterest(ctx context.Context, req *advert.UpdateUserInterestRequest) (r *advert.UpdateUserInterestResponse, err error) {
	var _args advert.AdvertServiceUpdateUserInterestArgs
	_args.Req = req
	var _result advert.AdvertServiceUpdateUserInterestResult
	if err = p.c.Call(ctx, "UpdateUserInterest", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserInterests(ctx context.Context, req *advert.GetUserInterestsRequest) (r *advert.GetUserInterestsResponse, err error) {
	var _args advert.AdvertServiceGetUserInterestsArgs
	_args.Req = req
	var _result advert.AdvertServiceGetUserInterestsResult
	if err = p.c.Call(ctx, "GetUserInterests", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteUserInterest(ctx context.Context, req *advert.DeleteUserInterestRequest) (r *advert.DeleteUserInterestResponse, err error) {
	var _args advert.AdvertServiceDeleteUserInterestArgs
	_args.Req = req
	var _result advert.AdvertServiceDeleteUserInterestResult
	if err = p.c.Call(ctx, "DeleteUserInterest", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateAdEvent(ctx context.Context, req *advert.CreateAdEventRequest) (r *advert.CreateAdEventResponse, err error) {
	var _args advert.AdvertServiceCreateAdEventArgs
	_args.Req = req
	var _result advert.AdvertServiceCreateAdEventResult
	if err = p.c.Call(ctx, "CreateAdEvent", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserAdEvents(ctx context.Context, req *advert.GetUserAdEventsRequest) (r *advert.GetUserAdEventsResponse, err error) {
	var _args advert.AdvertServiceGetUserAdEventsArgs
	_args.Req = req
	var _result advert.AdvertServiceGetUserAdEventsResult
	if err = p.c.Call(ctx, "GetUserAdEvents", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetCreativeAdEvents(ctx context.Context, req *advert.GetCreativeAdEventsRequest) (r *advert.GetCreativeAdEventsResponse, err error) {
	var _args advert.AdvertServiceGetCreativeAdEventsArgs
	_args.Req = req
	var _result advert.AdvertServiceGetCreativeAdEventsResult
	if err = p.c.Call(ctx, "GetCreativeAdEvents", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAdvertRecommend(ctx context.Context, req *advert.GetAdvertRecommendRequest) (r *advert.GetAdvertRecommendResponse, err error) {
	var _args advert.AdvertServiceGetAdvertRecommendArgs
	_args.Req = req
	var _result advert.AdvertServiceGetAdvertRecommendResult
	if err = p.c.Call(ctx, "GetAdvertRecommend", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
