// Code generated by Kitex v0.15.2. DO NOT EDIT.

package advertservice

import (
	advert "AdvertRecommend/kitex_gen/advert"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateAdPlan(ctx context.Context, req *advert.CreateAdPlanRequest, callOptions ...callopt.Option) (r *advert.CreateAdPlanResponse, err error)
	UpdateAdPlan(ctx context.Context, req *advert.UpdateAdPlanRequest, callOptions ...callopt.Option) (r *advert.UpdateAdPlanResponse, err error)
	GetAdPlan(ctx context.Context, req *advert.GetAdPlanRequest, callOptions ...callopt.Option) (r *advert.GetAdPlanResponse, err error)
	ListAdPlans(ctx context.Context, req *advert.ListAdPlansRequest, callOptions ...callopt.Option) (r *advert.ListAdPlansResponse, err error)
	DeleteAdPlan(ctx context.Context, req *advert.DeleteAdPlanRequest, callOptions ...callopt.Option) (r *advert.DeleteAdPlanResponse, err error)
	CreateAdCreative(ctx context.Context, req *advert.CreateAdCreativeRequest, callOptions ...callopt.Option) (r *advert.CreateAdCreativeResponse, err error)
	UpdateAdCreative(ctx context.Context, req *advert.UpdateAdCreativeRequest, callOptions ...callopt.Option) (r *advert.UpdateAdCreativeResponse, err error)
	GetAdCreative(ctx context.Context, req *advert.GetAdCreativeRequest, callOptions ...callopt.Option) (r *advert.GetAdCreativeResponse, err error)
	ListAdCreatives(ctx context.Context, req *advert.ListAdCreativesRequest, callOptions ...callopt.Option) (r *advert.ListAdCreativesResponse, err error)
	DeleteAdCreative(ctx context.Context, req *advert.DeleteAdCreativeRequest, callOptions ...callopt.Option) (r *advert.DeleteAdCreativeResponse, err error)
	CreateUserProfile(ctx context.Context, req *advert.CreateUserProfileRequest, callOptions ...callopt.Option) (r *advert.CreateUserProfileResponse, err error)
	UpdateUserProfile(ctx context.Context, req *advert.UpdateUserProfileRequest, callOptions ...callopt.Option) (r *advert.UpdateUserProfileResponse, err error)
	GetUserProfile(ctx context.Context, req *advert.GetUserProfileRequest, callOptions ...callopt.Option) (r *advert.GetUserProfileResponse, err error)
	DeleteUserProfile(ctx context.Context, req *advert.DeleteUserProfileRequest, callOptions ...callopt.Option) (r *advert.DeleteUserProfileResponse, err error)
	AddUserInterest(ctx context.Context, req *advert.AddUserInterestRequest, callOptions ...callopt.Option) (r *advert.AddUserInterestResponse, err error)
	UpdateUserInterest(ctx context.Context, req *advert.UpdateUserInterestRequest, callOptions ...callopt.Option) (r *advert.UpdateUserInterestResponse, err error)
	GetUserInterests(ctx context.Context, req *advert.GetUserInterestsRequest, callOptions ...callopt.Option) (r *advert.GetUserInterestsResponse, err error)
	DeleteUserInterest(ctx context.Context, req *advert.DeleteUserInterestRequest, callOptions ...callopt.Option) (r *advert.DeleteUserInterestResponse, err error)
	CreateAdEvent(ctx context.Context, req *advert.CreateAdEventRequest, callOptions ...callopt.Option) (r *advert.CreateAdEventResponse, err error)
	GetUserAdEvents(ctx context.Context, req *advert.GetUserAdEventsRequest, callOptions ...callopt.Option) (r *advert.GetUserAdEventsResponse, err error)
	GetCreativeAdEvents(ctx context.Context, req *advert.GetCreativeAdEventsRequest, callOptions ...callopt.Option) (r *advert.GetCreativeAdEventsResponse, err error)
	GetAdvertRecommend(ctx context.Context, req *advert.GetAdvertRecommendRequest, callOptions ...callopt.Option) (r *advert.GetAdvertRecommendResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kAdvertServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAdvertServiceClient struct {
	*kClient
}

func (p *kAdvertServiceClient) CreateAdPlan(ctx context.Context, req *advert.CreateAdPlanRequest, callOptions ...callopt.Option) (r *advert.CreateAdPlanResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateAdPlan(ctx, req)
}

func (p *kAdvertServiceClient) UpdateAdPlan(ctx context.Context, req *advert.UpdateAdPlanRequest, callOptions ...callopt.Option) (r *advert.UpdateAdPlanResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateAdPlan(ctx, req)
}

func (p *kAdvertServiceClient) GetAdPlan(ctx context.Context, req *advert.GetAdPlanRequest, callOptions ...callopt.Option) (r *advert.GetAdPlanResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAdPlan(ctx, req)
}

func (p *kAdvertServiceClient) ListAdPlans(ctx context.Context, req *advert.ListAdPlansRequest, callOptions ...callopt.Option) (r *advert.ListAdPlansResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListAdPlans(ctx, req)
}

func (p *kAdvertServiceClient) DeleteAdPlan(ctx context.Context, req *advert.DeleteAdPlanRequest, callOptions ...callopt.Option) (r *advert.DeleteAdPlanResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteAdPlan(ctx, req)
}

func (p *kAdvertServiceClient) CreateAdCreative(ctx context.Context, req *advert.CreateAdCreativeRequest, callOptions ...callopt.Option) (r *advert.CreateAdCreativeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateAdCreative(ctx, req)
}

func (p *kAdvertServiceClient) UpdateAdCreative(ctx context.Context, req *advert.UpdateAdCreativeRequest, callOptions ...callopt.Option) (r *advert.UpdateAdCreativeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateAdCreative(ctx, req)
}

func (p *kAdvertServiceClient) GetAdCreative(ctx context.Context, req *advert.GetAdCreativeRequest, callOptions ...callopt.Option) (r *advert.GetAdCreativeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAdCreative(ctx, req)
}

func (p *kAdvertServiceClient) ListAdCreatives(ctx context.Context, req *advert.ListAdCreativesRequest, callOptions ...callopt.Option) (r *advert.ListAdCreativesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListAdCreatives(ctx, req)
}

func (p *kAdvertServiceClient) DeleteAdCreative(ctx context.Context, req *advert.DeleteAdCreativeRequest, callOptions ...callopt.Option) (r *advert.DeleteAdCreativeResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteAdCreative(ctx, req)
}

func (p *kAdvertServiceClient) CreateUserProfile(ctx context.Context, req *advert.CreateUserProfileRequest, callOptions ...callopt.Option) (r *advert.CreateUserProfileResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateUserProfile(ctx, req)
}

func (p *kAdvertServiceClient) UpdateUserProfile(ctx context.Context, req *advert.UpdateUserProfileRequest, callOptions ...callopt.Option) (r *advert.UpdateUserProfileResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUserProfile(ctx, req)
}

func (p *kAdvertServiceClient) GetUserProfile(ctx context.Context, req *advert.GetUserProfileRequest, callOptions ...callopt.Option) (r *advert.GetUserProfileResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserProfile(ctx, req)
}

func (p *kAdvertServiceClient) DeleteUserProfile(ctx context.Context, req *advert.DeleteUserProfileRequest, callOptions ...callopt.Option) (r *advert.DeleteUserProfileResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteUserProfile(ctx, req)
}

func (p *kAdvertServiceClient) AddUserInterest(ctx context.Context, req *advert.AddUserInterestRequest, callOptions ...callopt.Option) (r *advert.AddUserInterestResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddUserInterest(ctx, req)
}

func (p *kAdvertServiceClient) UpdateUserInterest(ctx context.Context, req *advert.UpdateUserInterestRequest, callOptions ...callopt.Option) (r *advert.UpdateUserInterestResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUserInterest(ctx, req)
}

func (p *kAdvertServiceClient) GetUserInterests(ctx context.Context, req *advert.GetUserInterestsRequest, callOptions ...callopt.Option) (r *advert.GetUserInterestsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserInterests(ctx, req)
}

func (p *kAdvertServiceClient) DeleteUserInterest(ctx context.Context, req *advert.DeleteUserInterestRequest, callOptions ...callopt.Option) (r *advert.DeleteUserInterestResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteUserInterest(ctx, req)
}

func (p *kAdvertServiceClient) CreateAdEvent(ctx context.Context, req *advert.CreateAdEventRequest, callOptions ...callopt.Option) (r *advert.CreateAdEventResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateAdEvent(ctx, req)
}

func (p *kAdvertServiceClient) GetUserAdEvents(ctx context.Context, req *advert.GetUserAdEventsRequest, callOptions ...callopt.Option) (r *advert.GetUserAdEventsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserAdEvents(ctx, req)
}

func (p *kAdvertServiceClient) GetCreativeAdEvents(ctx context.Context, req *advert.GetCreativeAdEventsRequest, callOptions ...callopt.Option) (r *advert.GetCreativeAdEventsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetCreativeAdEvents(ctx, req)
}

func (p *kAdvertServiceClient) GetAdvertRecommend(ctx context.Context, req *advert.GetAdvertRecommendRequest, callOptions ...callopt.Option) (r *advert.GetAdvertRecommendResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAdvertRecommend(ctx, req)
}
