// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package user

import (
	"context"
	"fmt"
	"gitee.com/HeXiangdong/AdvertRecommend/recommend-service/kitex_gen/common"
)

type UserProfileBase struct {
	UserId     int64  `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	Gender     int32  `thrift:"gender,2" frugal:"2,default,i32" json:"gender"`
	Age        int32  `thrift:"age,3" frugal:"3,default,i32" json:"age"`
	Region     string `thrift:"region,4" frugal:"4,default,string" json:"region"`
	DeviceType string `thrift:"deviceType,5" frugal:"5,default,string" json:"deviceType"`
	CreateTime string `thrift:"createTime,6" frugal:"6,default,string" json:"createTime"`
	UpdateTime string `thrift:"updateTime,7" frugal:"7,default,string" json:"updateTime"`
}

func NewUserProfileBase() *UserProfileBase {
	return &UserProfileBase{}
}

func (p *UserProfileBase) InitDefault() {
}

func (p *UserProfileBase) GetUserId() (v int64) {
	return p.UserId
}

func (p *UserProfileBase) GetGender() (v int32) {
	return p.Gender
}

func (p *UserProfileBase) GetAge() (v int32) {
	return p.Age
}

func (p *UserProfileBase) GetRegion() (v string) {
	return p.Region
}

func (p *UserProfileBase) GetDeviceType() (v string) {
	return p.DeviceType
}

func (p *UserProfileBase) GetCreateTime() (v string) {
	return p.CreateTime
}

func (p *UserProfileBase) GetUpdateTime() (v string) {
	return p.UpdateTime
}
func (p *UserProfileBase) SetUserId(val int64) {
	p.UserId = val
}
func (p *UserProfileBase) SetGender(val int32) {
	p.Gender = val
}
func (p *UserProfileBase) SetAge(val int32) {
	p.Age = val
}
func (p *UserProfileBase) SetRegion(val string) {
	p.Region = val
}
func (p *UserProfileBase) SetDeviceType(val string) {
	p.DeviceType = val
}
func (p *UserProfileBase) SetCreateTime(val string) {
	p.CreateTime = val
}
func (p *UserProfileBase) SetUpdateTime(val string) {
	p.UpdateTime = val
}

func (p *UserProfileBase) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserProfileBase(%+v)", *p)
}

var fieldIDToName_UserProfileBase = map[int16]string{
	1: "userId",
	2: "gender",
	3: "age",
	4: "region",
	5: "deviceType",
	6: "createTime",
	7: "updateTime",
}

type GetUserProfileRequest struct {
	UserId int64 `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
}

func NewGetUserProfileRequest() *GetUserProfileRequest {
	return &GetUserProfileRequest{}
}

func (p *GetUserProfileRequest) InitDefault() {
}

func (p *GetUserProfileRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetUserProfileRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetUserProfileRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserProfileRequest(%+v)", *p)
}

var fieldIDToName_GetUserProfileRequest = map[int16]string{
	1: "userId",
}

type GetUserProfileResponse struct {
	BaseResp    *common.BaseResponse `thrift:"baseResp,1" frugal:"1,default,common.BaseResponse" json:"baseResp"`
	UserProfile *UserProfileBase     `thrift:"userProfile,2" frugal:"2,default,UserProfileBase" json:"userProfile"`
}

func NewGetUserProfileResponse() *GetUserProfileResponse {
	return &GetUserProfileResponse{}
}

func (p *GetUserProfileResponse) InitDefault() {
}

var GetUserProfileResponse_BaseResp_DEFAULT *common.BaseResponse

func (p *GetUserProfileResponse) GetBaseResp() (v *common.BaseResponse) {
	if !p.IsSetBaseResp() {
		return GetUserProfileResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var GetUserProfileResponse_UserProfile_DEFAULT *UserProfileBase

func (p *GetUserProfileResponse) GetUserProfile() (v *UserProfileBase) {
	if !p.IsSetUserProfile() {
		return GetUserProfileResponse_UserProfile_DEFAULT
	}
	return p.UserProfile
}
func (p *GetUserProfileResponse) SetBaseResp(val *common.BaseResponse) {
	p.BaseResp = val
}
func (p *GetUserProfileResponse) SetUserProfile(val *UserProfileBase) {
	p.UserProfile = val
}

func (p *GetUserProfileResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetUserProfileResponse) IsSetUserProfile() bool {
	return p.UserProfile != nil
}

func (p *GetUserProfileResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserProfileResponse(%+v)", *p)
}

var fieldIDToName_GetUserProfileResponse = map[int16]string{
	1: "baseResp",
	2: "userProfile",
}

type UserService interface {
	GetUserProfile(ctx context.Context, req *GetUserProfileRequest) (r *GetUserProfileResponse, err error)
}

type UserServiceGetUserProfileArgs struct {
	Req *GetUserProfileRequest `thrift:"req,1" frugal:"1,default,GetUserProfileRequest" json:"req"`
}

func NewUserServiceGetUserProfileArgs() *UserServiceGetUserProfileArgs {
	return &UserServiceGetUserProfileArgs{}
}

func (p *UserServiceGetUserProfileArgs) InitDefault() {
}

var UserServiceGetUserProfileArgs_Req_DEFAULT *GetUserProfileRequest

func (p *UserServiceGetUserProfileArgs) GetReq() (v *GetUserProfileRequest) {
	if !p.IsSetReq() {
		return UserServiceGetUserProfileArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetUserProfileArgs) SetReq(val *GetUserProfileRequest) {
	p.Req = val
}

func (p *UserServiceGetUserProfileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetUserProfileArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserProfileArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserProfileArgs = map[int16]string{
	1: "req",
}

type UserServiceGetUserProfileResult struct {
	Success *GetUserProfileResponse `thrift:"success,0,optional" frugal:"0,optional,GetUserProfileResponse" json:"success,omitempty"`
}

func NewUserServiceGetUserProfileResult() *UserServiceGetUserProfileResult {
	return &UserServiceGetUserProfileResult{}
}

func (p *UserServiceGetUserProfileResult) InitDefault() {
}

var UserServiceGetUserProfileResult_Success_DEFAULT *GetUserProfileResponse

func (p *UserServiceGetUserProfileResult) GetSuccess() (v *GetUserProfileResponse) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserProfileResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserProfileResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserProfileResponse)
}

func (p *UserServiceGetUserProfileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserProfileResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserProfileResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserProfileResult = map[int16]string{
	0: "success",
}
