// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package recommend

import (
	"context"
	"fmt"
	"gitee.com/HeXiangdong/AdvertRecommend/recommend-service/kitex_gen/common"
)

type AdPlan struct {
	PlanId        int64   `thrift:"planId,1" frugal:"1,default,i64" json:"planId"`
	Name          string  `thrift:"name,2" frugal:"2,default,string" json:"name"`
	Objective     string  `thrift:"objective,3" frugal:"3,default,string" json:"objective"`
	Budget        float64 `thrift:"budget,4" frugal:"4,default,double" json:"budget"`
	BidPrice      string  `thrift:"bidPrice,5" frugal:"5,default,string" json:"bidPrice"`
	TargetingRule string  `thrift:"targetingRule,6" frugal:"6,default,string" json:"targetingRule"`
	StartTime     string  `thrift:"startTime,7" frugal:"7,default,string" json:"startTime"`
	EndTime       string  `thrift:"endTime,8" frugal:"8,default,string" json:"endTime"`
	Status        int32   `thrift:"status,9" frugal:"9,default,i32" json:"status"`
	CreateTime    string  `thrift:"createTime,10" frugal:"10,default,string" json:"createTime"`
	UpdateTime    string  `thrift:"updateTime,11" frugal:"11,default,string" json:"updateTime"`
}

func NewAdPlan() *AdPlan {
	return &AdPlan{}
}

func (p *AdPlan) InitDefault() {
}

func (p *AdPlan) GetPlanId() (v int64) {
	return p.PlanId
}

func (p *AdPlan) GetName() (v string) {
	return p.Name
}

func (p *AdPlan) GetObjective() (v string) {
	return p.Objective
}

func (p *AdPlan) GetBudget() (v float64) {
	return p.Budget
}

func (p *AdPlan) GetBidPrice() (v string) {
	return p.BidPrice
}

func (p *AdPlan) GetTargetingRule() (v string) {
	return p.TargetingRule
}

func (p *AdPlan) GetStartTime() (v string) {
	return p.StartTime
}

func (p *AdPlan) GetEndTime() (v string) {
	return p.EndTime
}

func (p *AdPlan) GetStatus() (v int32) {
	return p.Status
}

func (p *AdPlan) GetCreateTime() (v string) {
	return p.CreateTime
}

func (p *AdPlan) GetUpdateTime() (v string) {
	return p.UpdateTime
}
func (p *AdPlan) SetPlanId(val int64) {
	p.PlanId = val
}
func (p *AdPlan) SetName(val string) {
	p.Name = val
}
func (p *AdPlan) SetObjective(val string) {
	p.Objective = val
}
func (p *AdPlan) SetBudget(val float64) {
	p.Budget = val
}
func (p *AdPlan) SetBidPrice(val string) {
	p.BidPrice = val
}
func (p *AdPlan) SetTargetingRule(val string) {
	p.TargetingRule = val
}
func (p *AdPlan) SetStartTime(val string) {
	p.StartTime = val
}
func (p *AdPlan) SetEndTime(val string) {
	p.EndTime = val
}
func (p *AdPlan) SetStatus(val int32) {
	p.Status = val
}
func (p *AdPlan) SetCreateTime(val string) {
	p.CreateTime = val
}
func (p *AdPlan) SetUpdateTime(val string) {
	p.UpdateTime = val
}

func (p *AdPlan) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdPlan(%+v)", *p)
}

var fieldIDToName_AdPlan = map[int16]string{
	1:  "planId",
	2:  "name",
	3:  "objective",
	4:  "budget",
	5:  "bidPrice",
	6:  "targetingRule",
	7:  "startTime",
	8:  "endTime",
	9:  "status",
	10: "createTime",
	11: "updateTime",
}

type CreateAdPlanRequest struct {
	Name          string  `thrift:"name,1" frugal:"1,default,string" json:"name"`
	Objective     string  `thrift:"objective,2" frugal:"2,default,string" json:"objective"`
	Budget        float64 `thrift:"budget,3" frugal:"3,default,double" json:"budget"`
	BidPrice      string  `thrift:"bidPrice,4" frugal:"4,default,string" json:"bidPrice"`
	TargetingRule string  `thrift:"targetingRule,5" frugal:"5,default,string" json:"targetingRule"`
	StartTime     string  `thrift:"startTime,6" frugal:"6,default,string" json:"startTime"`
	EndTime       string  `thrift:"endTime,7" frugal:"7,default,string" json:"endTime"`
}

func NewCreateAdPlanRequest() *CreateAdPlanRequest {
	return &CreateAdPlanRequest{}
}

func (p *CreateAdPlanRequest) InitDefault() {
}

func (p *CreateAdPlanRequest) GetName() (v string) {
	return p.Name
}

func (p *CreateAdPlanRequest) GetObjective() (v string) {
	return p.Objective
}

func (p *CreateAdPlanRequest) GetBudget() (v float64) {
	return p.Budget
}

func (p *CreateAdPlanRequest) GetBidPrice() (v string) {
	return p.BidPrice
}

func (p *CreateAdPlanRequest) GetTargetingRule() (v string) {
	return p.TargetingRule
}

func (p *CreateAdPlanRequest) GetStartTime() (v string) {
	return p.StartTime
}

func (p *CreateAdPlanRequest) GetEndTime() (v string) {
	return p.EndTime
}
func (p *CreateAdPlanRequest) SetName(val string) {
	p.Name = val
}
func (p *CreateAdPlanRequest) SetObjective(val string) {
	p.Objective = val
}
func (p *CreateAdPlanRequest) SetBudget(val float64) {
	p.Budget = val
}
func (p *CreateAdPlanRequest) SetBidPrice(val string) {
	p.BidPrice = val
}
func (p *CreateAdPlanRequest) SetTargetingRule(val string) {
	p.TargetingRule = val
}
func (p *CreateAdPlanRequest) SetStartTime(val string) {
	p.StartTime = val
}
func (p *CreateAdPlanRequest) SetEndTime(val string) {
	p.EndTime = val
}

func (p *CreateAdPlanRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateAdPlanRequest(%+v)", *p)
}

var fieldIDToName_CreateAdPlanRequest = map[int16]string{
	1: "name",
	2: "objective",
	3: "budget",
	4: "bidPrice",
	5: "targetingRule",
	6: "startTime",
	7: "endTime",
}

type CreateAdPlanResponse struct {
	BaseResp *common.BaseResponse `thrift:"baseResp,1" frugal:"1,default,common.BaseResponse" json:"baseResp"`
	PlanId   int64                `thrift:"planId,2" frugal:"2,default,i64" json:"planId"`
}

func NewCreateAdPlanResponse() *CreateAdPlanResponse {
	return &CreateAdPlanResponse{}
}

func (p *CreateAdPlanResponse) InitDefault() {
}

var CreateAdPlanResponse_BaseResp_DEFAULT *common.BaseResponse

func (p *CreateAdPlanResponse) GetBaseResp() (v *common.BaseResponse) {
	if !p.IsSetBaseResp() {
		return CreateAdPlanResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *CreateAdPlanResponse) GetPlanId() (v int64) {
	return p.PlanId
}
func (p *CreateAdPlanResponse) SetBaseResp(val *common.BaseResponse) {
	p.BaseResp = val
}
func (p *CreateAdPlanResponse) SetPlanId(val int64) {
	p.PlanId = val
}

func (p *CreateAdPlanResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CreateAdPlanResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateAdPlanResponse(%+v)", *p)
}

var fieldIDToName_CreateAdPlanResponse = map[int16]string{
	1: "baseResp",
	2: "planId",
}

type UpdateAdPlanRequest struct {
	PlanId        int64    `thrift:"planId,1" frugal:"1,default,i64" json:"planId"`
	Name          *string  `thrift:"name,2,optional" frugal:"2,optional,string" json:"name,omitempty"`
	Objective     *string  `thrift:"objective,3,optional" frugal:"3,optional,string" json:"objective,omitempty"`
	Budget        *float64 `thrift:"budget,4,optional" frugal:"4,optional,double" json:"budget,omitempty"`
	BidPrice      *string  `thrift:"bidPrice,5,optional" frugal:"5,optional,string" json:"bidPrice,omitempty"`
	TargetingRule *string  `thrift:"targetingRule,6,optional" frugal:"6,optional,string" json:"targetingRule,omitempty"`
	StartTime     *string  `thrift:"startTime,7,optional" frugal:"7,optional,string" json:"startTime,omitempty"`
	EndTime       *string  `thrift:"endTime,8,optional" frugal:"8,optional,string" json:"endTime,omitempty"`
	Status        *int32   `thrift:"status,9,optional" frugal:"9,optional,i32" json:"status,omitempty"`
}

func NewUpdateAdPlanRequest() *UpdateAdPlanRequest {
	return &UpdateAdPlanRequest{}
}

func (p *UpdateAdPlanRequest) InitDefault() {
}

func (p *UpdateAdPlanRequest) GetPlanId() (v int64) {
	return p.PlanId
}

var UpdateAdPlanRequest_Name_DEFAULT string

func (p *UpdateAdPlanRequest) GetName() (v string) {
	if !p.IsSetName() {
		return UpdateAdPlanRequest_Name_DEFAULT
	}
	return *p.Name
}

var UpdateAdPlanRequest_Objective_DEFAULT string

func (p *UpdateAdPlanRequest) GetObjective() (v string) {
	if !p.IsSetObjective() {
		return UpdateAdPlanRequest_Objective_DEFAULT
	}
	return *p.Objective
}

var UpdateAdPlanRequest_Budget_DEFAULT float64

func (p *UpdateAdPlanRequest) GetBudget() (v float64) {
	if !p.IsSetBudget() {
		return UpdateAdPlanRequest_Budget_DEFAULT
	}
	return *p.Budget
}

var UpdateAdPlanRequest_BidPrice_DEFAULT string

func (p *UpdateAdPlanRequest) GetBidPrice() (v string) {
	if !p.IsSetBidPrice() {
		return UpdateAdPlanRequest_BidPrice_DEFAULT
	}
	return *p.BidPrice
}

var UpdateAdPlanRequest_TargetingRule_DEFAULT string

func (p *UpdateAdPlanRequest) GetTargetingRule() (v string) {
	if !p.IsSetTargetingRule() {
		return UpdateAdPlanRequest_TargetingRule_DEFAULT
	}
	return *p.TargetingRule
}

var UpdateAdPlanRequest_StartTime_DEFAULT string

func (p *UpdateAdPlanRequest) GetStartTime() (v string) {
	if !p.IsSetStartTime() {
		return UpdateAdPlanRequest_StartTime_DEFAULT
	}
	return *p.StartTime
}

var UpdateAdPlanRequest_EndTime_DEFAULT string

func (p *UpdateAdPlanRequest) GetEndTime() (v string) {
	if !p.IsSetEndTime() {
		return UpdateAdPlanRequest_EndTime_DEFAULT
	}
	return *p.EndTime
}

var UpdateAdPlanRequest_Status_DEFAULT int32

func (p *UpdateAdPlanRequest) GetStatus() (v int32) {
	if !p.IsSetStatus() {
		return UpdateAdPlanRequest_Status_DEFAULT
	}
	return *p.Status
}
func (p *UpdateAdPlanRequest) SetPlanId(val int64) {
	p.PlanId = val
}
func (p *UpdateAdPlanRequest) SetName(val *string) {
	p.Name = val
}
func (p *UpdateAdPlanRequest) SetObjective(val *string) {
	p.Objective = val
}
func (p *UpdateAdPlanRequest) SetBudget(val *float64) {
	p.Budget = val
}
func (p *UpdateAdPlanRequest) SetBidPrice(val *string) {
	p.BidPrice = val
}
func (p *UpdateAdPlanRequest) SetTargetingRule(val *string) {
	p.TargetingRule = val
}
func (p *UpdateAdPlanRequest) SetStartTime(val *string) {
	p.StartTime = val
}
func (p *UpdateAdPlanRequest) SetEndTime(val *string) {
	p.EndTime = val
}
func (p *UpdateAdPlanRequest) SetStatus(val *int32) {
	p.Status = val
}

func (p *UpdateAdPlanRequest) IsSetName() bool {
	return p.Name != nil
}

func (p *UpdateAdPlanRequest) IsSetObjective() bool {
	return p.Objective != nil
}

func (p *UpdateAdPlanRequest) IsSetBudget() bool {
	return p.Budget != nil
}

func (p *UpdateAdPlanRequest) IsSetBidPrice() bool {
	return p.BidPrice != nil
}

func (p *UpdateAdPlanRequest) IsSetTargetingRule() bool {
	return p.TargetingRule != nil
}

func (p *UpdateAdPlanRequest) IsSetStartTime() bool {
	return p.StartTime != nil
}

func (p *UpdateAdPlanRequest) IsSetEndTime() bool {
	return p.EndTime != nil
}

func (p *UpdateAdPlanRequest) IsSetStatus() bool {
	return p.Status != nil
}

func (p *UpdateAdPlanRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateAdPlanRequest(%+v)", *p)
}

var fieldIDToName_UpdateAdPlanRequest = map[int16]string{
	1: "planId",
	2: "name",
	3: "objective",
	4: "budget",
	5: "bidPrice",
	6: "targetingRule",
	7: "startTime",
	8: "endTime",
	9: "status",
}

type UpdateAdPlanResponse struct {
	BaseResp *common.BaseResponse `thrift:"baseResp,1" frugal:"1,default,common.BaseResponse" json:"baseResp"`
}

func NewUpdateAdPlanResponse() *UpdateAdPlanResponse {
	return &UpdateAdPlanResponse{}
}

func (p *UpdateAdPlanResponse) InitDefault() {
}

var UpdateAdPlanResponse_BaseResp_DEFAULT *common.BaseResponse

func (p *UpdateAdPlanResponse) GetBaseResp() (v *common.BaseResponse) {
	if !p.IsSetBaseResp() {
		return UpdateAdPlanResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *UpdateAdPlanResponse) SetBaseResp(val *common.BaseResponse) {
	p.BaseResp = val
}

func (p *UpdateAdPlanResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UpdateAdPlanResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateAdPlanResponse(%+v)", *p)
}

var fieldIDToName_UpdateAdPlanResponse = map[int16]string{
	1: "baseResp",
}

type GetAdPlanRequest struct {
	PlanId int64 `thrift:"planId,1" frugal:"1,default,i64" json:"planId"`
}

func NewGetAdPlanRequest() *GetAdPlanRequest {
	return &GetAdPlanRequest{}
}

func (p *GetAdPlanRequest) InitDefault() {
}

func (p *GetAdPlanRequest) GetPlanId() (v int64) {
	return p.PlanId
}
func (p *GetAdPlanRequest) SetPlanId(val int64) {
	p.PlanId = val
}

func (p *GetAdPlanRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAdPlanRequest(%+v)", *p)
}

var fieldIDToName_GetAdPlanRequest = map[int16]string{
	1: "planId",
}

type GetAdPlanResponse struct {
	BaseResp *common.BaseResponse `thrift:"baseResp,1" frugal:"1,default,common.BaseResponse" json:"baseResp"`
	AdPlan   *AdPlan              `thrift:"adPlan,2" frugal:"2,default,AdPlan" json:"adPlan"`
}

func NewGetAdPlanResponse() *GetAdPlanResponse {
	return &GetAdPlanResponse{}
}

func (p *GetAdPlanResponse) InitDefault() {
}

var GetAdPlanResponse_BaseResp_DEFAULT *common.BaseResponse

func (p *GetAdPlanResponse) GetBaseResp() (v *common.BaseResponse) {
	if !p.IsSetBaseResp() {
		return GetAdPlanResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var GetAdPlanResponse_AdPlan_DEFAULT *AdPlan

func (p *GetAdPlanResponse) GetAdPlan() (v *AdPlan) {
	if !p.IsSetAdPlan() {
		return GetAdPlanResponse_AdPlan_DEFAULT
	}
	return p.AdPlan
}
func (p *GetAdPlanResponse) SetBaseResp(val *common.BaseResponse) {
	p.BaseResp = val
}
func (p *GetAdPlanResponse) SetAdPlan(val *AdPlan) {
	p.AdPlan = val
}

func (p *GetAdPlanResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetAdPlanResponse) IsSetAdPlan() bool {
	return p.AdPlan != nil
}

func (p *GetAdPlanResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAdPlanResponse(%+v)", *p)
}

var fieldIDToName_GetAdPlanResponse = map[int16]string{
	1: "baseResp",
	2: "adPlan",
}

type ListAdPlansRequest struct {
	Page     int32  `thrift:"page,1" frugal:"1,default,i32" json:"page"`
	PageSize int32  `thrift:"pageSize,2" frugal:"2,default,i32" json:"pageSize"`
	Status   *int32 `thrift:"status,3,optional" frugal:"3,optional,i32" json:"status,omitempty"`
}

func NewListAdPlansRequest() *ListAdPlansRequest {
	return &ListAdPlansRequest{}
}

func (p *ListAdPlansRequest) InitDefault() {
}

func (p *ListAdPlansRequest) GetPage() (v int32) {
	return p.Page
}

func (p *ListAdPlansRequest) GetPageSize() (v int32) {
	return p.PageSize
}

var ListAdPlansRequest_Status_DEFAULT int32

func (p *ListAdPlansRequest) GetStatus() (v int32) {
	if !p.IsSetStatus() {
		return ListAdPlansRequest_Status_DEFAULT
	}
	return *p.Status
}
func (p *ListAdPlansRequest) SetPage(val int32) {
	p.Page = val
}
func (p *ListAdPlansRequest) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *ListAdPlansRequest) SetStatus(val *int32) {
	p.Status = val
}

func (p *ListAdPlansRequest) IsSetStatus() bool {
	return p.Status != nil
}

func (p *ListAdPlansRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListAdPlansRequest(%+v)", *p)
}

var fieldIDToName_ListAdPlansRequest = map[int16]string{
	1: "page",
	2: "pageSize",
	3: "status",
}

type ListAdPlansResponse struct {
	BaseResp *common.BaseResponse `thrift:"baseResp,1" frugal:"1,default,common.BaseResponse" json:"baseResp"`
	AdPlans  []*AdPlan            `thrift:"adPlans,2" frugal:"2,default,list<AdPlan>" json:"adPlans"`
	Total    int64                `thrift:"total,3" frugal:"3,default,i64" json:"total"`
}

func NewListAdPlansResponse() *ListAdPlansResponse {
	return &ListAdPlansResponse{}
}

func (p *ListAdPlansResponse) InitDefault() {
}

var ListAdPlansResponse_BaseResp_DEFAULT *common.BaseResponse

func (p *ListAdPlansResponse) GetBaseResp() (v *common.BaseResponse) {
	if !p.IsSetBaseResp() {
		return ListAdPlansResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *ListAdPlansResponse) GetAdPlans() (v []*AdPlan) {
	return p.AdPlans
}

func (p *ListAdPlansResponse) GetTotal() (v int64) {
	return p.Total
}
func (p *ListAdPlansResponse) SetBaseResp(val *common.BaseResponse) {
	p.BaseResp = val
}
func (p *ListAdPlansResponse) SetAdPlans(val []*AdPlan) {
	p.AdPlans = val
}
func (p *ListAdPlansResponse) SetTotal(val int64) {
	p.Total = val
}

func (p *ListAdPlansResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ListAdPlansResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListAdPlansResponse(%+v)", *p)
}

var fieldIDToName_ListAdPlansResponse = map[int16]string{
	1: "baseResp",
	2: "adPlans",
	3: "total",
}

type DeleteAdPlanRequest struct {
	PlanId int64 `thrift:"planId,1" frugal:"1,default,i64" json:"planId"`
}

func NewDeleteAdPlanRequest() *DeleteAdPlanRequest {
	return &DeleteAdPlanRequest{}
}

func (p *DeleteAdPlanRequest) InitDefault() {
}

func (p *DeleteAdPlanRequest) GetPlanId() (v int64) {
	return p.PlanId
}
func (p *DeleteAdPlanRequest) SetPlanId(val int64) {
	p.PlanId = val
}

func (p *DeleteAdPlanRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteAdPlanRequest(%+v)", *p)
}

var fieldIDToName_DeleteAdPlanRequest = map[int16]string{
	1: "planId",
}

type DeleteAdPlanResponse struct {
	BaseResp *common.BaseResponse `thrift:"baseResp,1" frugal:"1,default,common.BaseResponse" json:"baseResp"`
}

func NewDeleteAdPlanResponse() *DeleteAdPlanResponse {
	return &DeleteAdPlanResponse{}
}

func (p *DeleteAdPlanResponse) InitDefault() {
}

var DeleteAdPlanResponse_BaseResp_DEFAULT *common.BaseResponse

func (p *DeleteAdPlanResponse) GetBaseResp() (v *common.BaseResponse) {
	if !p.IsSetBaseResp() {
		return DeleteAdPlanResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *DeleteAdPlanResponse) SetBaseResp(val *common.BaseResponse) {
	p.BaseResp = val
}

func (p *DeleteAdPlanResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *DeleteAdPlanResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteAdPlanResponse(%+v)", *p)
}

var fieldIDToName_DeleteAdPlanResponse = map[int16]string{
	1: "baseResp",
}

type AdCreative struct {
	CreativeId   int64   `thrift:"creativeId,1" frugal:"1,default,i64" json:"creativeId"`
	PlanId       int64   `thrift:"planId,2" frugal:"2,default,i64" json:"planId"`
	CreativeType int32   `thrift:"creativeType,3" frugal:"3,default,i32" json:"creativeType"`
	MediaUrl     string  `thrift:"mediaUrl,4" frugal:"4,default,string" json:"mediaUrl"`
	Title        string  `thrift:"title,5" frugal:"5,default,string" json:"title"`
	Description  string  `thrift:"description,6" frugal:"6,default,string" json:"description"`
	Status       int32   `thrift:"status,7" frugal:"7,default,i32" json:"status"`
	CreateTime   string  `thrift:"createTime,8" frugal:"8,default,string" json:"createTime"`
	UpdateTime   string  `thrift:"updateTime,9" frugal:"9,default,string" json:"updateTime"`
	Weight       float64 `thrift:"weight,10" frugal:"10,default,double" json:"weight"`
}

func NewAdCreative() *AdCreative {
	return &AdCreative{}
}

func (p *AdCreative) InitDefault() {
}

func (p *AdCreative) GetCreativeId() (v int64) {
	return p.CreativeId
}

func (p *AdCreative) GetPlanId() (v int64) {
	return p.PlanId
}

func (p *AdCreative) GetCreativeType() (v int32) {
	return p.CreativeType
}

func (p *AdCreative) GetMediaUrl() (v string) {
	return p.MediaUrl
}

func (p *AdCreative) GetTitle() (v string) {
	return p.Title
}

func (p *AdCreative) GetDescription() (v string) {
	return p.Description
}

func (p *AdCreative) GetStatus() (v int32) {
	return p.Status
}

func (p *AdCreative) GetCreateTime() (v string) {
	return p.CreateTime
}

func (p *AdCreative) GetUpdateTime() (v string) {
	return p.UpdateTime
}

func (p *AdCreative) GetWeight() (v float64) {
	return p.Weight
}
func (p *AdCreative) SetCreativeId(val int64) {
	p.CreativeId = val
}
func (p *AdCreative) SetPlanId(val int64) {
	p.PlanId = val
}
func (p *AdCreative) SetCreativeType(val int32) {
	p.CreativeType = val
}
func (p *AdCreative) SetMediaUrl(val string) {
	p.MediaUrl = val
}
func (p *AdCreative) SetTitle(val string) {
	p.Title = val
}
func (p *AdCreative) SetDescription(val string) {
	p.Description = val
}
func (p *AdCreative) SetStatus(val int32) {
	p.Status = val
}
func (p *AdCreative) SetCreateTime(val string) {
	p.CreateTime = val
}
func (p *AdCreative) SetUpdateTime(val string) {
	p.UpdateTime = val
}
func (p *AdCreative) SetWeight(val float64) {
	p.Weight = val
}

func (p *AdCreative) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdCreative(%+v)", *p)
}

var fieldIDToName_AdCreative = map[int16]string{
	1:  "creativeId",
	2:  "planId",
	3:  "creativeType",
	4:  "mediaUrl",
	5:  "title",
	6:  "description",
	7:  "status",
	8:  "createTime",
	9:  "updateTime",
	10: "weight",
}

type CreateAdCreativeRequest struct {
	PlanId       int64  `thrift:"planId,1" frugal:"1,default,i64" json:"planId"`
	CreativeType int32  `thrift:"creativeType,2" frugal:"2,default,i32" json:"creativeType"`
	MediaUrl     string `thrift:"mediaUrl,3" frugal:"3,default,string" json:"mediaUrl"`
	Title        string `thrift:"title,4" frugal:"4,default,string" json:"title"`
	Description  string `thrift:"description,5" frugal:"5,default,string" json:"description"`
}

func NewCreateAdCreativeRequest() *CreateAdCreativeRequest {
	return &CreateAdCreativeRequest{}
}

func (p *CreateAdCreativeRequest) InitDefault() {
}

func (p *CreateAdCreativeRequest) GetPlanId() (v int64) {
	return p.PlanId
}

func (p *CreateAdCreativeRequest) GetCreativeType() (v int32) {
	return p.CreativeType
}

func (p *CreateAdCreativeRequest) GetMediaUrl() (v string) {
	return p.MediaUrl
}

func (p *CreateAdCreativeRequest) GetTitle() (v string) {
	return p.Title
}

func (p *CreateAdCreativeRequest) GetDescription() (v string) {
	return p.Description
}
func (p *CreateAdCreativeRequest) SetPlanId(val int64) {
	p.PlanId = val
}
func (p *CreateAdCreativeRequest) SetCreativeType(val int32) {
	p.CreativeType = val
}
func (p *CreateAdCreativeRequest) SetMediaUrl(val string) {
	p.MediaUrl = val
}
func (p *CreateAdCreativeRequest) SetTitle(val string) {
	p.Title = val
}
func (p *CreateAdCreativeRequest) SetDescription(val string) {
	p.Description = val
}

func (p *CreateAdCreativeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateAdCreativeRequest(%+v)", *p)
}

var fieldIDToName_CreateAdCreativeRequest = map[int16]string{
	1: "planId",
	2: "creativeType",
	3: "mediaUrl",
	4: "title",
	5: "description",
}

type CreateAdCreativeResponse struct {
	BaseResp   *common.BaseResponse `thrift:"baseResp,1" frugal:"1,default,common.BaseResponse" json:"baseResp"`
	CreativeId int64                `thrift:"creativeId,2" frugal:"2,default,i64" json:"creativeId"`
}

func NewCreateAdCreativeResponse() *CreateAdCreativeResponse {
	return &CreateAdCreativeResponse{}
}

func (p *CreateAdCreativeResponse) InitDefault() {
}

var CreateAdCreativeResponse_BaseResp_DEFAULT *common.BaseResponse

func (p *CreateAdCreativeResponse) GetBaseResp() (v *common.BaseResponse) {
	if !p.IsSetBaseResp() {
		return CreateAdCreativeResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *CreateAdCreativeResponse) GetCreativeId() (v int64) {
	return p.CreativeId
}
func (p *CreateAdCreativeResponse) SetBaseResp(val *common.BaseResponse) {
	p.BaseResp = val
}
func (p *CreateAdCreativeResponse) SetCreativeId(val int64) {
	p.CreativeId = val
}

func (p *CreateAdCreativeResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CreateAdCreativeResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateAdCreativeResponse(%+v)", *p)
}

var fieldIDToName_CreateAdCreativeResponse = map[int16]string{
	1: "baseResp",
	2: "creativeId",
}

type UpdateAdCreativeRequest struct {
	CreativeId   int64   `thrift:"creativeId,1" frugal:"1,default,i64" json:"creativeId"`
	PlanId       *int64  `thrift:"planId,2,optional" frugal:"2,optional,i64" json:"planId,omitempty"`
	CreativeType *int32  `thrift:"creativeType,3,optional" frugal:"3,optional,i32" json:"creativeType,omitempty"`
	MediaUrl     *string `thrift:"mediaUrl,4,optional" frugal:"4,optional,string" json:"mediaUrl,omitempty"`
	Title        *string `thrift:"title,5,optional" frugal:"5,optional,string" json:"title,omitempty"`
	Description  *string `thrift:"description,6,optional" frugal:"6,optional,string" json:"description,omitempty"`
	Status       *int32  `thrift:"status,7,optional" frugal:"7,optional,i32" json:"status,omitempty"`
}

func NewUpdateAdCreativeRequest() *UpdateAdCreativeRequest {
	return &UpdateAdCreativeRequest{}
}

func (p *UpdateAdCreativeRequest) InitDefault() {
}

func (p *UpdateAdCreativeRequest) GetCreativeId() (v int64) {
	return p.CreativeId
}

var UpdateAdCreativeRequest_PlanId_DEFAULT int64

func (p *UpdateAdCreativeRequest) GetPlanId() (v int64) {
	if !p.IsSetPlanId() {
		return UpdateAdCreativeRequest_PlanId_DEFAULT
	}
	return *p.PlanId
}

var UpdateAdCreativeRequest_CreativeType_DEFAULT int32

func (p *UpdateAdCreativeRequest) GetCreativeType() (v int32) {
	if !p.IsSetCreativeType() {
		return UpdateAdCreativeRequest_CreativeType_DEFAULT
	}
	return *p.CreativeType
}

var UpdateAdCreativeRequest_MediaUrl_DEFAULT string

func (p *UpdateAdCreativeRequest) GetMediaUrl() (v string) {
	if !p.IsSetMediaUrl() {
		return UpdateAdCreativeRequest_MediaUrl_DEFAULT
	}
	return *p.MediaUrl
}

var UpdateAdCreativeRequest_Title_DEFAULT string

func (p *UpdateAdCreativeRequest) GetTitle() (v string) {
	if !p.IsSetTitle() {
		return UpdateAdCreativeRequest_Title_DEFAULT
	}
	return *p.Title
}

var UpdateAdCreativeRequest_Description_DEFAULT string

func (p *UpdateAdCreativeRequest) GetDescription() (v string) {
	if !p.IsSetDescription() {
		return UpdateAdCreativeRequest_Description_DEFAULT
	}
	return *p.Description
}

var UpdateAdCreativeRequest_Status_DEFAULT int32

func (p *UpdateAdCreativeRequest) GetStatus() (v int32) {
	if !p.IsSetStatus() {
		return UpdateAdCreativeRequest_Status_DEFAULT
	}
	return *p.Status
}
func (p *UpdateAdCreativeRequest) SetCreativeId(val int64) {
	p.CreativeId = val
}
func (p *UpdateAdCreativeRequest) SetPlanId(val *int64) {
	p.PlanId = val
}
func (p *UpdateAdCreativeRequest) SetCreativeType(val *int32) {
	p.CreativeType = val
}
func (p *UpdateAdCreativeRequest) SetMediaUrl(val *string) {
	p.MediaUrl = val
}
func (p *UpdateAdCreativeRequest) SetTitle(val *string) {
	p.Title = val
}
func (p *UpdateAdCreativeRequest) SetDescription(val *string) {
	p.Description = val
}
func (p *UpdateAdCreativeRequest) SetStatus(val *int32) {
	p.Status = val
}

func (p *UpdateAdCreativeRequest) IsSetPlanId() bool {
	return p.PlanId != nil
}

func (p *UpdateAdCreativeRequest) IsSetCreativeType() bool {
	return p.CreativeType != nil
}

func (p *UpdateAdCreativeRequest) IsSetMediaUrl() bool {
	return p.MediaUrl != nil
}

func (p *UpdateAdCreativeRequest) IsSetTitle() bool {
	return p.Title != nil
}

func (p *UpdateAdCreativeRequest) IsSetDescription() bool {
	return p.Description != nil
}

func (p *UpdateAdCreativeRequest) IsSetStatus() bool {
	return p.Status != nil
}

func (p *UpdateAdCreativeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateAdCreativeRequest(%+v)", *p)
}

var fieldIDToName_UpdateAdCreativeRequest = map[int16]string{
	1: "creativeId",
	2: "planId",
	3: "creativeType",
	4: "mediaUrl",
	5: "title",
	6: "description",
	7: "status",
}

type UpdateAdCreativeResponse struct {
	BaseResp *common.BaseResponse `thrift:"baseResp,1" frugal:"1,default,common.BaseResponse" json:"baseResp"`
}

func NewUpdateAdCreativeResponse() *UpdateAdCreativeResponse {
	return &UpdateAdCreativeResponse{}
}

func (p *UpdateAdCreativeResponse) InitDefault() {
}

var UpdateAdCreativeResponse_BaseResp_DEFAULT *common.BaseResponse

func (p *UpdateAdCreativeResponse) GetBaseResp() (v *common.BaseResponse) {
	if !p.IsSetBaseResp() {
		return UpdateAdCreativeResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *UpdateAdCreativeResponse) SetBaseResp(val *common.BaseResponse) {
	p.BaseResp = val
}

func (p *UpdateAdCreativeResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UpdateAdCreativeResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateAdCreativeResponse(%+v)", *p)
}

var fieldIDToName_UpdateAdCreativeResponse = map[int16]string{
	1: "baseResp",
}

type GetAdCreativeRequest struct {
	CreativeId int64 `thrift:"creativeId,1" frugal:"1,default,i64" json:"creativeId"`
}

func NewGetAdCreativeRequest() *GetAdCreativeRequest {
	return &GetAdCreativeRequest{}
}

func (p *GetAdCreativeRequest) InitDefault() {
}

func (p *GetAdCreativeRequest) GetCreativeId() (v int64) {
	return p.CreativeId
}
func (p *GetAdCreativeRequest) SetCreativeId(val int64) {
	p.CreativeId = val
}

func (p *GetAdCreativeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAdCreativeRequest(%+v)", *p)
}

var fieldIDToName_GetAdCreativeRequest = map[int16]string{
	1: "creativeId",
}

type GetAdCreativeResponse struct {
	BaseResp   *common.BaseResponse `thrift:"baseResp,1" frugal:"1,default,common.BaseResponse" json:"baseResp"`
	AdCreative *AdCreative          `thrift:"adCreative,2" frugal:"2,default,AdCreative" json:"adCreative"`
}

func NewGetAdCreativeResponse() *GetAdCreativeResponse {
	return &GetAdCreativeResponse{}
}

func (p *GetAdCreativeResponse) InitDefault() {
}

var GetAdCreativeResponse_BaseResp_DEFAULT *common.BaseResponse

func (p *GetAdCreativeResponse) GetBaseResp() (v *common.BaseResponse) {
	if !p.IsSetBaseResp() {
		return GetAdCreativeResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var GetAdCreativeResponse_AdCreative_DEFAULT *AdCreative

func (p *GetAdCreativeResponse) GetAdCreative() (v *AdCreative) {
	if !p.IsSetAdCreative() {
		return GetAdCreativeResponse_AdCreative_DEFAULT
	}
	return p.AdCreative
}
func (p *GetAdCreativeResponse) SetBaseResp(val *common.BaseResponse) {
	p.BaseResp = val
}
func (p *GetAdCreativeResponse) SetAdCreative(val *AdCreative) {
	p.AdCreative = val
}

func (p *GetAdCreativeResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetAdCreativeResponse) IsSetAdCreative() bool {
	return p.AdCreative != nil
}

func (p *GetAdCreativeResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAdCreativeResponse(%+v)", *p)
}

var fieldIDToName_GetAdCreativeResponse = map[int16]string{
	1: "baseResp",
	2: "adCreative",
}

type ListAdCreativesRequest struct {
	Page     int32  `thrift:"page,1" frugal:"1,default,i32" json:"page"`
	PageSize int32  `thrift:"pageSize,2" frugal:"2,default,i32" json:"pageSize"`
	PlanId   *int64 `thrift:"planId,3,optional" frugal:"3,optional,i64" json:"planId,omitempty"`
}

func NewListAdCreativesRequest() *ListAdCreativesRequest {
	return &ListAdCreativesRequest{}
}

func (p *ListAdCreativesRequest) InitDefault() {
}

func (p *ListAdCreativesRequest) GetPage() (v int32) {
	return p.Page
}

func (p *ListAdCreativesRequest) GetPageSize() (v int32) {
	return p.PageSize
}

var ListAdCreativesRequest_PlanId_DEFAULT int64

func (p *ListAdCreativesRequest) GetPlanId() (v int64) {
	if !p.IsSetPlanId() {
		return ListAdCreativesRequest_PlanId_DEFAULT
	}
	return *p.PlanId
}
func (p *ListAdCreativesRequest) SetPage(val int32) {
	p.Page = val
}
func (p *ListAdCreativesRequest) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *ListAdCreativesRequest) SetPlanId(val *int64) {
	p.PlanId = val
}

func (p *ListAdCreativesRequest) IsSetPlanId() bool {
	return p.PlanId != nil
}

func (p *ListAdCreativesRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListAdCreativesRequest(%+v)", *p)
}

var fieldIDToName_ListAdCreativesRequest = map[int16]string{
	1: "page",
	2: "pageSize",
	3: "planId",
}

type ListAdCreativesResponse struct {
	BaseResp    *common.BaseResponse `thrift:"baseResp,1" frugal:"1,default,common.BaseResponse" json:"baseResp"`
	AdCreatives []*AdCreative        `thrift:"adCreatives,2" frugal:"2,default,list<AdCreative>" json:"adCreatives"`
	Total       int64                `thrift:"total,3" frugal:"3,default,i64" json:"total"`
}

func NewListAdCreativesResponse() *ListAdCreativesResponse {
	return &ListAdCreativesResponse{}
}

func (p *ListAdCreativesResponse) InitDefault() {
}

var ListAdCreativesResponse_BaseResp_DEFAULT *common.BaseResponse

func (p *ListAdCreativesResponse) GetBaseResp() (v *common.BaseResponse) {
	if !p.IsSetBaseResp() {
		return ListAdCreativesResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *ListAdCreativesResponse) GetAdCreatives() (v []*AdCreative) {
	return p.AdCreatives
}

func (p *ListAdCreativesResponse) GetTotal() (v int64) {
	return p.Total
}
func (p *ListAdCreativesResponse) SetBaseResp(val *common.BaseResponse) {
	p.BaseResp = val
}
func (p *ListAdCreativesResponse) SetAdCreatives(val []*AdCreative) {
	p.AdCreatives = val
}
func (p *ListAdCreativesResponse) SetTotal(val int64) {
	p.Total = val
}

func (p *ListAdCreativesResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ListAdCreativesResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListAdCreativesResponse(%+v)", *p)
}

var fieldIDToName_ListAdCreativesResponse = map[int16]string{
	1: "baseResp",
	2: "adCreatives",
	3: "total",
}

type DeleteAdCreativeRequest struct {
	CreativeId int64 `thrift:"creativeId,1" frugal:"1,default,i64" json:"creativeId"`
}

func NewDeleteAdCreativeRequest() *DeleteAdCreativeRequest {
	return &DeleteAdCreativeRequest{}
}

func (p *DeleteAdCreativeRequest) InitDefault() {
}

func (p *DeleteAdCreativeRequest) GetCreativeId() (v int64) {
	return p.CreativeId
}
func (p *DeleteAdCreativeRequest) SetCreativeId(val int64) {
	p.CreativeId = val
}

func (p *DeleteAdCreativeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteAdCreativeRequest(%+v)", *p)
}

var fieldIDToName_DeleteAdCreativeRequest = map[int16]string{
	1: "creativeId",
}

type DeleteAdCreativeResponse struct {
	BaseResp *common.BaseResponse `thrift:"baseResp,1" frugal:"1,default,common.BaseResponse" json:"baseResp"`
}

func NewDeleteAdCreativeResponse() *DeleteAdCreativeResponse {
	return &DeleteAdCreativeResponse{}
}

func (p *DeleteAdCreativeResponse) InitDefault() {
}

var DeleteAdCreativeResponse_BaseResp_DEFAULT *common.BaseResponse

func (p *DeleteAdCreativeResponse) GetBaseResp() (v *common.BaseResponse) {
	if !p.IsSetBaseResp() {
		return DeleteAdCreativeResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *DeleteAdCreativeResponse) SetBaseResp(val *common.BaseResponse) {
	p.BaseResp = val
}

func (p *DeleteAdCreativeResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *DeleteAdCreativeResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteAdCreativeResponse(%+v)", *p)
}

var fieldIDToName_DeleteAdCreativeResponse = map[int16]string{
	1: "baseResp",
}

type UserInterest struct {
	Id         int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	UserId     int64   `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
	Tag        string  `thrift:"tag,3" frugal:"3,default,string" json:"tag"`
	Weight     float64 `thrift:"weight,4" frugal:"4,default,double" json:"weight"`
	UpdateTime string  `thrift:"updateTime,5" frugal:"5,default,string" json:"updateTime"`
}

func NewUserInterest() *UserInterest {
	return &UserInterest{}
}

func (p *UserInterest) InitDefault() {
}

func (p *UserInterest) GetId() (v int64) {
	return p.Id
}

func (p *UserInterest) GetUserId() (v int64) {
	return p.UserId
}

func (p *UserInterest) GetTag() (v string) {
	return p.Tag
}

func (p *UserInterest) GetWeight() (v float64) {
	return p.Weight
}

func (p *UserInterest) GetUpdateTime() (v string) {
	return p.UpdateTime
}
func (p *UserInterest) SetId(val int64) {
	p.Id = val
}
func (p *UserInterest) SetUserId(val int64) {
	p.UserId = val
}
func (p *UserInterest) SetTag(val string) {
	p.Tag = val
}
func (p *UserInterest) SetWeight(val float64) {
	p.Weight = val
}
func (p *UserInterest) SetUpdateTime(val string) {
	p.UpdateTime = val
}

func (p *UserInterest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInterest(%+v)", *p)
}

var fieldIDToName_UserInterest = map[int16]string{
	1: "id",
	2: "userId",
	3: "tag",
	4: "weight",
	5: "updateTime",
}

type AddUserInterestRequest struct {
	UserId int64   `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	Tag    string  `thrift:"tag,2" frugal:"2,default,string" json:"tag"`
	Weight float64 `thrift:"weight,3" frugal:"3,default,double" json:"weight"`
}

func NewAddUserInterestRequest() *AddUserInterestRequest {
	return &AddUserInterestRequest{}
}

func (p *AddUserInterestRequest) InitDefault() {
}

func (p *AddUserInterestRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *AddUserInterestRequest) GetTag() (v string) {
	return p.Tag
}

func (p *AddUserInterestRequest) GetWeight() (v float64) {
	return p.Weight
}
func (p *AddUserInterestRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *AddUserInterestRequest) SetTag(val string) {
	p.Tag = val
}
func (p *AddUserInterestRequest) SetWeight(val float64) {
	p.Weight = val
}

func (p *AddUserInterestRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddUserInterestRequest(%+v)", *p)
}

var fieldIDToName_AddUserInterestRequest = map[int16]string{
	1: "userId",
	2: "tag",
	3: "weight",
}

type AddUserInterestResponse struct {
	BaseResp *common.BaseResponse `thrift:"baseResp,1" frugal:"1,default,common.BaseResponse" json:"baseResp"`
	Id       int64                `thrift:"id,2" frugal:"2,default,i64" json:"id"`
}

func NewAddUserInterestResponse() *AddUserInterestResponse {
	return &AddUserInterestResponse{}
}

func (p *AddUserInterestResponse) InitDefault() {
}

var AddUserInterestResponse_BaseResp_DEFAULT *common.BaseResponse

func (p *AddUserInterestResponse) GetBaseResp() (v *common.BaseResponse) {
	if !p.IsSetBaseResp() {
		return AddUserInterestResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *AddUserInterestResponse) GetId() (v int64) {
	return p.Id
}
func (p *AddUserInterestResponse) SetBaseResp(val *common.BaseResponse) {
	p.BaseResp = val
}
func (p *AddUserInterestResponse) SetId(val int64) {
	p.Id = val
}

func (p *AddUserInterestResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *AddUserInterestResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddUserInterestResponse(%+v)", *p)
}

var fieldIDToName_AddUserInterestResponse = map[int16]string{
	1: "baseResp",
	2: "id",
}

type UpdateUserInterestRequest struct {
	Id     int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Weight float64 `thrift:"weight,2" frugal:"2,default,double" json:"weight"`
}

func NewUpdateUserInterestRequest() *UpdateUserInterestRequest {
	return &UpdateUserInterestRequest{}
}

func (p *UpdateUserInterestRequest) InitDefault() {
}

func (p *UpdateUserInterestRequest) GetId() (v int64) {
	return p.Id
}

func (p *UpdateUserInterestRequest) GetWeight() (v float64) {
	return p.Weight
}
func (p *UpdateUserInterestRequest) SetId(val int64) {
	p.Id = val
}
func (p *UpdateUserInterestRequest) SetWeight(val float64) {
	p.Weight = val
}

func (p *UpdateUserInterestRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserInterestRequest(%+v)", *p)
}

var fieldIDToName_UpdateUserInterestRequest = map[int16]string{
	1: "id",
	2: "weight",
}

type UpdateUserInterestResponse struct {
	BaseResp *common.BaseResponse `thrift:"baseResp,1" frugal:"1,default,common.BaseResponse" json:"baseResp"`
}

func NewUpdateUserInterestResponse() *UpdateUserInterestResponse {
	return &UpdateUserInterestResponse{}
}

func (p *UpdateUserInterestResponse) InitDefault() {
}

var UpdateUserInterestResponse_BaseResp_DEFAULT *common.BaseResponse

func (p *UpdateUserInterestResponse) GetBaseResp() (v *common.BaseResponse) {
	if !p.IsSetBaseResp() {
		return UpdateUserInterestResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *UpdateUserInterestResponse) SetBaseResp(val *common.BaseResponse) {
	p.BaseResp = val
}

func (p *UpdateUserInterestResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UpdateUserInterestResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserInterestResponse(%+v)", *p)
}

var fieldIDToName_UpdateUserInterestResponse = map[int16]string{
	1: "baseResp",
}

type GetUserInterestsRequest struct {
	UserId int64 `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
}

func NewGetUserInterestsRequest() *GetUserInterestsRequest {
	return &GetUserInterestsRequest{}
}

func (p *GetUserInterestsRequest) InitDefault() {
}

func (p *GetUserInterestsRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetUserInterestsRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetUserInterestsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInterestsRequest(%+v)", *p)
}

var fieldIDToName_GetUserInterestsRequest = map[int16]string{
	1: "userId",
}

type GetUserInterestsResponse struct {
	BaseResp  *common.BaseResponse `thrift:"baseResp,1" frugal:"1,default,common.BaseResponse" json:"baseResp"`
	Interests []*UserInterest      `thrift:"interests,2" frugal:"2,default,list<UserInterest>" json:"interests"`
}

func NewGetUserInterestsResponse() *GetUserInterestsResponse {
	return &GetUserInterestsResponse{}
}

func (p *GetUserInterestsResponse) InitDefault() {
}

var GetUserInterestsResponse_BaseResp_DEFAULT *common.BaseResponse

func (p *GetUserInterestsResponse) GetBaseResp() (v *common.BaseResponse) {
	if !p.IsSetBaseResp() {
		return GetUserInterestsResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *GetUserInterestsResponse) GetInterests() (v []*UserInterest) {
	return p.Interests
}
func (p *GetUserInterestsResponse) SetBaseResp(val *common.BaseResponse) {
	p.BaseResp = val
}
func (p *GetUserInterestsResponse) SetInterests(val []*UserInterest) {
	p.Interests = val
}

func (p *GetUserInterestsResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetUserInterestsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInterestsResponse(%+v)", *p)
}

var fieldIDToName_GetUserInterestsResponse = map[int16]string{
	1: "baseResp",
	2: "interests",
}

type DeleteUserInterestRequest struct {
	Id int64 `thrift:"id,1" frugal:"1,default,i64" json:"id"`
}

func NewDeleteUserInterestRequest() *DeleteUserInterestRequest {
	return &DeleteUserInterestRequest{}
}

func (p *DeleteUserInterestRequest) InitDefault() {
}

func (p *DeleteUserInterestRequest) GetId() (v int64) {
	return p.Id
}
func (p *DeleteUserInterestRequest) SetId(val int64) {
	p.Id = val
}

func (p *DeleteUserInterestRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteUserInterestRequest(%+v)", *p)
}

var fieldIDToName_DeleteUserInterestRequest = map[int16]string{
	1: "id",
}

type DeleteUserInterestResponse struct {
	BaseResp *common.BaseResponse `thrift:"baseResp,1" frugal:"1,default,common.BaseResponse" json:"baseResp"`
}

func NewDeleteUserInterestResponse() *DeleteUserInterestResponse {
	return &DeleteUserInterestResponse{}
}

func (p *DeleteUserInterestResponse) InitDefault() {
}

var DeleteUserInterestResponse_BaseResp_DEFAULT *common.BaseResponse

func (p *DeleteUserInterestResponse) GetBaseResp() (v *common.BaseResponse) {
	if !p.IsSetBaseResp() {
		return DeleteUserInterestResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *DeleteUserInterestResponse) SetBaseResp(val *common.BaseResponse) {
	p.BaseResp = val
}

func (p *DeleteUserInterestResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *DeleteUserInterestResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteUserInterestResponse(%+v)", *p)
}

var fieldIDToName_DeleteUserInterestResponse = map[int16]string{
	1: "baseResp",
}

type UserAdEvent struct {
	EventId    int64  `thrift:"eventId,1" frugal:"1,default,i64" json:"eventId"`
	UserId     int64  `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
	CreativeId int64  `thrift:"creativeId,3" frugal:"3,default,i64" json:"creativeId"`
	EventType  int32  `thrift:"eventType,4" frugal:"4,default,i32" json:"eventType"`
	Ts         string `thrift:"ts,5" frugal:"5,default,string" json:"ts"`
	Extra      string `thrift:"extra,6" frugal:"6,default,string" json:"extra"`
}

func NewUserAdEvent() *UserAdEvent {
	return &UserAdEvent{}
}

func (p *UserAdEvent) InitDefault() {
}

func (p *UserAdEvent) GetEventId() (v int64) {
	return p.EventId
}

func (p *UserAdEvent) GetUserId() (v int64) {
	return p.UserId
}

func (p *UserAdEvent) GetCreativeId() (v int64) {
	return p.CreativeId
}

func (p *UserAdEvent) GetEventType() (v int32) {
	return p.EventType
}

func (p *UserAdEvent) GetTs() (v string) {
	return p.Ts
}

func (p *UserAdEvent) GetExtra() (v string) {
	return p.Extra
}
func (p *UserAdEvent) SetEventId(val int64) {
	p.EventId = val
}
func (p *UserAdEvent) SetUserId(val int64) {
	p.UserId = val
}
func (p *UserAdEvent) SetCreativeId(val int64) {
	p.CreativeId = val
}
func (p *UserAdEvent) SetEventType(val int32) {
	p.EventType = val
}
func (p *UserAdEvent) SetTs(val string) {
	p.Ts = val
}
func (p *UserAdEvent) SetExtra(val string) {
	p.Extra = val
}

func (p *UserAdEvent) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserAdEvent(%+v)", *p)
}

var fieldIDToName_UserAdEvent = map[int16]string{
	1: "eventId",
	2: "userId",
	3: "creativeId",
	4: "eventType",
	5: "ts",
	6: "extra",
}

type CreateAdEventRequest struct {
	UserId     int64  `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	CreativeId int64  `thrift:"creativeId,2" frugal:"2,default,i64" json:"creativeId"`
	EventType  int32  `thrift:"eventType,3" frugal:"3,default,i32" json:"eventType"`
	Ts         string `thrift:"ts,4" frugal:"4,default,string" json:"ts"`
	Extra      string `thrift:"extra,5" frugal:"5,default,string" json:"extra"`
}

func NewCreateAdEventRequest() *CreateAdEventRequest {
	return &CreateAdEventRequest{}
}

func (p *CreateAdEventRequest) InitDefault() {
}

func (p *CreateAdEventRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *CreateAdEventRequest) GetCreativeId() (v int64) {
	return p.CreativeId
}

func (p *CreateAdEventRequest) GetEventType() (v int32) {
	return p.EventType
}

func (p *CreateAdEventRequest) GetTs() (v string) {
	return p.Ts
}

func (p *CreateAdEventRequest) GetExtra() (v string) {
	return p.Extra
}
func (p *CreateAdEventRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *CreateAdEventRequest) SetCreativeId(val int64) {
	p.CreativeId = val
}
func (p *CreateAdEventRequest) SetEventType(val int32) {
	p.EventType = val
}
func (p *CreateAdEventRequest) SetTs(val string) {
	p.Ts = val
}
func (p *CreateAdEventRequest) SetExtra(val string) {
	p.Extra = val
}

func (p *CreateAdEventRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateAdEventRequest(%+v)", *p)
}

var fieldIDToName_CreateAdEventRequest = map[int16]string{
	1: "userId",
	2: "creativeId",
	3: "eventType",
	4: "ts",
	5: "extra",
}

type CreateAdEventResponse struct {
	BaseResp *common.BaseResponse `thrift:"baseResp,1" frugal:"1,default,common.BaseResponse" json:"baseResp"`
	EventId  int64                `thrift:"eventId,2" frugal:"2,default,i64" json:"eventId"`
}

func NewCreateAdEventResponse() *CreateAdEventResponse {
	return &CreateAdEventResponse{}
}

func (p *CreateAdEventResponse) InitDefault() {
}

var CreateAdEventResponse_BaseResp_DEFAULT *common.BaseResponse

func (p *CreateAdEventResponse) GetBaseResp() (v *common.BaseResponse) {
	if !p.IsSetBaseResp() {
		return CreateAdEventResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *CreateAdEventResponse) GetEventId() (v int64) {
	return p.EventId
}
func (p *CreateAdEventResponse) SetBaseResp(val *common.BaseResponse) {
	p.BaseResp = val
}
func (p *CreateAdEventResponse) SetEventId(val int64) {
	p.EventId = val
}

func (p *CreateAdEventResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CreateAdEventResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateAdEventResponse(%+v)", *p)
}

var fieldIDToName_CreateAdEventResponse = map[int16]string{
	1: "baseResp",
	2: "eventId",
}

type GetUserAdEventsRequest struct {
	UserId    int64  `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	Page      int32  `thrift:"page,2" frugal:"2,default,i32" json:"page"`
	PageSize  int32  `thrift:"pageSize,3" frugal:"3,default,i32" json:"pageSize"`
	EventType *int32 `thrift:"eventType,4,optional" frugal:"4,optional,i32" json:"eventType,omitempty"`
}

func NewGetUserAdEventsRequest() *GetUserAdEventsRequest {
	return &GetUserAdEventsRequest{}
}

func (p *GetUserAdEventsRequest) InitDefault() {
}

func (p *GetUserAdEventsRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *GetUserAdEventsRequest) GetPage() (v int32) {
	return p.Page
}

func (p *GetUserAdEventsRequest) GetPageSize() (v int32) {
	return p.PageSize
}

var GetUserAdEventsRequest_EventType_DEFAULT int32

func (p *GetUserAdEventsRequest) GetEventType() (v int32) {
	if !p.IsSetEventType() {
		return GetUserAdEventsRequest_EventType_DEFAULT
	}
	return *p.EventType
}
func (p *GetUserAdEventsRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *GetUserAdEventsRequest) SetPage(val int32) {
	p.Page = val
}
func (p *GetUserAdEventsRequest) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *GetUserAdEventsRequest) SetEventType(val *int32) {
	p.EventType = val
}

func (p *GetUserAdEventsRequest) IsSetEventType() bool {
	return p.EventType != nil
}

func (p *GetUserAdEventsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserAdEventsRequest(%+v)", *p)
}

var fieldIDToName_GetUserAdEventsRequest = map[int16]string{
	1: "userId",
	2: "page",
	3: "pageSize",
	4: "eventType",
}

type GetUserAdEventsResponse struct {
	BaseResp *common.BaseResponse `thrift:"baseResp,1" frugal:"1,default,common.BaseResponse" json:"baseResp"`
	Events   []*UserAdEvent       `thrift:"events,2" frugal:"2,default,list<UserAdEvent>" json:"events"`
	Total    int64                `thrift:"total,3" frugal:"3,default,i64" json:"total"`
}

func NewGetUserAdEventsResponse() *GetUserAdEventsResponse {
	return &GetUserAdEventsResponse{}
}

func (p *GetUserAdEventsResponse) InitDefault() {
}

var GetUserAdEventsResponse_BaseResp_DEFAULT *common.BaseResponse

func (p *GetUserAdEventsResponse) GetBaseResp() (v *common.BaseResponse) {
	if !p.IsSetBaseResp() {
		return GetUserAdEventsResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *GetUserAdEventsResponse) GetEvents() (v []*UserAdEvent) {
	return p.Events
}

func (p *GetUserAdEventsResponse) GetTotal() (v int64) {
	return p.Total
}
func (p *GetUserAdEventsResponse) SetBaseResp(val *common.BaseResponse) {
	p.BaseResp = val
}
func (p *GetUserAdEventsResponse) SetEvents(val []*UserAdEvent) {
	p.Events = val
}
func (p *GetUserAdEventsResponse) SetTotal(val int64) {
	p.Total = val
}

func (p *GetUserAdEventsResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetUserAdEventsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserAdEventsResponse(%+v)", *p)
}

var fieldIDToName_GetUserAdEventsResponse = map[int16]string{
	1: "baseResp",
	2: "events",
	3: "total",
}

type GetCreativeAdEventsRequest struct {
	CreativeId int64  `thrift:"creativeId,1" frugal:"1,default,i64" json:"creativeId"`
	Page       int32  `thrift:"page,2" frugal:"2,default,i32" json:"page"`
	PageSize   int32  `thrift:"pageSize,3" frugal:"3,default,i32" json:"pageSize"`
	EventType  *int32 `thrift:"eventType,4,optional" frugal:"4,optional,i32" json:"eventType,omitempty"`
}

func NewGetCreativeAdEventsRequest() *GetCreativeAdEventsRequest {
	return &GetCreativeAdEventsRequest{}
}

func (p *GetCreativeAdEventsRequest) InitDefault() {
}

func (p *GetCreativeAdEventsRequest) GetCreativeId() (v int64) {
	return p.CreativeId
}

func (p *GetCreativeAdEventsRequest) GetPage() (v int32) {
	return p.Page
}

func (p *GetCreativeAdEventsRequest) GetPageSize() (v int32) {
	return p.PageSize
}

var GetCreativeAdEventsRequest_EventType_DEFAULT int32

func (p *GetCreativeAdEventsRequest) GetEventType() (v int32) {
	if !p.IsSetEventType() {
		return GetCreativeAdEventsRequest_EventType_DEFAULT
	}
	return *p.EventType
}
func (p *GetCreativeAdEventsRequest) SetCreativeId(val int64) {
	p.CreativeId = val
}
func (p *GetCreativeAdEventsRequest) SetPage(val int32) {
	p.Page = val
}
func (p *GetCreativeAdEventsRequest) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *GetCreativeAdEventsRequest) SetEventType(val *int32) {
	p.EventType = val
}

func (p *GetCreativeAdEventsRequest) IsSetEventType() bool {
	return p.EventType != nil
}

func (p *GetCreativeAdEventsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetCreativeAdEventsRequest(%+v)", *p)
}

var fieldIDToName_GetCreativeAdEventsRequest = map[int16]string{
	1: "creativeId",
	2: "page",
	3: "pageSize",
	4: "eventType",
}

type GetCreativeAdEventsResponse struct {
	BaseResp *common.BaseResponse `thrift:"baseResp,1" frugal:"1,default,common.BaseResponse" json:"baseResp"`
	Events   []*UserAdEvent       `thrift:"events,2" frugal:"2,default,list<UserAdEvent>" json:"events"`
	Total    int64                `thrift:"total,3" frugal:"3,default,i64" json:"total"`
}

func NewGetCreativeAdEventsResponse() *GetCreativeAdEventsResponse {
	return &GetCreativeAdEventsResponse{}
}

func (p *GetCreativeAdEventsResponse) InitDefault() {
}

var GetCreativeAdEventsResponse_BaseResp_DEFAULT *common.BaseResponse

func (p *GetCreativeAdEventsResponse) GetBaseResp() (v *common.BaseResponse) {
	if !p.IsSetBaseResp() {
		return GetCreativeAdEventsResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *GetCreativeAdEventsResponse) GetEvents() (v []*UserAdEvent) {
	return p.Events
}

func (p *GetCreativeAdEventsResponse) GetTotal() (v int64) {
	return p.Total
}
func (p *GetCreativeAdEventsResponse) SetBaseResp(val *common.BaseResponse) {
	p.BaseResp = val
}
func (p *GetCreativeAdEventsResponse) SetEvents(val []*UserAdEvent) {
	p.Events = val
}
func (p *GetCreativeAdEventsResponse) SetTotal(val int64) {
	p.Total = val
}

func (p *GetCreativeAdEventsResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetCreativeAdEventsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetCreativeAdEventsResponse(%+v)", *p)
}

var fieldIDToName_GetCreativeAdEventsResponse = map[int16]string{
	1: "baseResp",
	2: "events",
	3: "total",
}

type GetAdvertRecommendRequest struct {
	UserId int64 `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
}

func NewGetAdvertRecommendRequest() *GetAdvertRecommendRequest {
	return &GetAdvertRecommendRequest{}
}

func (p *GetAdvertRecommendRequest) InitDefault() {
}

func (p *GetAdvertRecommendRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetAdvertRecommendRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetAdvertRecommendRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAdvertRecommendRequest(%+v)", *p)
}

var fieldIDToName_GetAdvertRecommendRequest = map[int16]string{
	1: "userId",
}

type GetAdvertRecommendResponse struct {
	BaseResp *common.BaseResponse `thrift:"baseResp,1" frugal:"1,default,common.BaseResponse" json:"baseResp"`
	Adverts  []*AdCreative        `thrift:"adverts,2" frugal:"2,default,list<AdCreative>" json:"adverts"`
	Total    int64                `thrift:"total,3" frugal:"3,default,i64" json:"total"`
}

func NewGetAdvertRecommendResponse() *GetAdvertRecommendResponse {
	return &GetAdvertRecommendResponse{}
}

func (p *GetAdvertRecommendResponse) InitDefault() {
}

var GetAdvertRecommendResponse_BaseResp_DEFAULT *common.BaseResponse

func (p *GetAdvertRecommendResponse) GetBaseResp() (v *common.BaseResponse) {
	if !p.IsSetBaseResp() {
		return GetAdvertRecommendResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *GetAdvertRecommendResponse) GetAdverts() (v []*AdCreative) {
	return p.Adverts
}

func (p *GetAdvertRecommendResponse) GetTotal() (v int64) {
	return p.Total
}
func (p *GetAdvertRecommendResponse) SetBaseResp(val *common.BaseResponse) {
	p.BaseResp = val
}
func (p *GetAdvertRecommendResponse) SetAdverts(val []*AdCreative) {
	p.Adverts = val
}
func (p *GetAdvertRecommendResponse) SetTotal(val int64) {
	p.Total = val
}

func (p *GetAdvertRecommendResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetAdvertRecommendResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAdvertRecommendResponse(%+v)", *p)
}

var fieldIDToName_GetAdvertRecommendResponse = map[int16]string{
	1: "baseResp",
	2: "adverts",
	3: "total",
}

type RecommendService interface {
	CreateAdPlan(ctx context.Context, req *CreateAdPlanRequest) (r *CreateAdPlanResponse, err error)

	UpdateAdPlan(ctx context.Context, req *UpdateAdPlanRequest) (r *UpdateAdPlanResponse, err error)

	GetAdPlan(ctx context.Context, req *GetAdPlanRequest) (r *GetAdPlanResponse, err error)

	ListAdPlans(ctx context.Context, req *ListAdPlansRequest) (r *ListAdPlansResponse, err error)

	DeleteAdPlan(ctx context.Context, req *DeleteAdPlanRequest) (r *DeleteAdPlanResponse, err error)

	CreateAdCreative(ctx context.Context, req *CreateAdCreativeRequest) (r *CreateAdCreativeResponse, err error)

	UpdateAdCreative(ctx context.Context, req *UpdateAdCreativeRequest) (r *UpdateAdCreativeResponse, err error)

	GetAdCreative(ctx context.Context, req *GetAdCreativeRequest) (r *GetAdCreativeResponse, err error)

	ListAdCreatives(ctx context.Context, req *ListAdCreativesRequest) (r *ListAdCreativesResponse, err error)

	DeleteAdCreative(ctx context.Context, req *DeleteAdCreativeRequest) (r *DeleteAdCreativeResponse, err error)

	AddUserInterest(ctx context.Context, req *AddUserInterestRequest) (r *AddUserInterestResponse, err error)

	UpdateUserInterest(ctx context.Context, req *UpdateUserInterestRequest) (r *UpdateUserInterestResponse, err error)

	GetUserInterests(ctx context.Context, req *GetUserInterestsRequest) (r *GetUserInterestsResponse, err error)

	DeleteUserInterest(ctx context.Context, req *DeleteUserInterestRequest) (r *DeleteUserInterestResponse, err error)

	CreateAdEvent(ctx context.Context, req *CreateAdEventRequest) (r *CreateAdEventResponse, err error)

	GetUserAdEvents(ctx context.Context, req *GetUserAdEventsRequest) (r *GetUserAdEventsResponse, err error)

	GetCreativeAdEvents(ctx context.Context, req *GetCreativeAdEventsRequest) (r *GetCreativeAdEventsResponse, err error)

	GetAdvertRecommend(ctx context.Context, req *GetAdvertRecommendRequest) (r *GetAdvertRecommendResponse, err error)
}

type RecommendServiceCreateAdPlanArgs struct {
	Req *CreateAdPlanRequest `thrift:"req,1" frugal:"1,default,CreateAdPlanRequest" json:"req"`
}

func NewRecommendServiceCreateAdPlanArgs() *RecommendServiceCreateAdPlanArgs {
	return &RecommendServiceCreateAdPlanArgs{}
}

func (p *RecommendServiceCreateAdPlanArgs) InitDefault() {
}

var RecommendServiceCreateAdPlanArgs_Req_DEFAULT *CreateAdPlanRequest

func (p *RecommendServiceCreateAdPlanArgs) GetReq() (v *CreateAdPlanRequest) {
	if !p.IsSetReq() {
		return RecommendServiceCreateAdPlanArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceCreateAdPlanArgs) SetReq(val *CreateAdPlanRequest) {
	p.Req = val
}

func (p *RecommendServiceCreateAdPlanArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceCreateAdPlanArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceCreateAdPlanArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceCreateAdPlanArgs = map[int16]string{
	1: "req",
}

type RecommendServiceCreateAdPlanResult struct {
	Success *CreateAdPlanResponse `thrift:"success,0,optional" frugal:"0,optional,CreateAdPlanResponse" json:"success,omitempty"`
}

func NewRecommendServiceCreateAdPlanResult() *RecommendServiceCreateAdPlanResult {
	return &RecommendServiceCreateAdPlanResult{}
}

func (p *RecommendServiceCreateAdPlanResult) InitDefault() {
}

var RecommendServiceCreateAdPlanResult_Success_DEFAULT *CreateAdPlanResponse

func (p *RecommendServiceCreateAdPlanResult) GetSuccess() (v *CreateAdPlanResponse) {
	if !p.IsSetSuccess() {
		return RecommendServiceCreateAdPlanResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceCreateAdPlanResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateAdPlanResponse)
}

func (p *RecommendServiceCreateAdPlanResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceCreateAdPlanResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceCreateAdPlanResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceCreateAdPlanResult = map[int16]string{
	0: "success",
}

type RecommendServiceUpdateAdPlanArgs struct {
	Req *UpdateAdPlanRequest `thrift:"req,1" frugal:"1,default,UpdateAdPlanRequest" json:"req"`
}

func NewRecommendServiceUpdateAdPlanArgs() *RecommendServiceUpdateAdPlanArgs {
	return &RecommendServiceUpdateAdPlanArgs{}
}

func (p *RecommendServiceUpdateAdPlanArgs) InitDefault() {
}

var RecommendServiceUpdateAdPlanArgs_Req_DEFAULT *UpdateAdPlanRequest

func (p *RecommendServiceUpdateAdPlanArgs) GetReq() (v *UpdateAdPlanRequest) {
	if !p.IsSetReq() {
		return RecommendServiceUpdateAdPlanArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceUpdateAdPlanArgs) SetReq(val *UpdateAdPlanRequest) {
	p.Req = val
}

func (p *RecommendServiceUpdateAdPlanArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceUpdateAdPlanArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceUpdateAdPlanArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceUpdateAdPlanArgs = map[int16]string{
	1: "req",
}

type RecommendServiceUpdateAdPlanResult struct {
	Success *UpdateAdPlanResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateAdPlanResponse" json:"success,omitempty"`
}

func NewRecommendServiceUpdateAdPlanResult() *RecommendServiceUpdateAdPlanResult {
	return &RecommendServiceUpdateAdPlanResult{}
}

func (p *RecommendServiceUpdateAdPlanResult) InitDefault() {
}

var RecommendServiceUpdateAdPlanResult_Success_DEFAULT *UpdateAdPlanResponse

func (p *RecommendServiceUpdateAdPlanResult) GetSuccess() (v *UpdateAdPlanResponse) {
	if !p.IsSetSuccess() {
		return RecommendServiceUpdateAdPlanResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceUpdateAdPlanResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateAdPlanResponse)
}

func (p *RecommendServiceUpdateAdPlanResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceUpdateAdPlanResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceUpdateAdPlanResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceUpdateAdPlanResult = map[int16]string{
	0: "success",
}

type RecommendServiceGetAdPlanArgs struct {
	Req *GetAdPlanRequest `thrift:"req,1" frugal:"1,default,GetAdPlanRequest" json:"req"`
}

func NewRecommendServiceGetAdPlanArgs() *RecommendServiceGetAdPlanArgs {
	return &RecommendServiceGetAdPlanArgs{}
}

func (p *RecommendServiceGetAdPlanArgs) InitDefault() {
}

var RecommendServiceGetAdPlanArgs_Req_DEFAULT *GetAdPlanRequest

func (p *RecommendServiceGetAdPlanArgs) GetReq() (v *GetAdPlanRequest) {
	if !p.IsSetReq() {
		return RecommendServiceGetAdPlanArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceGetAdPlanArgs) SetReq(val *GetAdPlanRequest) {
	p.Req = val
}

func (p *RecommendServiceGetAdPlanArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceGetAdPlanArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetAdPlanArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetAdPlanArgs = map[int16]string{
	1: "req",
}

type RecommendServiceGetAdPlanResult struct {
	Success *GetAdPlanResponse `thrift:"success,0,optional" frugal:"0,optional,GetAdPlanResponse" json:"success,omitempty"`
}

func NewRecommendServiceGetAdPlanResult() *RecommendServiceGetAdPlanResult {
	return &RecommendServiceGetAdPlanResult{}
}

func (p *RecommendServiceGetAdPlanResult) InitDefault() {
}

var RecommendServiceGetAdPlanResult_Success_DEFAULT *GetAdPlanResponse

func (p *RecommendServiceGetAdPlanResult) GetSuccess() (v *GetAdPlanResponse) {
	if !p.IsSetSuccess() {
		return RecommendServiceGetAdPlanResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceGetAdPlanResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetAdPlanResponse)
}

func (p *RecommendServiceGetAdPlanResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceGetAdPlanResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetAdPlanResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetAdPlanResult = map[int16]string{
	0: "success",
}

type RecommendServiceListAdPlansArgs struct {
	Req *ListAdPlansRequest `thrift:"req,1" frugal:"1,default,ListAdPlansRequest" json:"req"`
}

func NewRecommendServiceListAdPlansArgs() *RecommendServiceListAdPlansArgs {
	return &RecommendServiceListAdPlansArgs{}
}

func (p *RecommendServiceListAdPlansArgs) InitDefault() {
}

var RecommendServiceListAdPlansArgs_Req_DEFAULT *ListAdPlansRequest

func (p *RecommendServiceListAdPlansArgs) GetReq() (v *ListAdPlansRequest) {
	if !p.IsSetReq() {
		return RecommendServiceListAdPlansArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceListAdPlansArgs) SetReq(val *ListAdPlansRequest) {
	p.Req = val
}

func (p *RecommendServiceListAdPlansArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceListAdPlansArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceListAdPlansArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceListAdPlansArgs = map[int16]string{
	1: "req",
}

type RecommendServiceListAdPlansResult struct {
	Success *ListAdPlansResponse `thrift:"success,0,optional" frugal:"0,optional,ListAdPlansResponse" json:"success,omitempty"`
}

func NewRecommendServiceListAdPlansResult() *RecommendServiceListAdPlansResult {
	return &RecommendServiceListAdPlansResult{}
}

func (p *RecommendServiceListAdPlansResult) InitDefault() {
}

var RecommendServiceListAdPlansResult_Success_DEFAULT *ListAdPlansResponse

func (p *RecommendServiceListAdPlansResult) GetSuccess() (v *ListAdPlansResponse) {
	if !p.IsSetSuccess() {
		return RecommendServiceListAdPlansResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceListAdPlansResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListAdPlansResponse)
}

func (p *RecommendServiceListAdPlansResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceListAdPlansResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceListAdPlansResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceListAdPlansResult = map[int16]string{
	0: "success",
}

type RecommendServiceDeleteAdPlanArgs struct {
	Req *DeleteAdPlanRequest `thrift:"req,1" frugal:"1,default,DeleteAdPlanRequest" json:"req"`
}

func NewRecommendServiceDeleteAdPlanArgs() *RecommendServiceDeleteAdPlanArgs {
	return &RecommendServiceDeleteAdPlanArgs{}
}

func (p *RecommendServiceDeleteAdPlanArgs) InitDefault() {
}

var RecommendServiceDeleteAdPlanArgs_Req_DEFAULT *DeleteAdPlanRequest

func (p *RecommendServiceDeleteAdPlanArgs) GetReq() (v *DeleteAdPlanRequest) {
	if !p.IsSetReq() {
		return RecommendServiceDeleteAdPlanArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceDeleteAdPlanArgs) SetReq(val *DeleteAdPlanRequest) {
	p.Req = val
}

func (p *RecommendServiceDeleteAdPlanArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceDeleteAdPlanArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceDeleteAdPlanArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceDeleteAdPlanArgs = map[int16]string{
	1: "req",
}

type RecommendServiceDeleteAdPlanResult struct {
	Success *DeleteAdPlanResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteAdPlanResponse" json:"success,omitempty"`
}

func NewRecommendServiceDeleteAdPlanResult() *RecommendServiceDeleteAdPlanResult {
	return &RecommendServiceDeleteAdPlanResult{}
}

func (p *RecommendServiceDeleteAdPlanResult) InitDefault() {
}

var RecommendServiceDeleteAdPlanResult_Success_DEFAULT *DeleteAdPlanResponse

func (p *RecommendServiceDeleteAdPlanResult) GetSuccess() (v *DeleteAdPlanResponse) {
	if !p.IsSetSuccess() {
		return RecommendServiceDeleteAdPlanResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceDeleteAdPlanResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteAdPlanResponse)
}

func (p *RecommendServiceDeleteAdPlanResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceDeleteAdPlanResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceDeleteAdPlanResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceDeleteAdPlanResult = map[int16]string{
	0: "success",
}

type RecommendServiceCreateAdCreativeArgs struct {
	Req *CreateAdCreativeRequest `thrift:"req,1" frugal:"1,default,CreateAdCreativeRequest" json:"req"`
}

func NewRecommendServiceCreateAdCreativeArgs() *RecommendServiceCreateAdCreativeArgs {
	return &RecommendServiceCreateAdCreativeArgs{}
}

func (p *RecommendServiceCreateAdCreativeArgs) InitDefault() {
}

var RecommendServiceCreateAdCreativeArgs_Req_DEFAULT *CreateAdCreativeRequest

func (p *RecommendServiceCreateAdCreativeArgs) GetReq() (v *CreateAdCreativeRequest) {
	if !p.IsSetReq() {
		return RecommendServiceCreateAdCreativeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceCreateAdCreativeArgs) SetReq(val *CreateAdCreativeRequest) {
	p.Req = val
}

func (p *RecommendServiceCreateAdCreativeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceCreateAdCreativeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceCreateAdCreativeArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceCreateAdCreativeArgs = map[int16]string{
	1: "req",
}

type RecommendServiceCreateAdCreativeResult struct {
	Success *CreateAdCreativeResponse `thrift:"success,0,optional" frugal:"0,optional,CreateAdCreativeResponse" json:"success,omitempty"`
}

func NewRecommendServiceCreateAdCreativeResult() *RecommendServiceCreateAdCreativeResult {
	return &RecommendServiceCreateAdCreativeResult{}
}

func (p *RecommendServiceCreateAdCreativeResult) InitDefault() {
}

var RecommendServiceCreateAdCreativeResult_Success_DEFAULT *CreateAdCreativeResponse

func (p *RecommendServiceCreateAdCreativeResult) GetSuccess() (v *CreateAdCreativeResponse) {
	if !p.IsSetSuccess() {
		return RecommendServiceCreateAdCreativeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceCreateAdCreativeResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateAdCreativeResponse)
}

func (p *RecommendServiceCreateAdCreativeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceCreateAdCreativeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceCreateAdCreativeResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceCreateAdCreativeResult = map[int16]string{
	0: "success",
}

type RecommendServiceUpdateAdCreativeArgs struct {
	Req *UpdateAdCreativeRequest `thrift:"req,1" frugal:"1,default,UpdateAdCreativeRequest" json:"req"`
}

func NewRecommendServiceUpdateAdCreativeArgs() *RecommendServiceUpdateAdCreativeArgs {
	return &RecommendServiceUpdateAdCreativeArgs{}
}

func (p *RecommendServiceUpdateAdCreativeArgs) InitDefault() {
}

var RecommendServiceUpdateAdCreativeArgs_Req_DEFAULT *UpdateAdCreativeRequest

func (p *RecommendServiceUpdateAdCreativeArgs) GetReq() (v *UpdateAdCreativeRequest) {
	if !p.IsSetReq() {
		return RecommendServiceUpdateAdCreativeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceUpdateAdCreativeArgs) SetReq(val *UpdateAdCreativeRequest) {
	p.Req = val
}

func (p *RecommendServiceUpdateAdCreativeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceUpdateAdCreativeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceUpdateAdCreativeArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceUpdateAdCreativeArgs = map[int16]string{
	1: "req",
}

type RecommendServiceUpdateAdCreativeResult struct {
	Success *UpdateAdCreativeResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateAdCreativeResponse" json:"success,omitempty"`
}

func NewRecommendServiceUpdateAdCreativeResult() *RecommendServiceUpdateAdCreativeResult {
	return &RecommendServiceUpdateAdCreativeResult{}
}

func (p *RecommendServiceUpdateAdCreativeResult) InitDefault() {
}

var RecommendServiceUpdateAdCreativeResult_Success_DEFAULT *UpdateAdCreativeResponse

func (p *RecommendServiceUpdateAdCreativeResult) GetSuccess() (v *UpdateAdCreativeResponse) {
	if !p.IsSetSuccess() {
		return RecommendServiceUpdateAdCreativeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceUpdateAdCreativeResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateAdCreativeResponse)
}

func (p *RecommendServiceUpdateAdCreativeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceUpdateAdCreativeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceUpdateAdCreativeResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceUpdateAdCreativeResult = map[int16]string{
	0: "success",
}

type RecommendServiceGetAdCreativeArgs struct {
	Req *GetAdCreativeRequest `thrift:"req,1" frugal:"1,default,GetAdCreativeRequest" json:"req"`
}

func NewRecommendServiceGetAdCreativeArgs() *RecommendServiceGetAdCreativeArgs {
	return &RecommendServiceGetAdCreativeArgs{}
}

func (p *RecommendServiceGetAdCreativeArgs) InitDefault() {
}

var RecommendServiceGetAdCreativeArgs_Req_DEFAULT *GetAdCreativeRequest

func (p *RecommendServiceGetAdCreativeArgs) GetReq() (v *GetAdCreativeRequest) {
	if !p.IsSetReq() {
		return RecommendServiceGetAdCreativeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceGetAdCreativeArgs) SetReq(val *GetAdCreativeRequest) {
	p.Req = val
}

func (p *RecommendServiceGetAdCreativeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceGetAdCreativeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetAdCreativeArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetAdCreativeArgs = map[int16]string{
	1: "req",
}

type RecommendServiceGetAdCreativeResult struct {
	Success *GetAdCreativeResponse `thrift:"success,0,optional" frugal:"0,optional,GetAdCreativeResponse" json:"success,omitempty"`
}

func NewRecommendServiceGetAdCreativeResult() *RecommendServiceGetAdCreativeResult {
	return &RecommendServiceGetAdCreativeResult{}
}

func (p *RecommendServiceGetAdCreativeResult) InitDefault() {
}

var RecommendServiceGetAdCreativeResult_Success_DEFAULT *GetAdCreativeResponse

func (p *RecommendServiceGetAdCreativeResult) GetSuccess() (v *GetAdCreativeResponse) {
	if !p.IsSetSuccess() {
		return RecommendServiceGetAdCreativeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceGetAdCreativeResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetAdCreativeResponse)
}

func (p *RecommendServiceGetAdCreativeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceGetAdCreativeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetAdCreativeResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetAdCreativeResult = map[int16]string{
	0: "success",
}

type RecommendServiceListAdCreativesArgs struct {
	Req *ListAdCreativesRequest `thrift:"req,1" frugal:"1,default,ListAdCreativesRequest" json:"req"`
}

func NewRecommendServiceListAdCreativesArgs() *RecommendServiceListAdCreativesArgs {
	return &RecommendServiceListAdCreativesArgs{}
}

func (p *RecommendServiceListAdCreativesArgs) InitDefault() {
}

var RecommendServiceListAdCreativesArgs_Req_DEFAULT *ListAdCreativesRequest

func (p *RecommendServiceListAdCreativesArgs) GetReq() (v *ListAdCreativesRequest) {
	if !p.IsSetReq() {
		return RecommendServiceListAdCreativesArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceListAdCreativesArgs) SetReq(val *ListAdCreativesRequest) {
	p.Req = val
}

func (p *RecommendServiceListAdCreativesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceListAdCreativesArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceListAdCreativesArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceListAdCreativesArgs = map[int16]string{
	1: "req",
}

type RecommendServiceListAdCreativesResult struct {
	Success *ListAdCreativesResponse `thrift:"success,0,optional" frugal:"0,optional,ListAdCreativesResponse" json:"success,omitempty"`
}

func NewRecommendServiceListAdCreativesResult() *RecommendServiceListAdCreativesResult {
	return &RecommendServiceListAdCreativesResult{}
}

func (p *RecommendServiceListAdCreativesResult) InitDefault() {
}

var RecommendServiceListAdCreativesResult_Success_DEFAULT *ListAdCreativesResponse

func (p *RecommendServiceListAdCreativesResult) GetSuccess() (v *ListAdCreativesResponse) {
	if !p.IsSetSuccess() {
		return RecommendServiceListAdCreativesResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceListAdCreativesResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListAdCreativesResponse)
}

func (p *RecommendServiceListAdCreativesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceListAdCreativesResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceListAdCreativesResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceListAdCreativesResult = map[int16]string{
	0: "success",
}

type RecommendServiceDeleteAdCreativeArgs struct {
	Req *DeleteAdCreativeRequest `thrift:"req,1" frugal:"1,default,DeleteAdCreativeRequest" json:"req"`
}

func NewRecommendServiceDeleteAdCreativeArgs() *RecommendServiceDeleteAdCreativeArgs {
	return &RecommendServiceDeleteAdCreativeArgs{}
}

func (p *RecommendServiceDeleteAdCreativeArgs) InitDefault() {
}

var RecommendServiceDeleteAdCreativeArgs_Req_DEFAULT *DeleteAdCreativeRequest

func (p *RecommendServiceDeleteAdCreativeArgs) GetReq() (v *DeleteAdCreativeRequest) {
	if !p.IsSetReq() {
		return RecommendServiceDeleteAdCreativeArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceDeleteAdCreativeArgs) SetReq(val *DeleteAdCreativeRequest) {
	p.Req = val
}

func (p *RecommendServiceDeleteAdCreativeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceDeleteAdCreativeArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceDeleteAdCreativeArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceDeleteAdCreativeArgs = map[int16]string{
	1: "req",
}

type RecommendServiceDeleteAdCreativeResult struct {
	Success *DeleteAdCreativeResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteAdCreativeResponse" json:"success,omitempty"`
}

func NewRecommendServiceDeleteAdCreativeResult() *RecommendServiceDeleteAdCreativeResult {
	return &RecommendServiceDeleteAdCreativeResult{}
}

func (p *RecommendServiceDeleteAdCreativeResult) InitDefault() {
}

var RecommendServiceDeleteAdCreativeResult_Success_DEFAULT *DeleteAdCreativeResponse

func (p *RecommendServiceDeleteAdCreativeResult) GetSuccess() (v *DeleteAdCreativeResponse) {
	if !p.IsSetSuccess() {
		return RecommendServiceDeleteAdCreativeResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceDeleteAdCreativeResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteAdCreativeResponse)
}

func (p *RecommendServiceDeleteAdCreativeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceDeleteAdCreativeResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceDeleteAdCreativeResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceDeleteAdCreativeResult = map[int16]string{
	0: "success",
}

type RecommendServiceAddUserInterestArgs struct {
	Req *AddUserInterestRequest `thrift:"req,1" frugal:"1,default,AddUserInterestRequest" json:"req"`
}

func NewRecommendServiceAddUserInterestArgs() *RecommendServiceAddUserInterestArgs {
	return &RecommendServiceAddUserInterestArgs{}
}

func (p *RecommendServiceAddUserInterestArgs) InitDefault() {
}

var RecommendServiceAddUserInterestArgs_Req_DEFAULT *AddUserInterestRequest

func (p *RecommendServiceAddUserInterestArgs) GetReq() (v *AddUserInterestRequest) {
	if !p.IsSetReq() {
		return RecommendServiceAddUserInterestArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceAddUserInterestArgs) SetReq(val *AddUserInterestRequest) {
	p.Req = val
}

func (p *RecommendServiceAddUserInterestArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceAddUserInterestArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceAddUserInterestArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceAddUserInterestArgs = map[int16]string{
	1: "req",
}

type RecommendServiceAddUserInterestResult struct {
	Success *AddUserInterestResponse `thrift:"success,0,optional" frugal:"0,optional,AddUserInterestResponse" json:"success,omitempty"`
}

func NewRecommendServiceAddUserInterestResult() *RecommendServiceAddUserInterestResult {
	return &RecommendServiceAddUserInterestResult{}
}

func (p *RecommendServiceAddUserInterestResult) InitDefault() {
}

var RecommendServiceAddUserInterestResult_Success_DEFAULT *AddUserInterestResponse

func (p *RecommendServiceAddUserInterestResult) GetSuccess() (v *AddUserInterestResponse) {
	if !p.IsSetSuccess() {
		return RecommendServiceAddUserInterestResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceAddUserInterestResult) SetSuccess(x interface{}) {
	p.Success = x.(*AddUserInterestResponse)
}

func (p *RecommendServiceAddUserInterestResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceAddUserInterestResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceAddUserInterestResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceAddUserInterestResult = map[int16]string{
	0: "success",
}

type RecommendServiceUpdateUserInterestArgs struct {
	Req *UpdateUserInterestRequest `thrift:"req,1" frugal:"1,default,UpdateUserInterestRequest" json:"req"`
}

func NewRecommendServiceUpdateUserInterestArgs() *RecommendServiceUpdateUserInterestArgs {
	return &RecommendServiceUpdateUserInterestArgs{}
}

func (p *RecommendServiceUpdateUserInterestArgs) InitDefault() {
}

var RecommendServiceUpdateUserInterestArgs_Req_DEFAULT *UpdateUserInterestRequest

func (p *RecommendServiceUpdateUserInterestArgs) GetReq() (v *UpdateUserInterestRequest) {
	if !p.IsSetReq() {
		return RecommendServiceUpdateUserInterestArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceUpdateUserInterestArgs) SetReq(val *UpdateUserInterestRequest) {
	p.Req = val
}

func (p *RecommendServiceUpdateUserInterestArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceUpdateUserInterestArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceUpdateUserInterestArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceUpdateUserInterestArgs = map[int16]string{
	1: "req",
}

type RecommendServiceUpdateUserInterestResult struct {
	Success *UpdateUserInterestResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateUserInterestResponse" json:"success,omitempty"`
}

func NewRecommendServiceUpdateUserInterestResult() *RecommendServiceUpdateUserInterestResult {
	return &RecommendServiceUpdateUserInterestResult{}
}

func (p *RecommendServiceUpdateUserInterestResult) InitDefault() {
}

var RecommendServiceUpdateUserInterestResult_Success_DEFAULT *UpdateUserInterestResponse

func (p *RecommendServiceUpdateUserInterestResult) GetSuccess() (v *UpdateUserInterestResponse) {
	if !p.IsSetSuccess() {
		return RecommendServiceUpdateUserInterestResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceUpdateUserInterestResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateUserInterestResponse)
}

func (p *RecommendServiceUpdateUserInterestResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceUpdateUserInterestResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceUpdateUserInterestResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceUpdateUserInterestResult = map[int16]string{
	0: "success",
}

type RecommendServiceGetUserInterestsArgs struct {
	Req *GetUserInterestsRequest `thrift:"req,1" frugal:"1,default,GetUserInterestsRequest" json:"req"`
}

func NewRecommendServiceGetUserInterestsArgs() *RecommendServiceGetUserInterestsArgs {
	return &RecommendServiceGetUserInterestsArgs{}
}

func (p *RecommendServiceGetUserInterestsArgs) InitDefault() {
}

var RecommendServiceGetUserInterestsArgs_Req_DEFAULT *GetUserInterestsRequest

func (p *RecommendServiceGetUserInterestsArgs) GetReq() (v *GetUserInterestsRequest) {
	if !p.IsSetReq() {
		return RecommendServiceGetUserInterestsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceGetUserInterestsArgs) SetReq(val *GetUserInterestsRequest) {
	p.Req = val
}

func (p *RecommendServiceGetUserInterestsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceGetUserInterestsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetUserInterestsArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetUserInterestsArgs = map[int16]string{
	1: "req",
}

type RecommendServiceGetUserInterestsResult struct {
	Success *GetUserInterestsResponse `thrift:"success,0,optional" frugal:"0,optional,GetUserInterestsResponse" json:"success,omitempty"`
}

func NewRecommendServiceGetUserInterestsResult() *RecommendServiceGetUserInterestsResult {
	return &RecommendServiceGetUserInterestsResult{}
}

func (p *RecommendServiceGetUserInterestsResult) InitDefault() {
}

var RecommendServiceGetUserInterestsResult_Success_DEFAULT *GetUserInterestsResponse

func (p *RecommendServiceGetUserInterestsResult) GetSuccess() (v *GetUserInterestsResponse) {
	if !p.IsSetSuccess() {
		return RecommendServiceGetUserInterestsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceGetUserInterestsResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserInterestsResponse)
}

func (p *RecommendServiceGetUserInterestsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceGetUserInterestsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetUserInterestsResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetUserInterestsResult = map[int16]string{
	0: "success",
}

type RecommendServiceDeleteUserInterestArgs struct {
	Req *DeleteUserInterestRequest `thrift:"req,1" frugal:"1,default,DeleteUserInterestRequest" json:"req"`
}

func NewRecommendServiceDeleteUserInterestArgs() *RecommendServiceDeleteUserInterestArgs {
	return &RecommendServiceDeleteUserInterestArgs{}
}

func (p *RecommendServiceDeleteUserInterestArgs) InitDefault() {
}

var RecommendServiceDeleteUserInterestArgs_Req_DEFAULT *DeleteUserInterestRequest

func (p *RecommendServiceDeleteUserInterestArgs) GetReq() (v *DeleteUserInterestRequest) {
	if !p.IsSetReq() {
		return RecommendServiceDeleteUserInterestArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceDeleteUserInterestArgs) SetReq(val *DeleteUserInterestRequest) {
	p.Req = val
}

func (p *RecommendServiceDeleteUserInterestArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceDeleteUserInterestArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceDeleteUserInterestArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceDeleteUserInterestArgs = map[int16]string{
	1: "req",
}

type RecommendServiceDeleteUserInterestResult struct {
	Success *DeleteUserInterestResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteUserInterestResponse" json:"success,omitempty"`
}

func NewRecommendServiceDeleteUserInterestResult() *RecommendServiceDeleteUserInterestResult {
	return &RecommendServiceDeleteUserInterestResult{}
}

func (p *RecommendServiceDeleteUserInterestResult) InitDefault() {
}

var RecommendServiceDeleteUserInterestResult_Success_DEFAULT *DeleteUserInterestResponse

func (p *RecommendServiceDeleteUserInterestResult) GetSuccess() (v *DeleteUserInterestResponse) {
	if !p.IsSetSuccess() {
		return RecommendServiceDeleteUserInterestResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceDeleteUserInterestResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteUserInterestResponse)
}

func (p *RecommendServiceDeleteUserInterestResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceDeleteUserInterestResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceDeleteUserInterestResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceDeleteUserInterestResult = map[int16]string{
	0: "success",
}

type RecommendServiceCreateAdEventArgs struct {
	Req *CreateAdEventRequest `thrift:"req,1" frugal:"1,default,CreateAdEventRequest" json:"req"`
}

func NewRecommendServiceCreateAdEventArgs() *RecommendServiceCreateAdEventArgs {
	return &RecommendServiceCreateAdEventArgs{}
}

func (p *RecommendServiceCreateAdEventArgs) InitDefault() {
}

var RecommendServiceCreateAdEventArgs_Req_DEFAULT *CreateAdEventRequest

func (p *RecommendServiceCreateAdEventArgs) GetReq() (v *CreateAdEventRequest) {
	if !p.IsSetReq() {
		return RecommendServiceCreateAdEventArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceCreateAdEventArgs) SetReq(val *CreateAdEventRequest) {
	p.Req = val
}

func (p *RecommendServiceCreateAdEventArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceCreateAdEventArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceCreateAdEventArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceCreateAdEventArgs = map[int16]string{
	1: "req",
}

type RecommendServiceCreateAdEventResult struct {
	Success *CreateAdEventResponse `thrift:"success,0,optional" frugal:"0,optional,CreateAdEventResponse" json:"success,omitempty"`
}

func NewRecommendServiceCreateAdEventResult() *RecommendServiceCreateAdEventResult {
	return &RecommendServiceCreateAdEventResult{}
}

func (p *RecommendServiceCreateAdEventResult) InitDefault() {
}

var RecommendServiceCreateAdEventResult_Success_DEFAULT *CreateAdEventResponse

func (p *RecommendServiceCreateAdEventResult) GetSuccess() (v *CreateAdEventResponse) {
	if !p.IsSetSuccess() {
		return RecommendServiceCreateAdEventResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceCreateAdEventResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateAdEventResponse)
}

func (p *RecommendServiceCreateAdEventResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceCreateAdEventResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceCreateAdEventResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceCreateAdEventResult = map[int16]string{
	0: "success",
}

type RecommendServiceGetUserAdEventsArgs struct {
	Req *GetUserAdEventsRequest `thrift:"req,1" frugal:"1,default,GetUserAdEventsRequest" json:"req"`
}

func NewRecommendServiceGetUserAdEventsArgs() *RecommendServiceGetUserAdEventsArgs {
	return &RecommendServiceGetUserAdEventsArgs{}
}

func (p *RecommendServiceGetUserAdEventsArgs) InitDefault() {
}

var RecommendServiceGetUserAdEventsArgs_Req_DEFAULT *GetUserAdEventsRequest

func (p *RecommendServiceGetUserAdEventsArgs) GetReq() (v *GetUserAdEventsRequest) {
	if !p.IsSetReq() {
		return RecommendServiceGetUserAdEventsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceGetUserAdEventsArgs) SetReq(val *GetUserAdEventsRequest) {
	p.Req = val
}

func (p *RecommendServiceGetUserAdEventsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceGetUserAdEventsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetUserAdEventsArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetUserAdEventsArgs = map[int16]string{
	1: "req",
}

type RecommendServiceGetUserAdEventsResult struct {
	Success *GetUserAdEventsResponse `thrift:"success,0,optional" frugal:"0,optional,GetUserAdEventsResponse" json:"success,omitempty"`
}

func NewRecommendServiceGetUserAdEventsResult() *RecommendServiceGetUserAdEventsResult {
	return &RecommendServiceGetUserAdEventsResult{}
}

func (p *RecommendServiceGetUserAdEventsResult) InitDefault() {
}

var RecommendServiceGetUserAdEventsResult_Success_DEFAULT *GetUserAdEventsResponse

func (p *RecommendServiceGetUserAdEventsResult) GetSuccess() (v *GetUserAdEventsResponse) {
	if !p.IsSetSuccess() {
		return RecommendServiceGetUserAdEventsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceGetUserAdEventsResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserAdEventsResponse)
}

func (p *RecommendServiceGetUserAdEventsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceGetUserAdEventsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetUserAdEventsResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetUserAdEventsResult = map[int16]string{
	0: "success",
}

type RecommendServiceGetCreativeAdEventsArgs struct {
	Req *GetCreativeAdEventsRequest `thrift:"req,1" frugal:"1,default,GetCreativeAdEventsRequest" json:"req"`
}

func NewRecommendServiceGetCreativeAdEventsArgs() *RecommendServiceGetCreativeAdEventsArgs {
	return &RecommendServiceGetCreativeAdEventsArgs{}
}

func (p *RecommendServiceGetCreativeAdEventsArgs) InitDefault() {
}

var RecommendServiceGetCreativeAdEventsArgs_Req_DEFAULT *GetCreativeAdEventsRequest

func (p *RecommendServiceGetCreativeAdEventsArgs) GetReq() (v *GetCreativeAdEventsRequest) {
	if !p.IsSetReq() {
		return RecommendServiceGetCreativeAdEventsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceGetCreativeAdEventsArgs) SetReq(val *GetCreativeAdEventsRequest) {
	p.Req = val
}

func (p *RecommendServiceGetCreativeAdEventsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceGetCreativeAdEventsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetCreativeAdEventsArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetCreativeAdEventsArgs = map[int16]string{
	1: "req",
}

type RecommendServiceGetCreativeAdEventsResult struct {
	Success *GetCreativeAdEventsResponse `thrift:"success,0,optional" frugal:"0,optional,GetCreativeAdEventsResponse" json:"success,omitempty"`
}

func NewRecommendServiceGetCreativeAdEventsResult() *RecommendServiceGetCreativeAdEventsResult {
	return &RecommendServiceGetCreativeAdEventsResult{}
}

func (p *RecommendServiceGetCreativeAdEventsResult) InitDefault() {
}

var RecommendServiceGetCreativeAdEventsResult_Success_DEFAULT *GetCreativeAdEventsResponse

func (p *RecommendServiceGetCreativeAdEventsResult) GetSuccess() (v *GetCreativeAdEventsResponse) {
	if !p.IsSetSuccess() {
		return RecommendServiceGetCreativeAdEventsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceGetCreativeAdEventsResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetCreativeAdEventsResponse)
}

func (p *RecommendServiceGetCreativeAdEventsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceGetCreativeAdEventsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetCreativeAdEventsResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetCreativeAdEventsResult = map[int16]string{
	0: "success",
}

type RecommendServiceGetAdvertRecommendArgs struct {
	Req *GetAdvertRecommendRequest `thrift:"req,1" frugal:"1,default,GetAdvertRecommendRequest" json:"req"`
}

func NewRecommendServiceGetAdvertRecommendArgs() *RecommendServiceGetAdvertRecommendArgs {
	return &RecommendServiceGetAdvertRecommendArgs{}
}

func (p *RecommendServiceGetAdvertRecommendArgs) InitDefault() {
}

var RecommendServiceGetAdvertRecommendArgs_Req_DEFAULT *GetAdvertRecommendRequest

func (p *RecommendServiceGetAdvertRecommendArgs) GetReq() (v *GetAdvertRecommendRequest) {
	if !p.IsSetReq() {
		return RecommendServiceGetAdvertRecommendArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *RecommendServiceGetAdvertRecommendArgs) SetReq(val *GetAdvertRecommendRequest) {
	p.Req = val
}

func (p *RecommendServiceGetAdvertRecommendArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *RecommendServiceGetAdvertRecommendArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetAdvertRecommendArgs(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetAdvertRecommendArgs = map[int16]string{
	1: "req",
}

type RecommendServiceGetAdvertRecommendResult struct {
	Success *GetAdvertRecommendResponse `thrift:"success,0,optional" frugal:"0,optional,GetAdvertRecommendResponse" json:"success,omitempty"`
}

func NewRecommendServiceGetAdvertRecommendResult() *RecommendServiceGetAdvertRecommendResult {
	return &RecommendServiceGetAdvertRecommendResult{}
}

func (p *RecommendServiceGetAdvertRecommendResult) InitDefault() {
}

var RecommendServiceGetAdvertRecommendResult_Success_DEFAULT *GetAdvertRecommendResponse

func (p *RecommendServiceGetAdvertRecommendResult) GetSuccess() (v *GetAdvertRecommendResponse) {
	if !p.IsSetSuccess() {
		return RecommendServiceGetAdvertRecommendResult_Success_DEFAULT
	}
	return p.Success
}
func (p *RecommendServiceGetAdvertRecommendResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetAdvertRecommendResponse)
}

func (p *RecommendServiceGetAdvertRecommendResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *RecommendServiceGetAdvertRecommendResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RecommendServiceGetAdvertRecommendResult(%+v)", *p)
}

var fieldIDToName_RecommendServiceGetAdvertRecommendResult = map[int16]string{
	0: "success",
}
